# Example compose for subflux. See the README for all configuration options and hardening.
services:
  subflux:
    image: ghcr.io/cplieger/subflux:latest
    container_name: subflux
    restart: unless-stopped
    user: "1000:1000"  # match your host user

    environment:
      TZ: "Europe/Paris"

    ports:
      - "8374:8374"

    volumes:
      - "/opt/appdata/subflux:/config"
      - "/path/to/media:/media"
