package server

import (
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/cplieger/auth/v5"
)

// --- handleUI tests ---

func TestHandleUI_serves_index_at_root(t *testing.T) {
	t.Parallel()
	s := newTestServer(t, &qhMockStore{})

	req := httptest.NewRequestWithContext(t.Context(),
		http.MethodGet, "/", http.NoBody)
	rec := httptest.NewRecorder()
	s.handleUI(rec, req)

	if rec.Code != http.StatusOK {
		t.Errorf("handleUI(/) status = %d, want %d", rec.Code, http.StatusOK)
	}
	if ct := rec.Header().Get("Content-Type"); !strings.Contains(ct, "text/html") {
		t.Errorf("handleUI(/) Content-Type = %q, want text/html", ct)
	}
}

func TestHandleUI_serves_static_file(t *testing.T) {
	t.Parallel()
	s := newTestServer(t, &qhMockStore{})

	// favicon.svg is tracked in internal/server/static/; CSS bundles
	// (style.css, login.css) are generated by the Dockerfile and not
	// available at test time, so we use a tracked asset instead.
	req := httptest.NewRequestWithContext(t.Context(),
		http.MethodGet, "/favicon.svg", http.NoBody)
	rec := httptest.NewRecorder()
	s.handleUI(rec, req)

	if rec.Code != http.StatusOK {
		t.Errorf("handleUI(/favicon.svg) status = %d, want %d", rec.Code, http.StatusOK)
	}
	if ct := rec.Header().Get("Content-Type"); !strings.Contains(ct, "svg") {
		t.Errorf("handleUI(/favicon.svg) Content-Type = %q, want svg", ct)
	}
}

func TestHandleUI_spa_fallback_for_unknown_path(t *testing.T) {
	t.Parallel()
	s := newTestServer(t, &qhMockStore{})

	req := httptest.NewRequestWithContext(t.Context(),
		http.MethodGet, "/history/some-id", http.NoBody)
	rec := httptest.NewRecorder()
	s.handleUI(rec, req)

	if rec.Code != http.StatusOK {
		t.Errorf("handleUI(/history/some-id) status = %d, want %d", rec.Code, http.StatusOK)
	}
	// SPA fallback should serve index.html.
	if ct := rec.Header().Get("Content-Type"); !strings.Contains(ct, "text/html") {
		t.Errorf("handleUI(/history/some-id) Content-Type = %q, want text/html (SPA fallback)", ct)
	}
}

func TestHandleUI_directory_path_serves_index(t *testing.T) {
	t.Parallel()
	s := newTestServer(t, &qhMockStore{})

	// /icons/ is a directory in the embedded FS; should fall through to index.html.
	req := httptest.NewRequestWithContext(t.Context(),
		http.MethodGet, "/icons/", http.NoBody)
	rec := httptest.NewRecorder()
	s.handleUI(rec, req)

	if rec.Code != http.StatusOK {
		t.Errorf("handleUI(/icons/) status = %d, want %d", rec.Code, http.StatusOK)
	}
	if ct := rec.Header().Get("Content-Type"); !strings.Contains(ct, "text/html") {
		t.Errorf("handleUI(/icons/) Content-Type = %q, want text/html (directory fallback)", ct)
	}
}

func TestHandleUI_gz_sibling_not_addressable(t *testing.T) {
	t.Parallel()
	s := newTestServer(t, &qhMockStore{})

	// The precompressed .gz siblings are a transport encoding served for
	// their base asset, never resources of their own: a direct request
	// falls through to the SPA fallback like any unknown path.
	req := httptest.NewRequestWithContext(t.Context(),
		http.MethodGet, "/app.js.gz", http.NoBody)
	rec := httptest.NewRecorder()
	s.handleUI(rec, req)

	if rec.Code != http.StatusOK {
		t.Errorf("handleUI(/app.js.gz) status = %d, want %d", rec.Code, http.StatusOK)
	}
	if ct := rec.Header().Get("Content-Type"); !strings.Contains(ct, "text/html") {
		t.Errorf("handleUI(/app.js.gz) Content-Type = %q, want text/html (fallback)", ct)
	}
}

// rejectingAuthenticator is bypassAuthenticator's opposite: a
// sessionAuthenticator double that authenticates nothing, for the handleUI
// branches that turn on the request being anonymous.
type rejectingAuthenticator struct{}

func (rejectingAuthenticator) Authenticate(*http.Request) (*auth.User, string, error) {
	return nil, "", auth.ErrUnauthenticated
}

func (rejectingAuthenticator) RequireAuth(http.ResponseWriter, *http.Request) (*auth.User, string, bool) {
	return nil, "", false
}

// TestHandleUI_setup_path_serves_the_login_bundle pins the wizard's address in
// BOTH auth states, which is the whole point of it having one: creating the
// admin is step one of setup and it issues a session, so from step two onward a
// reload is an authenticated request. Before this path existed such a request
// fell through to index.html and dropped the operator into the app's
// unconfigured settings dialog with the half-finished wizard gone.
//
// Neither case carries an Accept header, so both also pin that the branch sits
// ABOVE the auth check and answers without consulting it or auth.IsBrowserRequest
// — the same public reachability /login.html already has for a browser, over a
// static shell that carries nothing a caller could not get from the login page.
//
// Asserted by which bundle the document loads rather than by Content-Type: both
// entrypoints are text/html, so a status-and-type check passes on the wrong one.
func TestHandleUI_setup_path_serves_the_login_bundle(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name string
		auth sessionAuthenticator
	}{
		{name: "authenticated", auth: bypassAuthenticator{}},
		{name: "anonymous", auth: rejectingAuthenticator{}},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			s := newTestServer(t, &qhMockStore{})
			s.authenticator = tt.auth

			req := httptest.NewRequestWithContext(t.Context(),
				http.MethodGet, "/setup", http.NoBody)
			rec := httptest.NewRecorder()
			s.handleUI(rec, req)

			if rec.Code != http.StatusOK {
				t.Errorf("handleUI(/setup) status = %d, want %d", rec.Code, http.StatusOK)
			}
			body := rec.Body.String()
			if !strings.Contains(body, "/login.js") {
				t.Errorf("handleUI(/setup) served a document without /login.js, want the login bundle")
			}
			if strings.Contains(body, "/app.js") {
				t.Errorf("handleUI(/setup) served the app bundle, want the login bundle")
			}
		})
	}
}

// TestHandleUI_root_still_serves_the_app_bundle is the control for the test
// above: the setup path must not have generalized into "authenticated
// navigations get login.html".
func TestHandleUI_root_still_serves_the_app_bundle(t *testing.T) {
	t.Parallel()
	s := newTestServer(t, &qhMockStore{})

	req := httptest.NewRequestWithContext(t.Context(),
		http.MethodGet, "/", http.NoBody)
	rec := httptest.NewRecorder()
	s.handleUI(rec, req)

	if !strings.Contains(rec.Body.String(), "/app.js") {
		t.Errorf("handleUI(/) served a document without /app.js, want the app bundle")
	}
}
