package server

import (
	"context"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
)

// --- handleUI tests ---

func TestHandleUI_serves_index_at_root(t *testing.T) {
	t.Parallel()
	s := newTestServer(&qhMockStore{}, &qhMockConfig{})

	req := httptest.NewRequestWithContext(context.Background(),
		http.MethodGet, "/", http.NoBody)
	rec := httptest.NewRecorder()
	s.handleUI(rec, req)

	if rec.Code != http.StatusOK {
		t.Errorf("handleUI(/) status = %d, want %d", rec.Code, http.StatusOK)
	}
	if ct := rec.Header().Get("Content-Type"); !strings.Contains(ct, "text/html") {
		t.Errorf("handleUI(/) Content-Type = %q, want text/html", ct)
	}
}

func TestHandleUI_serves_static_file(t *testing.T) {
	t.Parallel()
	s := newTestServer(&qhMockStore{}, &qhMockConfig{})

	// favicon.svg is tracked in internal/server/static/; CSS bundles
	// (style.css, login.css) are generated by the Dockerfile and not
	// available at test time, so we use a tracked asset instead.
	req := httptest.NewRequestWithContext(context.Background(),
		http.MethodGet, "/favicon.svg", http.NoBody)
	rec := httptest.NewRecorder()
	s.handleUI(rec, req)

	if rec.Code != http.StatusOK {
		t.Errorf("handleUI(/favicon.svg) status = %d, want %d", rec.Code, http.StatusOK)
	}
	if ct := rec.Header().Get("Content-Type"); !strings.Contains(ct, "svg") {
		t.Errorf("handleUI(/favicon.svg) Content-Type = %q, want svg", ct)
	}
}

func TestHandleUI_spa_fallback_for_unknown_path(t *testing.T) {
	t.Parallel()
	s := newTestServer(&qhMockStore{}, &qhMockConfig{})

	req := httptest.NewRequestWithContext(context.Background(),
		http.MethodGet, "/history/some-id", http.NoBody)
	rec := httptest.NewRecorder()
	s.handleUI(rec, req)

	if rec.Code != http.StatusOK {
		t.Errorf("handleUI(/history/some-id) status = %d, want %d", rec.Code, http.StatusOK)
	}
	// SPA fallback should serve index.html.
	if ct := rec.Header().Get("Content-Type"); !strings.Contains(ct, "text/html") {
		t.Errorf("handleUI(/history/some-id) Content-Type = %q, want text/html (SPA fallback)", ct)
	}
}

func TestHandleUI_directory_path_serves_index(t *testing.T) {
	t.Parallel()
	s := newTestServer(&qhMockStore{}, &qhMockConfig{})

	// /icons/ is a directory in the embedded FS; should fall through to index.html.
	req := httptest.NewRequestWithContext(context.Background(),
		http.MethodGet, "/icons/", http.NoBody)
	rec := httptest.NewRecorder()
	s.handleUI(rec, req)

	if rec.Code != http.StatusOK {
		t.Errorf("handleUI(/icons/) status = %d, want %d", rec.Code, http.StatusOK)
	}
	if ct := rec.Header().Get("Content-Type"); !strings.Contains(ct, "text/html") {
		t.Errorf("handleUI(/icons/) Content-Type = %q, want text/html (directory fallback)", ct)
	}
}

func TestHandleUI_gz_sibling_not_addressable(t *testing.T) {
	t.Parallel()
	s := newTestServer(&qhMockStore{}, &qhMockConfig{})

	// The precompressed .gz siblings are a transport encoding served for
	// their base asset, never resources of their own: a direct request
	// falls through to the SPA fallback like any unknown path.
	req := httptest.NewRequestWithContext(context.Background(),
		http.MethodGet, "/app.js.gz", http.NoBody)
	rec := httptest.NewRecorder()
	s.handleUI(rec, req)

	if rec.Code != http.StatusOK {
		t.Errorf("handleUI(/app.js.gz) status = %d, want %d", rec.Code, http.StatusOK)
	}
	if ct := rec.Header().Get("Content-Type"); !strings.Contains(ct, "text/html") {
		t.Errorf("handleUI(/app.js.gz) Content-Type = %q, want text/html (fallback)", ct)
	}
}
