// Package wirespec is the single source of truth for subflux's HTTP wire
// contract: the registered wire types, enums, and the endpoint table that
// cmd/wire-codegen feeds into wiregen to emit the TS types, decoders, typed
// client, and the Go path constants (internal/apipaths).
//
// routes.go (internal/server) stays authoritative for PERMISSIONS — each
// endpoint's AuthGroup here is checked against the actual route registration
// by internal/server's wirespec consistency test, so the two tables cannot
// drift silently.
//
// wiregen is a build-time-only dependency: this package is imported by
// cmd/wire-codegen and by tests, never by the server runtime.
//
// The Unix-socket admin plane (POST /api/admin/bootstrap, served via
// server.AdminHandler on config.AdminSocketPath) is DELIBERATELY off this
// table: it is not part of the TCP wire contract, has no browser consumer,
// and its path constant is hand-written in internal/config so the CLI's
// socket client and main.go share it without generated code.
package wirespec

import (
	"net/http"

	authwebauthn "github.com/cplieger/auth/v5/webauthn"
	"github.com/cplieger/subflux/internal/server/activity"
	"github.com/cplieger/subflux/internal/server/authhandlers"
	"github.com/cplieger/subflux/internal/server/confighandlers"
	"github.com/cplieger/subflux/internal/server/coverage"
	"github.com/cplieger/subflux/internal/server/coveragehandlers"
	"github.com/cplieger/subflux/internal/server/events"
	"github.com/cplieger/subflux/internal/server/filehandlers"
	"github.com/cplieger/subflux/internal/server/manualops"
	"github.com/cplieger/subflux/internal/server/mediahandlers"
	"github.com/cplieger/subflux/internal/server/previewhandlers"
	"github.com/cplieger/subflux/internal/server/queryhandlers"
	"github.com/cplieger/subflux/internal/server/resolve"
	"github.com/cplieger/subflux/internal/server/scanning"
	"github.com/cplieger/subflux/internal/server/synchandlers"
	"github.com/cplieger/subflux/internal/server/syncjobs"
	"github.com/cplieger/subflux/internal/subflux"
	"github.com/cplieger/wiregen/v3"
)

// Auth group tags. Values match the route group names in
// internal/server/routes.go; the consistency test compares them.
const (
	GroupPublic          = "public"
	GroupUser            = "user"
	GroupAdmin           = "admin"
	GroupUserConfigured  = "userConfigured"
	GroupAdminConfigured = "adminConfigured"
)

// pathConfig is the raw-YAML config endpoint path, shared by its GET/PUT/POST
// verb entries in the endpoint table.
const pathConfig = "/api/config"

// Registry returns the fully-populated wiregen registry: types, enums, name
// overrides, and the endpoint table.
func Registry() *wiregen.Registry {
	r := wiregen.NewRegistry(
		wiregen.WithValidatorsImport("../validators.js"),
		// The validators module is library-owned generated output (wiregen
		// v2): Generate rewrites it next to the hand-written source on every
		// run. Never hand-edit it.
		wiregen.WithValidatorsFile("../validators.ts"),
		wiregen.WithTransportImport("../api-client.js"),
		wiregen.WithHeaderComment("// CODE-GENERATED by cmd/wire-codegen, DO NOT EDIT.\n\n"),
	)

	r.Types = []wiregen.WireType{
		wiregen.TypeRef[coverage.TargetCoverage](),
		wiregen.TypeRef[coveragehandlers.SeriesItem](),
		wiregen.TypeRef[coveragehandlers.MovieItem](),
		wiregen.TypeRef[subflux.SubtitleEntry](),
		wiregen.TypeRef[subflux.Stats](),
		wiregen.TypeRef[subflux.ProviderStatus](),
		wiregen.TypeRef[subflux.ProvidersResponse](),
		wiregen.TypeRef[subflux.MeResponse](),
		wiregen.TypeRef[subflux.SchemaField](),
		wiregen.TypeRef[subflux.SchemaOption](),
		wiregen.TypeRef[subflux.SchemaSection](),
		wiregen.TypeRef[subflux.ProviderSchema](),
		wiregen.TypeRef[subflux.StateEntry](),
		wiregen.TypeRef[subflux.ScorePreview](),
		wiregen.TypeRef[subflux.SearchTarget](),
		wiregen.TypeRef[subflux.SearchTargets](),
		wiregen.TypeRef[subflux.SetupStatus](),
		wiregen.TypeRef[subflux.LoginSuccess](),
		// The WebAuthn Signal API payloads, derived by auth/v5/webauthn and
		// passed straight to the browser's signal* calls by the client.
		wiregen.TypeRef[authwebauthn.Signals](),
		wiregen.TypeRef[authwebauthn.SignalCurrentUserDetails](),
		wiregen.TypeRef[authwebauthn.SignalAllAcceptedCredentials](),
		wiregen.TypeRef[subflux.PasskeyRegistered](),
		wiregen.TypeRef[subflux.KeyGenerated](),
		wiregen.TypeRef[subflux.BackoffEntry](),
		wiregen.TypeRef[subflux.ManualLockEntry](),
		wiregen.TypeRef[subflux.StatusResponse](),
		wiregen.TypeRef[subflux.AdminUserCreatedResponse](),
		wiregen.TypeRef[events.CoverageEvent](),
		wiregen.TypeRef[events.NotifyEvent](),
		wiregen.TypeRef[events.ScanEvent](),
		wiregen.TypeRef[events.EpochEvent](),
		wiregen.TypeRef[events.ActivityEvent](),
		wiregen.TypeRef[events.AlertEvent](),
		wiregen.TypeRef[events.SyncDoneEvent](),
		wiregen.TypeRef[events.ProviderEvent](),
		wiregen.TypeRef[events.ProviderTimeoutEntry](),
		// The sealed SSE union (//wiregen:union on the interface): emits the
		// TS union type + the discriminator decoders. This was the founding
		// use case for wiregen's AST engine.
		wiregen.TypeRef[events.EventData](),
		wiregen.TypeRef[activity.Entry](),
		wiregen.TypeRef[activity.Alert](),
		wiregen.TypeRef[queryhandlers.ProviderInfo](),
		wiregen.TypeRef[queryhandlers.ParsedConfig](),
		wiregen.TypeRef[subflux.LanguageRulesJSON](),
		wiregen.TypeRef[subflux.AudioRuleJSON](),
		wiregen.TypeRef[subflux.SubtitleTargJSON](),
		wiregen.TypeRef[subflux.Scores](),
		wiregen.TypeRef[subflux.PostProcessConfig](),
		wiregen.TypeRef[authhandlers.UserInfo](),
		wiregen.TypeRef[authhandlers.APIKeyInfo](),
		wiregen.TypeRef[authhandlers.PasskeyInfo](),
		wiregen.TypeRef[authhandlers.WebAuthnLoginBeginResponse](),
		wiregen.TypeRef[authhandlers.WebAuthnRegisterBeginResponse](),
		wiregen.TypeRef[confighandlers.PathValidationResponse](),
		wiregen.TypeRef[confighandlers.ConnTestResponse](),
		wiregen.TypeRef[confighandlers.StructuredConfig](),
		wiregen.TypeRef[mediahandlers.SeasonGroup](),
		wiregen.TypeRef[mediahandlers.EpisodeItem](),
		wiregen.TypeRef[manualops.ManualSearchResponse](),
		wiregen.TypeRef[manualops.SearchResult](),
		wiregen.TypeRef[manualops.DownloadAccepted](),
		wiregen.TypeRef[manualops.DownloadRequest](),
		wiregen.TypeRef[manualops.ResolveResponse](),
		wiregen.TypeRef[manualops.ResolvedItem](),
		wiregen.TypeRef[manualops.ResolveCandidate](),
		wiregen.TypeRef[manualops.ResolveSearchIDs](),
		wiregen.TypeRef[filehandlers.FileEntry](),
		wiregen.TypeRef[filehandlers.DeleteFileRequest](),
		wiregen.TypeRef[filehandlers.BulkDeleteRequest](),
		wiregen.TypeRef[synchandlers.SyncAudioRequest](),
		wiregen.TypeRef[synchandlers.SyncOffsetRequest](),
		wiregen.TypeRef[synchandlers.SyncAccepted](),
		wiregen.TypeRef[syncjobs.Job](),
		wiregen.TypeRef[resolve.FileRef](),
		wiregen.TypeRef[previewhandlers.PreviewStartResponse](),
		wiregen.TypeRef[scanning.ScanAccepted](),
	}

	// Enum values are auto-discovered from each type's const block in source.
	// Two need explicit values because they aren't discoverable that way:
	// MediaType ("series" is valid but has no const), and Role (its
	// "admin"/"user" constants live in the external github.com/cplieger/auth/v5
	// package, which wiregen does not scan for enum members).
	r.Enums = map[string]wiregen.EnumDef{
		"MediaType": {Values: []string{"movie", "episode", "series"}},
		"Role":      {Values: []string{"admin", "user"}},
		"Variant":   {}, "ScoreTier": {},
		"NotifyLevel": {}, "Source": {},
		"AlertLevel": {}, "AlertKind": {},
		// Scan scope kind + four-valued scan outcome (background scans S12);
		// both auto-discovered from the activity package's const blocks.
		"ScanKind": {}, "Outcome": {},
		// Sync job lifecycle + outcome (async sync D1), auto-discovered from
		// the syncjobs package's const blocks.
		"JobState": {}, "JobOutcome": {},
		// SSE event names (events.EventType consts) and the error-code
		// catalog (subflux.ErrorCode consts) — both auto-discovered, so a new
		// code/event lands in TS on the next generate.
		"EventType": {}, "ErrorCode": {},
		// The status-delta op discriminators (activity/alert/provider events),
		// auto-discovered from the events package's const blocks.
		"ActivityOp": {}, "AlertOp": {}, "ProviderOp": {},
	}

	// Wire DTOs are named as their TS interface, so no overrides are needed
	// except where the Go name would stutter against its package name.
	r.TSNameOverride = map[string]string{
		"TargetCoverage": "CoverageTarget", // coverage.TargetCoverage → avoid stutter
		"Entry":          "ActivityEntry",  // activity.Entry → avoid stutter
		// The *JSON suffix is a Go-side disambiguation (vs the engine's
		// runtime types); the TS side has no such collision.
		"LanguageRulesJSON": "LanguageRules",
		"AudioRuleJSON":     "AudioRule",
		"SubtitleTargJSON":  "SubtitleTarget",
	}

	// The begin-response envelopes marshal their options under a NESTED
	// "publicKey" key (webauthn.CredentialAssertion{Response ... `json:"publicKey"`}
	// wrapped again by our WebAuthn*BeginResponse.PublicKey `json:"publicKey"`),
	// so the wire shape is publicKey.publicKey.{challenge,...}. Mapping the
	// option types to the DOM's WebAuthn Level 3 JSON option types makes that
	// nesting compile-time-visible in the client (it was previously `unknown`
	// + casts one level short — a masked login/registration break), and the DOM
	// types are what the client hands straight to navigator.credentials.
	//
	// Base64URL is a []byte with base64url-string JSON, so without a mapping it
	// would emit number[].
	r.TypeMappings = map[string]string{ //nolint:gosec // G101: WebAuthn protocol TYPE names mapped to TS types; no credential material
		"github.com/cplieger/auth/v5/webauthn.CredentialAssertion": "{ publicKey: PublicKeyCredentialRequestOptionsJSON; mediation?: string }",
		"github.com/cplieger/auth/v5/webauthn.CredentialCreation":  "{ publicKey: PublicKeyCredentialCreationOptionsJSON; mediation?: string }",
		"github.com/cplieger/auth/v5/webauthn.Base64URL":           "string",
	}
	// Paired decode-time hardening: a TypeMappings entry without one emits an
	// unchecked `as` cast. Assert the nested envelope shape (object with a
	// string challenge) so future wire drift fails loudly at decode with a JSON
	// path instead of silently breaking the ceremony.
	r.DecoderMappings = map[string]string{ //nolint:gosec // G101: decoder snippets keyed by WebAuthn TYPE names; no credential material
		"github.com/cplieger/auth/v5/webauthn.CredentialAssertion": `((obj: Record<string, unknown>, key: string, path: string) => { const w = asObject(obj[key], path + "." + key); reqStr(asObject(w["publicKey"], path + "." + key + ".publicKey"), "challenge", path + "." + key + ".publicKey"); return w as unknown as { publicKey: PublicKeyCredentialRequestOptionsJSON; mediation?: string }; })`,
		"github.com/cplieger/auth/v5/webauthn.CredentialCreation":  `((obj: Record<string, unknown>, key: string, path: string) => { const w = asObject(obj[key], path + "." + key); reqStr(asObject(w["publicKey"], path + "." + key + ".publicKey"), "challenge", path + "." + key + ".publicKey"); return w as unknown as { publicKey: PublicKeyCredentialCreationOptionsJSON; mediation?: string }; })`,
		"github.com/cplieger/auth/v5/webauthn.Base64URL":           `reqStr`,
	}

	// EventData's runtime decoders: the discriminator values are the SSE
	// event names (events.EventType consts), two of which share the
	// ScanEvent payload.
	r.DiscriminatorMap = map[string]map[string]string{
		"EventData": {
			"coverage":   "CoverageEvent",
			"notify":     "NotifyEvent",
			"scan:start": "ScanEvent",
			"scan:done":  "ScanEvent",
			"epoch":      "EpochEvent",
			"activity":   "ActivityEvent",
			"alert":      "AlertEvent",
			"provider":   "ProviderEvent",
			"sync:done":  "SyncDoneEvent",
		},
	}

	r.Endpoints = Endpoints()
	return r
}

// Endpoints returns the endpoint table: every HTTP route the server
// registers, in routes.go registration order. AuthGroup mirrors the route
// group; Kind marks the documented non-JSON flows (raw) and the SSE stream.
func Endpoints() []wiregen.Endpoint {
	seriesItem := wiregen.TypeRef[coveragehandlers.SeriesItem]()
	movieItem := wiregen.TypeRef[coveragehandlers.MovieItem]()
	subtitleEntry := wiregen.TypeRef[subflux.SubtitleEntry]()
	statusResp := wiregen.TypeRef[subflux.StatusResponse]()
	scanAccepted := wiregen.TypeRef[scanning.ScanAccepted]()

	return []wiregen.Endpoint{
		// --- public ---
		{
			Name: "health", Method: http.MethodGet, Path: "/api/health", AuthGroup: GroupPublic,
			Response: statusResp, Doc: "Liveness probe; accepts any method server-side.",
		},
		{
			Name: "metrics", Method: http.MethodGet, Path: "/metrics", AuthGroup: GroupPublic,
			Kind: wiregen.KindRaw, Doc: "Prometheus exposition (text).",
		},
		{
			Name: "authSetupStatus", Method: http.MethodGet, Path: "/api/auth/setup", AuthGroup: GroupPublic,
			Response: wiregen.TypeRef[subflux.SetupStatus](),
		},
		{
			Name: "authSetupCreate", Method: http.MethodPost, Path: "/api/auth/setup", AuthGroup: GroupPublic,
			HasBody: true, Doc: "Create the initial admin account.",
		},
		{
			Name: "login", Method: http.MethodPost, Path: "/api/auth/login", AuthGroup: GroupPublic,
			HasBody: true, Response: wiregen.TypeRef[subflux.LoginSuccess](),
		},
		{Name: "logout", Method: http.MethodPost, Path: "/api/auth/logout", AuthGroup: GroupPublic},
		{
			Name: "oidcRedirect", Method: http.MethodGet, Path: "/api/auth/oidc", AuthGroup: GroupPublic,
			Kind: wiregen.KindRaw, Doc: "302 redirect into the OIDC provider.",
		},
		{
			Name: "oidcCallback", Method: http.MethodGet, Path: "/api/auth/oidc/callback", AuthGroup: GroupPublic,
			Kind: wiregen.KindRaw,
		},
		{
			Name: "oidcLink", Method: http.MethodPost, Path: "/api/auth/oidc/link", AuthGroup: GroupPublic,
			HasBody: true,
		},
		{
			Name: "webauthnLoginBegin", Method: http.MethodPost, Path: "/api/auth/webauthn/login/begin",
			AuthGroup: GroupPublic, Query: true,
			Response: wiregen.TypeRef[authhandlers.WebAuthnLoginBeginResponse](),
		},
		{
			Name: "webauthnLoginFinish", Method: http.MethodPost, Path: "/api/auth/webauthn/login/finish",
			AuthGroup: GroupPublic, Kind: wiregen.KindRaw,
			Doc: "WebAuthn assertion finish; hand-authored flow (documented non-JSON).",
		},

		// --- user ---
		{
			Name: "events", Method: http.MethodGet, Path: "/api/events", AuthGroup: GroupUser,
			Kind: wiregen.KindSSE, Doc: "Server-sent events stream (EventSource).",
		},
		{
			Name: "me", Method: http.MethodGet, Path: "/api/auth/me", AuthGroup: GroupUser,
			Response: wiregen.TypeRef[subflux.MeResponse](),
		},
		{
			Name: "changePassword", Method: http.MethodPut, Path: "/api/auth/password", AuthGroup: GroupUser,
			HasBody: true,
		},
		{
			Name: "updateProfile", Method: http.MethodPut, Path: "/api/auth/profile", AuthGroup: GroupUser,
			HasBody: true,
		},
		{
			Name: "listPasskeys", Method: http.MethodGet, Path: "/api/auth/passkeys", AuthGroup: GroupUser,
			Response: wiregen.TypeRef[authhandlers.PasskeyInfo](), RespShape: wiregen.RespArray,
		},
		{
			Name: "webauthnSignalData", Method: http.MethodGet, Path: "/api/auth/webauthn/signal-data",
			AuthGroup: GroupUser, Response: wiregen.TypeRef[authwebauthn.Signals](),
		},
		{
			Name: "webauthnRegisterBegin", Method: http.MethodPost, Path: "/api/auth/webauthn/register/begin",
			AuthGroup: GroupUser, HasBody: true,
			Response: wiregen.TypeRef[authhandlers.WebAuthnRegisterBeginResponse](),
		},
		{
			Name: "webauthnRegisterFinish", Method: http.MethodPost, Path: "/api/auth/webauthn/register/finish",
			AuthGroup: GroupUser, Kind: wiregen.KindRaw,
			Doc: "WebAuthn attestation finish; needs the X-WebAuthn-Session header, which the generated client has no seam for.",
		},
		{
			Name: "renamePasskey", Method: http.MethodPut, Path: "/api/auth/passkeys/{id}", AuthGroup: GroupUser,
			HasBody: true,
		},
		{
			Name: "configSchema", Method: http.MethodGet, Path: "/api/config/schema", AuthGroup: GroupUser,
			Response: wiregen.TypeRef[subflux.SchemaSection](), RespShape: wiregen.RespArray,
		},
		{
			Name: "validateConfigPath", Method: http.MethodPost, Path: "/api/config/validate-path",
			AuthGroup: GroupAdmin, HasBody: true,
			Doc:      "Config-time directory probe; the one deliberate path-accepting endpoint.",
			Response: wiregen.TypeRef[confighandlers.PathValidationResponse](),
		},
		{
			Name: "testConnection", Method: http.MethodPost, Path: "/api/config/test-connection",
			AuthGroup: GroupAdmin, HasBody: true,
			Doc:      "Live Sonarr/Radarr reachability + API-key check; a failed test is 200 with valid=false.",
			Response: wiregen.TypeRef[confighandlers.ConnTestResponse](),
		},
		{
			Name: "listAlerts", Method: http.MethodGet, Path: "/api/alerts", AuthGroup: GroupUser,
			Response: wiregen.TypeRef[activity.Alert](), RespShape: wiregen.RespArray,
		},
		{
			Name: "dismissAlert", Method: http.MethodDelete, Path: "/api/alerts", AuthGroup: GroupUser,
			Query: true,
		},
		{
			Name: "listActivity", Method: http.MethodGet, Path: "/api/activity", AuthGroup: GroupUser,
			Response: wiregen.TypeRef[activity.Entry](), RespShape: wiregen.RespArray,
		},
		{
			Name: "dismissActivity", Method: http.MethodDelete, Path: "/api/activity", AuthGroup: GroupUser,
			Query: true,
			Doc:   "Dismiss a completed entry or cancel a QUEUED one; never stops running work (see cancelActivity).",
		},
		{
			Name: "cancelActivity", Method: http.MethodPost, Path: "/api/activity/{id}/cancel",
			AuthGroup: GroupUserConfigured,
			Doc:       "Gracefully stop a running background scan after the current item. Object-level role: per-item scans any user, full scans admin. 204 stopped/already stopping, 404 unknown, 409 not cancellable.",
		},
		{
			Name: "deletePasskey", Method: http.MethodDelete, Path: "/api/auth/passkeys/{id}",
			AuthGroup: GroupUser,
		},
		{Name: "oidcUnlink", Method: http.MethodDelete, Path: "/api/auth/oidc/link", AuthGroup: GroupUser},

		// --- admin ---
		{
			Name: "listUsers", Method: http.MethodGet, Path: "/api/auth/users", AuthGroup: GroupAdmin,
			Response: wiregen.TypeRef[authhandlers.UserInfo](), RespShape: wiregen.RespArray,
		},
		{
			Name: "createUser", Method: http.MethodPost, Path: "/api/auth/users", AuthGroup: GroupAdmin,
			HasBody: true, Response: wiregen.TypeRef[subflux.AdminUserCreatedResponse](),
		},
		{Name: "deleteUser", Method: http.MethodDelete, Path: "/api/auth/users/{id}", AuthGroup: GroupAdmin},
		{
			Name: "listAPIKeys", Method: http.MethodGet, Path: "/api/auth/apikeys", AuthGroup: GroupAdmin,
			Response: wiregen.TypeRef[authhandlers.APIKeyInfo](), RespShape: wiregen.RespArray,
		},
		{
			Name: "generateAPIKey", Method: http.MethodPost, Path: "/api/auth/apikeys", AuthGroup: GroupAdmin,
			HasBody: true, Response: wiregen.TypeRef[subflux.KeyGenerated](),
		},
		{Name: "revokeAPIKey", Method: http.MethodDelete, Path: "/api/auth/apikeys/{id}", AuthGroup: GroupAdmin},
		{
			Name: "configYAML", Method: http.MethodGet, Path: pathConfig, AuthGroup: GroupAdmin,
			Kind: wiregen.KindRaw, Doc: "Raw config YAML (text/plain), secrets redacted.",
		},
		{
			Name: "saveConfigYAML", Method: http.MethodPut, Path: pathConfig, AuthGroup: GroupAdmin,
			Kind: wiregen.KindRaw, Doc: "Raw config YAML save (text/plain body).",
		},
		{
			Name: "saveConfigYAMLPost", Method: http.MethodPost, Path: pathConfig, AuthGroup: GroupAdmin,
			Kind: wiregen.KindRaw,
		},
		{
			Name: "configStructured", Method: http.MethodGet, Path: "/api/config/structured",
			AuthGroup: GroupAdmin, Response: wiregen.TypeRef[confighandlers.StructuredConfig](),
		},
		{
			Name: "saveConfigStructured", Method: http.MethodPut, Path: "/api/config/structured",
			AuthGroup: GroupAdmin, Request: wiregen.TypeRef[confighandlers.StructuredConfig](),
			Response: statusResp,
		},
		{Name: "resetConfig", Method: http.MethodPost, Path: "/api/config/reset", AuthGroup: GroupAdmin},
		{
			Name: "configParsed", Method: http.MethodGet, Path: "/api/config/parsed", AuthGroup: GroupAdmin,
			Response: wiregen.TypeRef[queryhandlers.ParsedConfig](),
		},

		// --- userConfigured ---
		{
			Name: "manualSearch", Method: http.MethodGet, Path: "/api/search", AuthGroup: GroupUserConfigured,
			Query: true, Response: wiregen.TypeRef[manualops.ManualSearchResponse](),
		},
		{
			Name: "searchResolve", Method: http.MethodGet, Path: "/api/search/resolve",
			AuthGroup: GroupUserConfigured, Query: true,
			Response: wiregen.TypeRef[manualops.ResolveResponse](),
			Doc:      "Resolve a user query (title/imdb/tmdb, optional type/season/episode) onto arr media items for the remote CLI search.",
		},
		{
			Name: "searchTargets", Method: http.MethodGet, Path: "/api/search/targets",
			AuthGroup: GroupUserConfigured, Query: true,
			Response: wiregen.TypeRef[subflux.SearchTargets](),
		},
		{
			Name: "listState", Method: http.MethodGet, Path: "/api/state", AuthGroup: GroupUserConfigured,
			Query: true, Response: wiregen.TypeRef[subflux.StateEntry](), RespShape: wiregen.RespArray,
		},
		{
			Name: "stateStats", Method: http.MethodGet, Path: "/api/state/stats", AuthGroup: GroupUserConfigured,
			Response: wiregen.TypeRef[subflux.Stats](),
		},
		{
			Name: "stateIDs", Method: http.MethodGet, Path: "/api/state/ids", AuthGroup: GroupUserConfigured,
			Query: true, RespShape: wiregen.RespStringArray,
		},
		{
			Name: "listBackoff", Method: http.MethodGet, Path: "/api/backoff", AuthGroup: GroupUserConfigured,
			Response: wiregen.TypeRef[subflux.BackoffEntry](), RespShape: wiregen.RespArray,
		},
		{
			Name: "backoffPrefix", Method: http.MethodGet, Path: "/api/backoff/prefix",
			AuthGroup: GroupUserConfigured, Query: true,
		},
		{
			Name: "listLocks", Method: http.MethodGet, Path: "/api/locks", AuthGroup: GroupUserConfigured,
			Response: wiregen.TypeRef[subflux.ManualLockEntry](), RespShape: wiregen.RespArray,
		},
		{
			Name: "listProviders", Method: http.MethodGet, Path: "/api/providers", AuthGroup: GroupUserConfigured,
			Response: wiregen.TypeRef[queryhandlers.ProviderInfo](), RespShape: wiregen.RespArray,
		},
		{
			Name: "providerTimeouts", Method: http.MethodGet, Path: "/api/providers/timeout",
			AuthGroup: GroupUserConfigured, Response: wiregen.TypeRef[subflux.ProvidersResponse](),
		},
		{
			Name: "mediaSeries", Method: http.MethodGet, Path: "/api/media/series",
			AuthGroup: GroupUserConfigured,
			Doc:       "Sonarr series list proxy; response typing intentionally deferred (no UI consumer).",
		},
		{
			Name: "mediaMovies", Method: http.MethodGet, Path: "/api/media/movies",
			AuthGroup: GroupUserConfigured,
		},
		{
			Name: "mediaEpisodes", Method: http.MethodGet, Path: "/api/media/series/{id}/episodes",
			AuthGroup: GroupUserConfigured, Query: true,
			Response: wiregen.TypeRef[mediahandlers.SeasonGroup](), RespShape: wiregen.RespArray,
			Doc: "Episodes grouped by season; honors ?recovery=1.",
		},
		{
			Name: "coverageSeries", Method: http.MethodGet, Path: "/api/coverage/series",
			AuthGroup: GroupUserConfigured, Query: true, Response: seriesItem, RespShape: wiregen.RespArray,
			Doc: "Whole-collection series coverage; honors ?recovery=1.",
		},
		{
			Name: "coverageMovies", Method: http.MethodGet, Path: "/api/coverage/movies",
			AuthGroup: GroupUserConfigured, Query: true, Response: movieItem, RespShape: wiregen.RespArray,
			Doc: "Whole-collection movie coverage, no inlined subtitle rows (/subs owns them); honors ?recovery=1.",
		},
		{
			Name: "coverageSeriesDetail", Method: http.MethodGet, Path: "/api/coverage/series/{tvdbId}",
			AuthGroup: GroupUserConfigured, Response: subtitleEntry, RespShape: wiregen.RespArray,
		},
		{
			Name: "coverageScanState", Method: http.MethodGet, Path: "/api/coverage/scan-state",
			AuthGroup: GroupUserConfigured,
		},
		{
			Name: "coverageSeriesSummary", Method: http.MethodGet,
			Path: "/api/coverage/series/{tvdbId}/summary", AuthGroup: GroupUserConfigured,
			Query: true, Response: seriesItem,
			Doc: "Per-item series coverage summary keyed by TVDB id; honors ?recovery=1. 404 exactly where the collection omits.",
		},
		{
			Name: "coverageMovieSummary", Method: http.MethodGet,
			Path: "/api/coverage/movies/{tmdbId}/summary", AuthGroup: GroupUserConfigured,
			Query: true, Response: movieItem,
			Doc: "Per-item movie coverage summary keyed by TMDB id, no subtitle rows; honors ?recovery=1. 404 exactly where the collection omits.",
		},
		{
			Name: "coverageMovieSubs", Method: http.MethodGet,
			Path: "/api/coverage/movies/{tmdbId}/subs", AuthGroup: GroupUserConfigured,
			Response: subtitleEntry, RespShape: wiregen.RespArray,
			Doc: "One movie's subtitle rows. Store-only: rows or an empty list, no arr read, so it does not honor ?recovery=1.",
		},
		{
			Name: "downloadSubtitle", Method: http.MethodPost, Path: "/api/search/download",
			AuthGroup: GroupUserConfigured,
			Request:   wiregen.TypeRef[manualops.DownloadRequest](),
			Response:  wiregen.TypeRef[manualops.DownloadAccepted](),
			Doc:       "Video addressed by MediaRef (media_id = arr ID + season/episode); no file path on the wire.",
		},
		{
			Name: "clearLock", Method: http.MethodPost, Path: "/api/search/clear-lock",
			AuthGroup: GroupUserConfigured, HasBody: true,
		},
		{
			Name: "scoreRelease", Method: http.MethodPost, Path: "/api/score", AuthGroup: GroupUserConfigured,
			HasBody: true, Response: wiregen.TypeRef[subflux.ScorePreview](),
		},
		{
			Name: "listFiles", Method: http.MethodGet, Path: "/api/files", AuthGroup: GroupUserConfigured,
			Query: true, Response: wiregen.TypeRef[filehandlers.FileEntry](), RespShape: wiregen.RespArray,
		},
		{
			Name: "deleteFile", Method: http.MethodDelete, Path: "/api/files", AuthGroup: GroupAdminConfigured,
			Request: wiregen.TypeRef[filehandlers.DeleteFileRequest](),
			Doc:     "File addressed by FileRef fields or a server-minted orphan_handle; no path on the wire.",
		},
		{
			Name: "bulkDeleteFiles", Method: http.MethodDelete, Path: "/api/files/bulk",
			AuthGroup: GroupAdminConfigured,
			Request:   wiregen.TypeRef[filehandlers.BulkDeleteRequest](),
		},
		{
			Name: "syncAudio", Method: http.MethodPost, Path: "/api/sync/audio", AuthGroup: GroupUserConfigured,
			Request:  wiregen.TypeRef[synchandlers.SyncAudioRequest](),
			Response: wiregen.TypeRef[synchandlers.SyncAccepted](),
			Doc:      "Dispatch one async audio-sync job: 202 {activity_id, job_id} after validation; the terminal result rides the sync:done event (matched on job_id) and the jobs read. Same-file dispatch answers the existing job's ids; a full admission lease answers 429.",
		},
		{
			Name: "syncOffset", Method: http.MethodPost, Path: "/api/sync/offset", AuthGroup: GroupUserConfigured,
			Request: wiregen.TypeRef[synchandlers.SyncOffsetRequest](),
		},
		{
			Name: "syncJobs", Method: http.MethodGet, Path: "/api/sync/jobs", AuthGroup: GroupUserConfigured,
			Query:    true,
			Response: wiregen.TypeRef[syncjobs.Job](), RespShape: wiregen.RespArray,
			Doc: "Sync job registry in total order (accepted_at DESC, job_id DESC), filterable by batch_activity_id; the reload path re-attaches through it.",
		},
		{
			Name: "previewStart", Method: http.MethodGet, Path: "/api/preview/start",
			AuthGroup: GroupUserConfigured, Query: true,
			Response: wiregen.TypeRef[previewhandlers.PreviewStartResponse](),
		},
		{
			Name: "previewSubtitle", Method: http.MethodGet, Path: "/api/preview/subtitle",
			AuthGroup: GroupUserConfigured, Kind: wiregen.KindRaw, Doc: "WebVTT text track.",
		},
		{
			Name: "previewVideo", Method: http.MethodGet, Path: "/api/preview/video",
			AuthGroup: GroupUserConfigured, Kind: wiregen.KindRaw, Doc: "Video byte stream.",
		},
		{
			Name: "previewPoster", Method: http.MethodGet, Path: "/api/preview/poster",
			AuthGroup: GroupUserConfigured, Kind: wiregen.KindRaw, Doc: "Poster image proxy.",
		},

		// --- scans (full scan is admin; per-item scans are user actions) ---
		//
		// Every scan start is async: 202 + ScanAccepted{activity_id};
		// GET /api/activity is the status monitor and completion counts ride
		// the activity/SSE machinery.
		{
			Name: "startScan", Method: http.MethodPost, Path: "/api/scan", AuthGroup: GroupAdminConfigured,
			Response: scanAccepted, Doc: "Trigger a full library scan (202 + activity_id; 409 while one runs).",
		},
		{
			Name: "scanSeries", Method: http.MethodPost, Path: "/api/scan/series/{id}",
			AuthGroup: GroupUserConfigured, Response: scanAccepted,
		},
		{
			Name: "scanSeason", Method: http.MethodPost, Path: "/api/scan/season/{id}/{season}",
			AuthGroup: GroupUserConfigured, Response: scanAccepted,
		},
		{
			Name: "scanMovie", Method: http.MethodPost, Path: "/api/scan/movie/{id}",
			AuthGroup: GroupUserConfigured, Response: scanAccepted,
		},
		{
			Name: "scanItem", Method: http.MethodPost, Path: "/api/scan/item", AuthGroup: GroupUserConfigured,
			HasBody: true, Response: scanAccepted,
		},
		{
			Name: "resetProviderTimeouts", Method: http.MethodPost, Path: "/api/providers/timeout/reset",
			AuthGroup: GroupAdminConfigured,
		},
	}
}

// RoutePatterns is reached only by tests, which is this package's whole shape:
// wirespec is build-time-only, imported by cmd/wire-codegen and by the
// consistency test that compares this table against routes.go bidirectionally.
//
// RoutePatterns maps endpoint names to their routes.go registration pattern
// when it differs from the default "METHOD path". Covers the prefix-style
// registrations (Go 1.22 ServeMux trailing-slash patterns whose handlers
// parse the suffix themselves) and the deliberately method-less routes.
func RoutePatterns() map[string]string {
	return map[string]string{ //nolint:gosec // G101: route path strings for passkey/API-key endpoints; no credential material
		"health":               "/api/health", // method-less: probes may use any method
		"metrics":              "/metrics",
		"renamePasskey":        "PUT /api/auth/passkeys/",
		"deletePasskey":        "DELETE /api/auth/passkeys/",
		"deleteUser":           "DELETE /api/auth/users/",
		"revokeAPIKey":         "DELETE /api/auth/apikeys/",
		"mediaEpisodes":        "GET /api/media/series/",
		"coverageSeriesDetail": "GET /api/coverage/series/",
		"scanSeries":           "POST /api/scan/series/",
		"scanSeason":           "POST /api/scan/season/",
		"scanMovie":            "POST /api/scan/movie/",
	}
}
