// Package wirespec is the single source of truth for subflux's HTTP wire
// contract: the registered wire types, enums, and the endpoint table that
// cmd/wire-codegen feeds into wiregen to emit the TS types, decoders, typed
// client, and the Go path constants (internal/apipaths).
//
// routes.go (internal/server) stays authoritative for PERMISSIONS — each
// endpoint's AuthGroup here is checked against the actual route registration
// by internal/server's wirespec consistency test, so the two tables cannot
// drift silently.
//
// wiregen is a build-time-only dependency: this package is imported by
// cmd/wire-codegen and by tests, never by the server runtime.
//
// The Unix-socket admin plane (POST /api/admin/bootstrap, served via
// server.AdminHandler on config.AdminSocketPath) is DELIBERATELY off this
// table: it is not part of the TCP wire contract, has no browser consumer,
// and its path constant is hand-written in internal/config so the CLI's
// socket client and main.go share it without generated code.
package wirespec

import (
	"github.com/cplieger/subflux/internal/api"
	"github.com/cplieger/subflux/internal/server/activity"
	"github.com/cplieger/subflux/internal/server/authhandlers"
	"github.com/cplieger/subflux/internal/server/confighandlers"
	"github.com/cplieger/subflux/internal/server/coverage"
	"github.com/cplieger/subflux/internal/server/coveragehandlers"
	"github.com/cplieger/subflux/internal/server/events"
	"github.com/cplieger/subflux/internal/server/filehandlers"
	"github.com/cplieger/subflux/internal/server/manualops"
	"github.com/cplieger/subflux/internal/server/mediahandlers"
	"github.com/cplieger/subflux/internal/server/previewhandlers"
	"github.com/cplieger/subflux/internal/server/queryhandlers"
	"github.com/cplieger/subflux/internal/server/scanning"
	"github.com/cplieger/subflux/internal/server/synchandlers"
	"github.com/cplieger/wiregen/v2"
)

// Auth group tags. Values match the route group names in
// internal/server/routes.go; the consistency test compares them.
const (
	GroupPublic          = "public"
	GroupUser            = "user"
	GroupAdmin           = "admin"
	GroupUserConfigured  = "userConfigured"
	GroupAdminConfigured = "adminConfigured"
)

// Registry returns the fully-populated wiregen registry: types, enums, name
// overrides, and the endpoint table.
func Registry() *wiregen.Registry {
	r := wiregen.NewRegistry(
		wiregen.WithValidatorsImport("../validators.js"),
		// The validators module is library-owned generated output (wiregen
		// v2): Generate rewrites it next to the hand-written source on every
		// run. Never hand-edit it.
		wiregen.WithValidatorsFile("../validators.ts"),
		wiregen.WithTransportImport("../api-client.js"),
		wiregen.WithHeaderComment("// CODE-GENERATED by cmd/wire-codegen, DO NOT EDIT.\n\n"),
	)

	r.Types = []wiregen.WireType{
		wiregen.TypeRef[coverage.TargetCoverage](),
		wiregen.TypeRef[coveragehandlers.SeriesItem](),
		wiregen.TypeRef[coveragehandlers.MovieItem](),
		wiregen.TypeRef[api.SubtitleEntry](),
		wiregen.TypeRef[api.Stats](),
		wiregen.TypeRef[api.ProviderStatus](),
		wiregen.TypeRef[api.ProvidersResponse](),
		wiregen.TypeRef[api.MeResponse](),
		wiregen.TypeRef[api.SchemaField](),
		wiregen.TypeRef[api.SchemaOption](),
		wiregen.TypeRef[api.SchemaSection](),
		wiregen.TypeRef[api.ProviderSchema](),
		wiregen.TypeRef[api.StateEntry](),
		wiregen.TypeRef[api.ScorePreview](),
		wiregen.TypeRef[api.SearchTarget](),
		wiregen.TypeRef[api.SearchTargets](),
		wiregen.TypeRef[api.SetupStatus](),
		wiregen.TypeRef[api.LoginSuccess](),
		wiregen.TypeRef[api.SignalData](),
		wiregen.TypeRef[api.PasskeyRegistered](),
		wiregen.TypeRef[api.KeyGenerated](),
		wiregen.TypeRef[api.BackoffEntry](),
		wiregen.TypeRef[api.ManualLockEntry](),
		wiregen.TypeRef[api.StatusResponse](),
		wiregen.TypeRef[api.AdminUserCreatedResponse](),
		wiregen.TypeRef[events.CoverageEvent](),
		wiregen.TypeRef[events.NotifyEvent](),
		wiregen.TypeRef[events.ScanEvent](),
		// The sealed SSE union (//wiregen:union on the interface): emits the
		// TS union type + the discriminator decoders. This was the founding
		// use case for wiregen's AST engine.
		wiregen.TypeRef[events.EventData](),
		wiregen.TypeRef[activity.Entry](),
		wiregen.TypeRef[activity.Alert](),
		wiregen.TypeRef[queryhandlers.ProviderInfo](),
		wiregen.TypeRef[queryhandlers.ParsedConfig](),
		wiregen.TypeRef[api.LanguageRulesJSON](),
		wiregen.TypeRef[api.AudioRuleJSON](),
		wiregen.TypeRef[api.SubtitleTargJSON](),
		wiregen.TypeRef[api.Scores](),
		wiregen.TypeRef[api.PostProcessConfig](),
		wiregen.TypeRef[authhandlers.UserInfo](),
		wiregen.TypeRef[authhandlers.APIKeyInfo](),
		wiregen.TypeRef[authhandlers.PasskeyInfo](),
		wiregen.TypeRef[authhandlers.WebAuthnLoginBeginResponse](),
		wiregen.TypeRef[authhandlers.WebAuthnRegisterBeginResponse](),
		wiregen.TypeRef[confighandlers.PathValidationResponse](),
		wiregen.TypeRef[confighandlers.StructuredConfig](),
		wiregen.TypeRef[mediahandlers.SeasonGroup](),
		wiregen.TypeRef[mediahandlers.EpisodeItem](),
		wiregen.TypeRef[manualops.ManualSearchResponse](),
		wiregen.TypeRef[manualops.SearchResult](),
		wiregen.TypeRef[manualops.DownloadAccepted](),
		wiregen.TypeRef[manualops.DownloadRequest](),
		wiregen.TypeRef[manualops.ResolveResponse](),
		wiregen.TypeRef[manualops.ResolvedItem](),
		wiregen.TypeRef[manualops.ResolveCandidate](),
		wiregen.TypeRef[manualops.ResolveSearchIDs](),
		wiregen.TypeRef[filehandlers.FileEntry](),
		wiregen.TypeRef[filehandlers.DeleteFileRequest](),
		wiregen.TypeRef[filehandlers.BulkDeleteRequest](),
		wiregen.TypeRef[synchandlers.SyncAudioRequest](),
		wiregen.TypeRef[synchandlers.SyncOffsetRequest](),
		wiregen.TypeRef[synchandlers.SyncAudioResponse](),
		wiregen.TypeRef[previewhandlers.PreviewStartResponse](),
		wiregen.TypeRef[scanning.ScanAccepted](),
	}

	// Enum values are auto-discovered from each type's const block in source.
	// Two need explicit values because they aren't discoverable that way:
	// MediaType ("series" is valid but has no const), and Role (its
	// "admin"/"user" constants live in the external github.com/cplieger/auth/v2
	// package, which wiregen does not scan for enum members).
	r.Enums = map[string]wiregen.EnumDef{
		"MediaType": {Values: []string{"movie", "episode", "series"}},
		"Role":      {Values: []string{"admin", "user"}},
		"Variant":   {}, "ScoreTier": {},
		"NotifyLevel": {}, "ActivitySource": {},
		"AlertLevel": {}, "AlertKind": {},
		// Scan scope kind + four-valued scan outcome (background scans S12);
		// both auto-discovered from the activity package's const blocks.
		"ScanKind": {}, "Outcome": {},
		// SSE event names (events.EventType consts) and the error-code
		// catalog (api.ErrorCode consts) — both auto-discovered, so a new
		// code/event lands in TS on the next generate.
		"EventType": {}, "ErrorCode": {},
	}

	// Wire DTOs are named as their TS interface, so no overrides are needed
	// except where the Go name would stutter against its package name.
	r.TSNameOverride = map[string]string{
		"TargetCoverage": "CoverageTarget", // coverage.TargetCoverage → avoid stutter
		"Entry":          "ActivityEntry",  // activity.Entry → avoid stutter
		// The *JSON suffix is a Go-side disambiguation (vs the engine's
		// runtime types); the TS side has no such collision.
		"LanguageRulesJSON": "LanguageRules",
		"AudioRuleJSON":     "AudioRule",
		"SubtitleTargJSON":  "SubtitleTarget",
	}

	// go-webauthn's begin-response envelopes marshal their options under a
	// NESTED "publicKey" key (protocol.CredentialAssertion{Response ... `json:"publicKey"`}
	// wrapped again by our WebAuthn*BeginResponse.PublicKey `json:"publicKey"`),
	// so the wire shape is publicKey.publicKey.{challenge,...}. Mapping the
	// protocol types to the DOM's WebAuthn Level 3 JSON option types makes
	// that nesting compile-time-visible in the client (it was previously
	// `unknown` + casts one level short — a masked login/registration break).
	r.TypeMappings = map[string]string{
		"github.com/go-webauthn/webauthn/protocol.CredentialAssertion": "{ publicKey: PublicKeyCredentialRequestOptionsJSON; mediation?: string }",
		"github.com/go-webauthn/webauthn/protocol.CredentialCreation":  "{ publicKey: PublicKeyCredentialCreationOptionsJSON; mediation?: string }",
	}
	// Paired decode-time hardening: assert the nested envelope shape (object
	// with a string challenge) so future go-webauthn wire drift fails loudly
	// at decode with a JSON path instead of silently breaking the ceremony.
	r.DecoderMappings = map[string]string{
		"github.com/go-webauthn/webauthn/protocol.CredentialAssertion": `((obj: Record<string, unknown>, key: string, path: string) => { const w = asObject(obj[key], path + "." + key); reqStr(asObject(w["publicKey"], path + "." + key + ".publicKey"), "challenge", path + "." + key + ".publicKey"); return w as unknown as { publicKey: PublicKeyCredentialRequestOptionsJSON; mediation?: string }; })`,
		"github.com/go-webauthn/webauthn/protocol.CredentialCreation":  `((obj: Record<string, unknown>, key: string, path: string) => { const w = asObject(obj[key], path + "." + key); reqStr(asObject(w["publicKey"], path + "." + key + ".publicKey"), "challenge", path + "." + key + ".publicKey"); return w as unknown as { publicKey: PublicKeyCredentialCreationOptionsJSON; mediation?: string }; })`,
	}

	// EventData's runtime decoders: the discriminator values are the SSE
	// event names (events.EventType consts), two of which share the
	// ScanEvent payload.
	r.DiscriminatorMap = map[string]map[string]string{
		"EventData": {
			"coverage":   "CoverageEvent",
			"notify":     "NotifyEvent",
			"scan:start": "ScanEvent",
			"scan:done":  "ScanEvent",
		},
	}

	r.Endpoints = Endpoints()
	return r
}

// Endpoints returns the endpoint table: every HTTP route the server
// registers, in routes.go registration order. AuthGroup mirrors the route
// group; Kind marks the documented non-JSON flows (raw) and the SSE stream.
func Endpoints() []wiregen.Endpoint {
	seriesItem := wiregen.TypeRef[coveragehandlers.SeriesItem]()
	movieItem := wiregen.TypeRef[coveragehandlers.MovieItem]()
	subtitleEntry := wiregen.TypeRef[api.SubtitleEntry]()
	statusResp := wiregen.TypeRef[api.StatusResponse]()
	scanAccepted := wiregen.TypeRef[scanning.ScanAccepted]()

	return []wiregen.Endpoint{
		// --- public ---
		{
			Name: "health", Method: "GET", Path: "/api/health", AuthGroup: GroupPublic,
			Response: statusResp, Doc: "Liveness probe; accepts any method server-side.",
		},
		{
			Name: "metrics", Method: "GET", Path: "/metrics", AuthGroup: GroupPublic,
			Kind: wiregen.KindRaw, Doc: "Prometheus exposition (text).",
		},
		{
			Name: "authSetupStatus", Method: "GET", Path: "/api/auth/setup", AuthGroup: GroupPublic,
			Response: wiregen.TypeRef[api.SetupStatus](),
		},
		{
			Name: "authSetupCreate", Method: "POST", Path: "/api/auth/setup", AuthGroup: GroupPublic,
			HasBody: true, Doc: "Create the initial admin account.",
		},
		{
			Name: "login", Method: "POST", Path: "/api/auth/login", AuthGroup: GroupPublic,
			HasBody: true, Response: wiregen.TypeRef[api.LoginSuccess](),
		},
		{Name: "logout", Method: "POST", Path: "/api/auth/logout", AuthGroup: GroupPublic},
		{
			Name: "oidcRedirect", Method: "GET", Path: "/api/auth/oidc", AuthGroup: GroupPublic,
			Kind: wiregen.KindRaw, Doc: "302 redirect into the OIDC provider.",
		},
		{
			Name: "oidcCallback", Method: "GET", Path: "/api/auth/oidc/callback", AuthGroup: GroupPublic,
			Kind: wiregen.KindRaw,
		},
		{
			Name: "oidcLink", Method: "POST", Path: "/api/auth/oidc/link", AuthGroup: GroupPublic,
			HasBody: true,
		},
		{
			Name: "webauthnLoginBegin", Method: "POST", Path: "/api/auth/webauthn/login/begin",
			AuthGroup: GroupPublic, Query: true,
			Response: wiregen.TypeRef[authhandlers.WebAuthnLoginBeginResponse](),
		},
		{
			Name: "webauthnLoginFinish", Method: "POST", Path: "/api/auth/webauthn/login/finish",
			AuthGroup: GroupPublic, Kind: wiregen.KindRaw,
			Doc: "WebAuthn assertion finish; hand-authored flow (documented non-JSON).",
		},

		// --- user ---
		{
			Name: "events", Method: "GET", Path: "/api/events", AuthGroup: GroupUser,
			Kind: wiregen.KindSSE, Doc: "Server-sent events stream (EventSource).",
		},
		{
			Name: "me", Method: "GET", Path: "/api/auth/me", AuthGroup: GroupUser,
			Response: wiregen.TypeRef[api.MeResponse](),
		},
		{
			Name: "changePassword", Method: "PUT", Path: "/api/auth/password", AuthGroup: GroupUser,
			HasBody: true,
		},
		{
			Name: "listPasskeys", Method: "GET", Path: "/api/auth/passkeys", AuthGroup: GroupUser,
			Response: wiregen.TypeRef[authhandlers.PasskeyInfo](), RespShape: wiregen.RespArray,
		},
		{
			Name: "webauthnSignalData", Method: "GET", Path: "/api/auth/webauthn/signal-data",
			AuthGroup: GroupUser, Response: wiregen.TypeRef[api.SignalData](),
		},
		{
			Name: "webauthnRegisterBegin", Method: "POST", Path: "/api/auth/webauthn/register/begin",
			AuthGroup: GroupUser, HasBody: true,
			Response: wiregen.TypeRef[authhandlers.WebAuthnRegisterBeginResponse](),
		},
		{
			Name: "webauthnRegisterFinish", Method: "POST", Path: "/api/auth/webauthn/register/finish",
			AuthGroup: GroupUser, Kind: wiregen.KindRaw,
			Doc: "WebAuthn attestation finish; needs the X-WebAuthn-Session header, which the generated client has no seam for.",
		},
		{
			Name: "renamePasskey", Method: "PUT", Path: "/api/auth/passkeys/{id}", AuthGroup: GroupUser,
			HasBody: true,
		},
		{
			Name: "configSchema", Method: "GET", Path: "/api/config/schema", AuthGroup: GroupUser,
			Response: wiregen.TypeRef[api.SchemaSection](), RespShape: wiregen.RespArray,
		},
		{
			Name: "validateConfigPath", Method: "POST", Path: "/api/config/validate-path",
			AuthGroup: GroupAdmin, HasBody: true,
			Doc:      "Config-time directory probe; the one deliberate path-accepting endpoint.",
			Response: wiregen.TypeRef[confighandlers.PathValidationResponse](),
		},
		{
			Name: "listAlerts", Method: "GET", Path: "/api/alerts", AuthGroup: GroupUser,
			Response: wiregen.TypeRef[activity.Alert](), RespShape: wiregen.RespArray,
		},
		{
			Name: "dismissAlert", Method: "DELETE", Path: "/api/alerts", AuthGroup: GroupUser,
			Query: true,
		},
		{
			Name: "listActivity", Method: "GET", Path: "/api/activity", AuthGroup: GroupUser,
			Response: wiregen.TypeRef[activity.Entry](), RespShape: wiregen.RespArray,
		},
		{
			Name: "dismissActivity", Method: "DELETE", Path: "/api/activity", AuthGroup: GroupUser,
			Query: true,
			Doc:   "Dismiss a completed entry or cancel a QUEUED one; never stops running work (see cancelActivity).",
		},
		{
			Name: "cancelActivity", Method: "POST", Path: "/api/activity/{id}/cancel",
			AuthGroup: GroupUserConfigured,
			Doc:       "Gracefully stop a running background scan after the current item. Object-level role: per-item scans any user, full scans admin. 204 stopped/already stopping, 404 unknown, 409 not cancellable.",
		},
		{
			Name: "deletePasskey", Method: "DELETE", Path: "/api/auth/passkeys/{id}",
			AuthGroup: GroupUser,
		},
		{Name: "oidcUnlink", Method: "DELETE", Path: "/api/auth/oidc/link", AuthGroup: GroupUser},

		// --- admin ---
		{
			Name: "listUsers", Method: "GET", Path: "/api/auth/users", AuthGroup: GroupAdmin,
			Response: wiregen.TypeRef[authhandlers.UserInfo](), RespShape: wiregen.RespArray,
		},
		{
			Name: "createUser", Method: "POST", Path: "/api/auth/users", AuthGroup: GroupAdmin,
			HasBody: true, Response: wiregen.TypeRef[api.AdminUserCreatedResponse](),
		},
		{Name: "deleteUser", Method: "DELETE", Path: "/api/auth/users/{id}", AuthGroup: GroupAdmin},
		{
			Name: "listAPIKeys", Method: "GET", Path: "/api/auth/apikeys", AuthGroup: GroupAdmin,
			Response: wiregen.TypeRef[authhandlers.APIKeyInfo](), RespShape: wiregen.RespArray,
		},
		{
			Name: "generateAPIKey", Method: "POST", Path: "/api/auth/apikeys", AuthGroup: GroupAdmin,
			HasBody: true, Response: wiregen.TypeRef[api.KeyGenerated](),
		},
		{Name: "revokeAPIKey", Method: "DELETE", Path: "/api/auth/apikeys/{id}", AuthGroup: GroupAdmin},
		{
			Name: "configYAML", Method: "GET", Path: "/api/config", AuthGroup: GroupAdmin,
			Kind: wiregen.KindRaw, Doc: "Raw config YAML (text/plain), secrets redacted.",
		},
		{
			Name: "saveConfigYAML", Method: "PUT", Path: "/api/config", AuthGroup: GroupAdmin,
			Kind: wiregen.KindRaw, Doc: "Raw config YAML save (text/plain body).",
		},
		{
			Name: "saveConfigYAMLPost", Method: "POST", Path: "/api/config", AuthGroup: GroupAdmin,
			Kind: wiregen.KindRaw,
		},
		{
			Name: "configStructured", Method: "GET", Path: "/api/config/structured",
			AuthGroup: GroupAdmin, Response: wiregen.TypeRef[confighandlers.StructuredConfig](),
		},
		{
			Name: "saveConfigStructured", Method: "PUT", Path: "/api/config/structured",
			AuthGroup: GroupAdmin, Request: wiregen.TypeRef[confighandlers.StructuredConfig](),
			Response: statusResp,
		},
		{Name: "resetConfig", Method: "POST", Path: "/api/config/reset", AuthGroup: GroupAdmin},
		{
			Name: "configParsed", Method: "GET", Path: "/api/config/parsed", AuthGroup: GroupAdmin,
			Response: wiregen.TypeRef[queryhandlers.ParsedConfig](),
		},

		// --- userConfigured ---
		{
			Name: "manualSearch", Method: "GET", Path: "/api/search", AuthGroup: GroupUserConfigured,
			Query: true, Response: wiregen.TypeRef[manualops.ManualSearchResponse](),
		},
		{
			Name: "searchResolve", Method: "GET", Path: "/api/search/resolve",
			AuthGroup: GroupUserConfigured, Query: true,
			Response: wiregen.TypeRef[manualops.ResolveResponse](),
			Doc:      "Resolve a user query (title/imdb/tmdb, optional type/season/episode) onto arr media items for the remote CLI search.",
		},
		{
			Name: "searchTargets", Method: "GET", Path: "/api/search/targets",
			AuthGroup: GroupUserConfigured, Query: true,
			Response: wiregen.TypeRef[api.SearchTargets](),
		},
		{
			Name: "listState", Method: "GET", Path: "/api/state", AuthGroup: GroupUserConfigured,
			Query: true, Response: wiregen.TypeRef[api.StateEntry](), RespShape: wiregen.RespArray,
		},
		{
			Name: "stateStats", Method: "GET", Path: "/api/state/stats", AuthGroup: GroupUserConfigured,
			Response: wiregen.TypeRef[api.Stats](),
		},
		{
			Name: "stateIDs", Method: "GET", Path: "/api/state/ids", AuthGroup: GroupUserConfigured,
			Query: true, RespShape: wiregen.RespStringArray,
		},
		{
			Name: "listBackoff", Method: "GET", Path: "/api/backoff", AuthGroup: GroupUserConfigured,
			Response: wiregen.TypeRef[api.BackoffEntry](), RespShape: wiregen.RespArray,
		},
		{
			Name: "backoffPrefix", Method: "GET", Path: "/api/backoff/prefix",
			AuthGroup: GroupUserConfigured, Query: true,
		},
		{
			Name: "listLocks", Method: "GET", Path: "/api/locks", AuthGroup: GroupUserConfigured,
			Response: wiregen.TypeRef[api.ManualLockEntry](), RespShape: wiregen.RespArray,
		},
		{
			Name: "listProviders", Method: "GET", Path: "/api/providers", AuthGroup: GroupUserConfigured,
			Response: wiregen.TypeRef[queryhandlers.ProviderInfo](), RespShape: wiregen.RespArray,
		},
		{
			Name: "providerTimeouts", Method: "GET", Path: "/api/providers/timeout",
			AuthGroup: GroupUserConfigured, Response: wiregen.TypeRef[api.ProvidersResponse](),
		},
		{
			Name: "mediaSeries", Method: "GET", Path: "/api/media/series",
			AuthGroup: GroupUserConfigured,
			Doc:       "Sonarr series list proxy; response typing intentionally deferred (no UI consumer).",
		},
		{
			Name: "mediaMovies", Method: "GET", Path: "/api/media/movies",
			AuthGroup: GroupUserConfigured,
		},
		{
			Name: "mediaEpisodes", Method: "GET", Path: "/api/media/series/{id}/episodes",
			AuthGroup: GroupUserConfigured,
			Response:  wiregen.TypeRef[mediahandlers.SeasonGroup](), RespShape: wiregen.RespArray,
		},
		{
			Name: "coverageSeries", Method: "GET", Path: "/api/coverage/series",
			AuthGroup: GroupUserConfigured, Response: seriesItem, RespShape: wiregen.RespArray,
		},
		{
			Name: "coverageMovies", Method: "GET", Path: "/api/coverage/movies",
			AuthGroup: GroupUserConfigured, Response: movieItem, RespShape: wiregen.RespArray,
		},
		{
			Name: "coverageSeriesDetail", Method: "GET", Path: "/api/coverage/series/{tvdbId}",
			AuthGroup: GroupUserConfigured, Response: subtitleEntry, RespShape: wiregen.RespArray,
		},
		{
			Name: "coverageScanState", Method: "GET", Path: "/api/coverage/scan-state",
			AuthGroup: GroupUserConfigured,
		},
		{
			Name: "downloadSubtitle", Method: "POST", Path: "/api/search/download",
			AuthGroup: GroupUserConfigured,
			Request:   wiregen.TypeRef[manualops.DownloadRequest](),
			Response:  wiregen.TypeRef[manualops.DownloadAccepted](),
			Doc:       "Video addressed by MediaRef (media_id = arr ID + season/episode); no file path on the wire.",
		},
		{
			Name: "clearLock", Method: "POST", Path: "/api/search/clear-lock",
			AuthGroup: GroupUserConfigured, HasBody: true,
		},
		{
			Name: "scoreRelease", Method: "POST", Path: "/api/score", AuthGroup: GroupUserConfigured,
			HasBody: true, Response: wiregen.TypeRef[api.ScorePreview](),
		},
		{
			Name: "listFiles", Method: "GET", Path: "/api/files", AuthGroup: GroupUserConfigured,
			Query: true, Response: wiregen.TypeRef[filehandlers.FileEntry](), RespShape: wiregen.RespArray,
		},
		{
			Name: "deleteFile", Method: "DELETE", Path: "/api/files", AuthGroup: GroupAdminConfigured,
			Request: wiregen.TypeRef[filehandlers.DeleteFileRequest](),
			Doc:     "File addressed by FileRef fields or a server-minted orphan_handle; no path on the wire.",
		},
		{
			Name: "bulkDeleteFiles", Method: "DELETE", Path: "/api/files/bulk",
			AuthGroup: GroupAdminConfigured,
			Request:   wiregen.TypeRef[filehandlers.BulkDeleteRequest](),
		},
		{
			Name: "syncAudio", Method: "POST", Path: "/api/sync/audio", AuthGroup: GroupUserConfigured,
			Request:  wiregen.TypeRef[synchandlers.SyncAudioRequest](),
			Response: wiregen.TypeRef[synchandlers.SyncAudioResponse](),
		},
		{
			Name: "syncOffset", Method: "POST", Path: "/api/sync/offset", AuthGroup: GroupUserConfigured,
			Request: wiregen.TypeRef[synchandlers.SyncOffsetRequest](),
		},
		{
			Name: "previewStart", Method: "GET", Path: "/api/preview/start",
			AuthGroup: GroupUserConfigured, Query: true,
			Response: wiregen.TypeRef[previewhandlers.PreviewStartResponse](),
		},
		{
			Name: "previewSubtitle", Method: "GET", Path: "/api/preview/subtitle",
			AuthGroup: GroupUserConfigured, Kind: wiregen.KindRaw, Doc: "WebVTT text track.",
		},
		{
			Name: "previewVideo", Method: "GET", Path: "/api/preview/video",
			AuthGroup: GroupUserConfigured, Kind: wiregen.KindRaw, Doc: "Video byte stream.",
		},
		{
			Name: "previewPoster", Method: "GET", Path: "/api/preview/poster",
			AuthGroup: GroupUserConfigured, Kind: wiregen.KindRaw, Doc: "Poster image proxy.",
		},

		// --- scans (full scan is admin; per-item scans are user actions) ---
		//
		// Every scan start is async: 202 + ScanAccepted{activity_id};
		// GET /api/activity is the status monitor and completion counts ride
		// the activity/SSE machinery.
		{
			Name: "startScan", Method: "POST", Path: "/api/scan", AuthGroup: GroupAdminConfigured,
			Response: scanAccepted, Doc: "Trigger a full library scan (202 + activity_id; 409 while one runs).",
		},
		{
			Name: "scanSeries", Method: "POST", Path: "/api/scan/series/{id}",
			AuthGroup: GroupUserConfigured, Response: scanAccepted,
		},
		{
			Name: "scanSeason", Method: "POST", Path: "/api/scan/season/{id}/{season}",
			AuthGroup: GroupUserConfigured, Response: scanAccepted,
		},
		{
			Name: "scanMovie", Method: "POST", Path: "/api/scan/movie/{id}",
			AuthGroup: GroupUserConfigured, Response: scanAccepted,
		},
		{
			Name: "scanItem", Method: "POST", Path: "/api/scan/item", AuthGroup: GroupUserConfigured,
			HasBody: true, Response: scanAccepted,
		},
		{
			Name: "resetProviderTimeouts", Method: "POST", Path: "/api/providers/timeout/reset",
			AuthGroup: GroupAdminConfigured,
		},
	}
}

// RoutePatterns maps endpoint names to their routes.go registration pattern
// when it differs from the default "METHOD path". Covers the prefix-style
// registrations (Go 1.22 ServeMux trailing-slash patterns whose handlers
// parse the suffix themselves) and the deliberately method-less routes.
func RoutePatterns() map[string]string {
	return map[string]string{
		"health":               "/api/health", // method-less: probes may use any method
		"metrics":              "/metrics",
		"renamePasskey":        "PUT /api/auth/passkeys/",
		"deletePasskey":        "DELETE /api/auth/passkeys/",
		"deleteUser":           "DELETE /api/auth/users/",
		"revokeAPIKey":         "DELETE /api/auth/apikeys/",
		"mediaEpisodes":        "GET /api/media/series/",
		"coverageSeriesDetail": "GET /api/coverage/series/",
		"scanSeries":           "POST /api/scan/series/",
		"scanSeason":           "POST /api/scan/season/",
		"scanMovie":            "POST /api/scan/movie/",
	}
}
