// CODE-GENERATED by cmd/wire-codegen, DO NOT EDIT.

import { clientRequest, clientRequestOK, clientRequestRaw } from "../api-client.js";
import type { ApiResult } from "../api-client.js";
import { decodeArray } from "../validators.js";
import { decodeAPIKeyInfo, decodeActivityEntry, decodeAdminUserCreatedResponse, decodeAlert, decodeBackoffEntry, decodeConnTestResponse, decodeDownloadAccepted, decodeFileEntry, decodeJob, decodeKeyGenerated, decodeLoginSuccess, decodeManualLockEntry, decodeManualSearchResponse, decodeMeResponse, decodeMovieItem, decodeParsedConfig, decodePasskeyInfo, decodePathValidationResponse, decodePreviewStartResponse, decodeProviderInfo, decodeProvidersResponse, decodeResolveResponse, decodeScanAccepted, decodeSchemaSection, decodeScorePreview, decodeSearchTargets, decodeSeasonGroup, decodeSeasonSyncAccepted, decodeSeriesItem, decodeSetupStatus, decodeSignals, decodeStateEntry, decodeStats, decodeStatusResponse, decodeStructuredConfig, decodeSubtitleEntry, decodeSyncAccepted, decodeUserInfo, decodeWebAuthnLoginBeginResponse, decodeWebAuthnRegisterBeginResponse } from "./decoders.gen.js";
import type { APIKeyInfo, ActivityEntry, AdminUserCreatedResponse, Alert, BackoffEntry, BulkDeleteRequest, ConnTestResponse, DeleteFileRequest, DownloadAccepted, DownloadRequest, FileEntry, Job, KeyGenerated, LoginSuccess, ManualLockEntry, ManualSearchResponse, MeResponse, MovieItem, ParsedConfig, PasskeyInfo, PathValidationResponse, PreviewStartResponse, ProviderInfo, ProvidersResponse, ResolveResponse, ScanAccepted, SchemaSection, ScorePreview, SearchTargets, SeasonGroup, SeasonSyncAccepted, SeriesItem, SetupStatus, Signals, StateEntry, Stats, StatusResponse, StructuredConfig, SubtitleEntry, SyncAccepted, SyncAudioRequest, SyncOffsetRequest, SyncSeasonRequest, UserInfo, WebAuthnLoginBeginResponse, WebAuthnRegisterBeginResponse } from "./types.gen.js";

/** Options accepted by every generated client function. */
export interface ClientOpts {
  signal?: AbortSignal;
}

/** Query values: undefined entries are skipped at serialization. */
export type QueryValue = string | number | boolean | undefined;

function qs(query?: Record<string, QueryValue>): string {
  if (!query) {
    return "";
  }
  const p = new URLSearchParams();
  for (const [k, v] of Object.entries(query)) {
    if (v !== undefined) {
      p.set(k, String(v));
    }
  }
  const s = p.toString();
  return s === "" ? "" : `?${s}`;
}

// One PATH_ constant per endpoint (placeholders kept verbatim). The
// non-JSON flows (kind: raw/sse) have no generated function and are
// consumed exclusively through these.
export const PATH_HEALTH = "/api/health";
export const PATH_METRICS = "/metrics";
export const PATH_AUTH_SETUP_STATUS = "/api/auth/setup";
export const PATH_AUTH_SETUP_CREATE = "/api/auth/setup";
export const PATH_LOGIN = "/api/auth/login";
export const PATH_LOGOUT = "/api/auth/logout";
export const PATH_OIDC_REDIRECT = "/api/auth/oidc";
export const PATH_OIDC_CALLBACK = "/api/auth/oidc/callback";
export const PATH_OIDC_LINK = "/api/auth/oidc/link";
export const PATH_WEBAUTHN_LOGIN_BEGIN = "/api/auth/webauthn/login/begin";
export const PATH_WEBAUTHN_LOGIN_FINISH = "/api/auth/webauthn/login/finish";
export const PATH_EVENTS = "/api/events";
export const PATH_ME = "/api/auth/me";
export const PATH_CHANGE_PASSWORD = "/api/auth/password";
export const PATH_UPDATE_PROFILE = "/api/auth/profile";
export const PATH_LIST_PASSKEYS = "/api/auth/passkeys";
export const PATH_WEBAUTHN_SIGNAL_DATA = "/api/auth/webauthn/signal-data";
export const PATH_WEBAUTHN_REGISTER_BEGIN = "/api/auth/webauthn/register/begin";
export const PATH_WEBAUTHN_REGISTER_FINISH = "/api/auth/webauthn/register/finish";
export const PATH_RENAME_PASSKEY = "/api/auth/passkeys/{id}";
export const PATH_CONFIG_SCHEMA = "/api/config/schema";
export const PATH_VALIDATE_CONFIG_PATH = "/api/config/validate-path";
export const PATH_TEST_CONNECTION = "/api/config/test-connection";
export const PATH_LIST_ALERTS = "/api/alerts";
export const PATH_DISMISS_ALERT = "/api/alerts";
export const PATH_LIST_ACTIVITY = "/api/activity";
export const PATH_DISMISS_ACTIVITY = "/api/activity";
export const PATH_CANCEL_ACTIVITY = "/api/activity/{id}/cancel";
export const PATH_DELETE_PASSKEY = "/api/auth/passkeys/{id}";
export const PATH_OIDC_UNLINK = "/api/auth/oidc/link";
export const PATH_LIST_USERS = "/api/auth/users";
export const PATH_CREATE_USER = "/api/auth/users";
export const PATH_DELETE_USER = "/api/auth/users/{id}";
export const PATH_LIST_API_KEYS = "/api/auth/apikeys";
export const PATH_GENERATE_API_KEY = "/api/auth/apikeys";
export const PATH_REVOKE_API_KEY = "/api/auth/apikeys/{id}";
export const PATH_CONFIG_YAML = "/api/config";
export const PATH_SAVE_CONFIG_YAML = "/api/config";
export const PATH_SAVE_CONFIG_YAML_POST = "/api/config";
export const PATH_CONFIG_STRUCTURED = "/api/config/structured";
export const PATH_SAVE_CONFIG_STRUCTURED = "/api/config/structured";
export const PATH_RESET_CONFIG = "/api/config/reset";
export const PATH_CONFIG_PARSED = "/api/config/parsed";
export const PATH_MANUAL_SEARCH = "/api/search";
export const PATH_SEARCH_RESOLVE = "/api/search/resolve";
export const PATH_SEARCH_TARGETS = "/api/search/targets";
export const PATH_LIST_STATE = "/api/state";
export const PATH_STATE_STATS = "/api/state/stats";
export const PATH_STATE_I_DS = "/api/state/ids";
export const PATH_LIST_BACKOFF = "/api/backoff";
export const PATH_BACKOFF_PREFIX = "/api/backoff/prefix";
export const PATH_LIST_LOCKS = "/api/locks";
export const PATH_LIST_PROVIDERS = "/api/providers";
export const PATH_PROVIDER_TIMEOUTS = "/api/providers/timeout";
export const PATH_MEDIA_SERIES = "/api/media/series";
export const PATH_MEDIA_MOVIES = "/api/media/movies";
export const PATH_MEDIA_EPISODES = "/api/media/series/{id}/episodes";
export const PATH_COVERAGE_SERIES = "/api/coverage/series";
export const PATH_COVERAGE_MOVIES = "/api/coverage/movies";
export const PATH_COVERAGE_SERIES_DETAIL = "/api/coverage/series/{tvdbId}";
export const PATH_COVERAGE_SCAN_STATE = "/api/coverage/scan-state";
export const PATH_COVERAGE_SERIES_SUMMARY = "/api/coverage/series/{tvdbId}/summary";
export const PATH_COVERAGE_MOVIE_SUMMARY = "/api/coverage/movies/{tmdbId}/summary";
export const PATH_COVERAGE_MOVIE_SUBS = "/api/coverage/movies/{tmdbId}/subs";
export const PATH_DOWNLOAD_SUBTITLE = "/api/search/download";
export const PATH_CLEAR_LOCK = "/api/search/clear-lock";
export const PATH_SCORE_RELEASE = "/api/score";
export const PATH_LIST_FILES = "/api/files";
export const PATH_DELETE_FILE = "/api/files";
export const PATH_BULK_DELETE_FILES = "/api/files/bulk";
export const PATH_SYNC_AUDIO = "/api/sync/audio";
export const PATH_SYNC_SEASON = "/api/sync/season";
export const PATH_SYNC_OFFSET = "/api/sync/offset";
export const PATH_SYNC_JOBS = "/api/sync/jobs";
export const PATH_PREVIEW_START = "/api/preview/start";
export const PATH_PREVIEW_SUBTITLE = "/api/preview/subtitle";
export const PATH_PREVIEW_VIDEO = "/api/preview/video";
export const PATH_PREVIEW_POSTER = "/api/preview/poster";
export const PATH_START_SCAN = "/api/scan";
export const PATH_SCAN_SERIES = "/api/scan/series/{id}";
export const PATH_SCAN_SEASON = "/api/scan/season/{id}/{season}";
export const PATH_SCAN_MOVIE = "/api/scan/movie/{id}";
export const PATH_SCAN_ITEM = "/api/scan/item";
export const PATH_RESET_PROVIDER_TIMEOUTS = "/api/providers/timeout/reset";

/** Liveness probe; accepts any method server-side. */
export function health(opts?: ClientOpts): Promise<StatusResponse | null> {
  return clientRequest("GET", "/api/health", undefined, decodeStatusResponse, opts?.signal);
}

export function healthRaw(opts?: ClientOpts): Promise<ApiResult<StatusResponse>> {
  return clientRequestRaw("GET", "/api/health", undefined, decodeStatusResponse, opts?.signal);
}

export function authSetupStatus(opts?: ClientOpts): Promise<SetupStatus | null> {
  return clientRequest("GET", "/api/auth/setup", undefined, decodeSetupStatus, opts?.signal);
}

export function authSetupStatusRaw(opts?: ClientOpts): Promise<ApiResult<SetupStatus>> {
  return clientRequestRaw("GET", "/api/auth/setup", undefined, decodeSetupStatus, opts?.signal);
}

/** Create the initial admin account. */
export function authSetupCreate(body: unknown, opts?: ClientOpts): Promise<boolean> {
  return clientRequestOK("POST", "/api/auth/setup", body, opts?.signal);
}

export function authSetupCreateRaw(body: unknown, opts?: ClientOpts): Promise<ApiResult<unknown>> {
  return clientRequestRaw("POST", "/api/auth/setup", body, undefined, opts?.signal);
}

export function login(body: unknown, opts?: ClientOpts): Promise<LoginSuccess | null> {
  return clientRequest("POST", "/api/auth/login", body, decodeLoginSuccess, opts?.signal);
}

export function loginRaw(body: unknown, opts?: ClientOpts): Promise<ApiResult<LoginSuccess>> {
  return clientRequestRaw("POST", "/api/auth/login", body, decodeLoginSuccess, opts?.signal);
}

export function logout(opts?: ClientOpts): Promise<boolean> {
  return clientRequestOK("POST", "/api/auth/logout", undefined, opts?.signal);
}

export function logoutRaw(opts?: ClientOpts): Promise<ApiResult<unknown>> {
  return clientRequestRaw("POST", "/api/auth/logout", undefined, undefined, opts?.signal);
}

export function oidcLink(body: unknown, opts?: ClientOpts): Promise<boolean> {
  return clientRequestOK("POST", "/api/auth/oidc/link", body, opts?.signal);
}

export function oidcLinkRaw(body: unknown, opts?: ClientOpts): Promise<ApiResult<unknown>> {
  return clientRequestRaw("POST", "/api/auth/oidc/link", body, undefined, opts?.signal);
}

export function webauthnLoginBegin(query?: Record<string, QueryValue>, opts?: ClientOpts): Promise<WebAuthnLoginBeginResponse | null> {
  return clientRequest("POST", "/api/auth/webauthn/login/begin" + qs(query), undefined, decodeWebAuthnLoginBeginResponse, opts?.signal);
}

export function webauthnLoginBeginRaw(query?: Record<string, QueryValue>, opts?: ClientOpts): Promise<ApiResult<WebAuthnLoginBeginResponse>> {
  return clientRequestRaw("POST", "/api/auth/webauthn/login/begin" + qs(query), undefined, decodeWebAuthnLoginBeginResponse, opts?.signal);
}

export function me(opts?: ClientOpts): Promise<MeResponse | null> {
  return clientRequest("GET", "/api/auth/me", undefined, decodeMeResponse, opts?.signal);
}

export function meRaw(opts?: ClientOpts): Promise<ApiResult<MeResponse>> {
  return clientRequestRaw("GET", "/api/auth/me", undefined, decodeMeResponse, opts?.signal);
}

export function changePassword(body: unknown, opts?: ClientOpts): Promise<boolean> {
  return clientRequestOK("PUT", "/api/auth/password", body, opts?.signal);
}

export function changePasswordRaw(body: unknown, opts?: ClientOpts): Promise<ApiResult<unknown>> {
  return clientRequestRaw("PUT", "/api/auth/password", body, undefined, opts?.signal);
}

export function updateProfile(body: unknown, opts?: ClientOpts): Promise<boolean> {
  return clientRequestOK("PUT", "/api/auth/profile", body, opts?.signal);
}

export function updateProfileRaw(body: unknown, opts?: ClientOpts): Promise<ApiResult<unknown>> {
  return clientRequestRaw("PUT", "/api/auth/profile", body, undefined, opts?.signal);
}

export function listPasskeys(opts?: ClientOpts): Promise<PasskeyInfo[] | null> {
  return clientRequest("GET", "/api/auth/passkeys", undefined, (v) => decodeArray(v, decodePasskeyInfo, "$"), opts?.signal);
}

export function listPasskeysRaw(opts?: ClientOpts): Promise<ApiResult<PasskeyInfo[]>> {
  return clientRequestRaw("GET", "/api/auth/passkeys", undefined, (v) => decodeArray(v, decodePasskeyInfo, "$"), opts?.signal);
}

export function webauthnSignalData(opts?: ClientOpts): Promise<Signals | null> {
  return clientRequest("GET", "/api/auth/webauthn/signal-data", undefined, decodeSignals, opts?.signal);
}

export function webauthnSignalDataRaw(opts?: ClientOpts): Promise<ApiResult<Signals>> {
  return clientRequestRaw("GET", "/api/auth/webauthn/signal-data", undefined, decodeSignals, opts?.signal);
}

export function webauthnRegisterBegin(body: unknown, opts?: ClientOpts): Promise<WebAuthnRegisterBeginResponse | null> {
  return clientRequest("POST", "/api/auth/webauthn/register/begin", body, decodeWebAuthnRegisterBeginResponse, opts?.signal);
}

export function webauthnRegisterBeginRaw(body: unknown, opts?: ClientOpts): Promise<ApiResult<WebAuthnRegisterBeginResponse>> {
  return clientRequestRaw("POST", "/api/auth/webauthn/register/begin", body, decodeWebAuthnRegisterBeginResponse, opts?.signal);
}

export function renamePasskey(id: string | number, body: unknown, opts?: ClientOpts): Promise<boolean> {
  return clientRequestOK("PUT", `/api/auth/passkeys/${encodeURIComponent(String(id))}`, body, opts?.signal);
}

export function renamePasskeyRaw(id: string | number, body: unknown, opts?: ClientOpts): Promise<ApiResult<unknown>> {
  return clientRequestRaw("PUT", `/api/auth/passkeys/${encodeURIComponent(String(id))}`, body, undefined, opts?.signal);
}

export function configSchema(opts?: ClientOpts): Promise<SchemaSection[] | null> {
  return clientRequest("GET", "/api/config/schema", undefined, (v) => decodeArray(v, decodeSchemaSection, "$"), opts?.signal);
}

export function configSchemaRaw(opts?: ClientOpts): Promise<ApiResult<SchemaSection[]>> {
  return clientRequestRaw("GET", "/api/config/schema", undefined, (v) => decodeArray(v, decodeSchemaSection, "$"), opts?.signal);
}

/** Config-time directory probe; the one deliberate path-accepting endpoint. */
export function validateConfigPath(body: unknown, opts?: ClientOpts): Promise<PathValidationResponse | null> {
  return clientRequest("POST", "/api/config/validate-path", body, decodePathValidationResponse, opts?.signal);
}

export function validateConfigPathRaw(body: unknown, opts?: ClientOpts): Promise<ApiResult<PathValidationResponse>> {
  return clientRequestRaw("POST", "/api/config/validate-path", body, decodePathValidationResponse, opts?.signal);
}

/** Live Sonarr/Radarr reachability + API-key check; a failed test is 200 with valid=false. */
export function testConnection(body: unknown, opts?: ClientOpts): Promise<ConnTestResponse | null> {
  return clientRequest("POST", "/api/config/test-connection", body, decodeConnTestResponse, opts?.signal);
}

export function testConnectionRaw(body: unknown, opts?: ClientOpts): Promise<ApiResult<ConnTestResponse>> {
  return clientRequestRaw("POST", "/api/config/test-connection", body, decodeConnTestResponse, opts?.signal);
}

export function listAlerts(opts?: ClientOpts): Promise<Alert[] | null> {
  return clientRequest("GET", "/api/alerts", undefined, (v) => decodeArray(v, decodeAlert, "$"), opts?.signal);
}

export function listAlertsRaw(opts?: ClientOpts): Promise<ApiResult<Alert[]>> {
  return clientRequestRaw("GET", "/api/alerts", undefined, (v) => decodeArray(v, decodeAlert, "$"), opts?.signal);
}

export function dismissAlert(query?: Record<string, QueryValue>, opts?: ClientOpts): Promise<boolean> {
  return clientRequestOK("DELETE", "/api/alerts" + qs(query), undefined, opts?.signal);
}

export function dismissAlertRaw(query?: Record<string, QueryValue>, opts?: ClientOpts): Promise<ApiResult<unknown>> {
  return clientRequestRaw("DELETE", "/api/alerts" + qs(query), undefined, undefined, opts?.signal);
}

export function listActivity(opts?: ClientOpts): Promise<ActivityEntry[] | null> {
  return clientRequest("GET", "/api/activity", undefined, (v) => decodeArray(v, decodeActivityEntry, "$"), opts?.signal);
}

export function listActivityRaw(opts?: ClientOpts): Promise<ApiResult<ActivityEntry[]>> {
  return clientRequestRaw("GET", "/api/activity", undefined, (v) => decodeArray(v, decodeActivityEntry, "$"), opts?.signal);
}

/** Dismiss a completed entry or cancel a QUEUED one; never stops running work (see cancelActivity). */
export function dismissActivity(query?: Record<string, QueryValue>, opts?: ClientOpts): Promise<boolean> {
  return clientRequestOK("DELETE", "/api/activity" + qs(query), undefined, opts?.signal);
}

export function dismissActivityRaw(query?: Record<string, QueryValue>, opts?: ClientOpts): Promise<ApiResult<unknown>> {
  return clientRequestRaw("DELETE", "/api/activity" + qs(query), undefined, undefined, opts?.signal);
}

/** Gracefully stop a running background scan after the current item. Object-level role: per-item scans any user, full scans admin. 204 stopped/already stopping, 404 unknown, 409 not cancellable. */
export function cancelActivity(id: string | number, opts?: ClientOpts): Promise<boolean> {
  return clientRequestOK("POST", `/api/activity/${encodeURIComponent(String(id))}/cancel`, undefined, opts?.signal);
}

export function cancelActivityRaw(id: string | number, opts?: ClientOpts): Promise<ApiResult<unknown>> {
  return clientRequestRaw("POST", `/api/activity/${encodeURIComponent(String(id))}/cancel`, undefined, undefined, opts?.signal);
}

export function deletePasskey(id: string | number, opts?: ClientOpts): Promise<boolean> {
  return clientRequestOK("DELETE", `/api/auth/passkeys/${encodeURIComponent(String(id))}`, undefined, opts?.signal);
}

export function deletePasskeyRaw(id: string | number, opts?: ClientOpts): Promise<ApiResult<unknown>> {
  return clientRequestRaw("DELETE", `/api/auth/passkeys/${encodeURIComponent(String(id))}`, undefined, undefined, opts?.signal);
}

export function oidcUnlink(opts?: ClientOpts): Promise<boolean> {
  return clientRequestOK("DELETE", "/api/auth/oidc/link", undefined, opts?.signal);
}

export function oidcUnlinkRaw(opts?: ClientOpts): Promise<ApiResult<unknown>> {
  return clientRequestRaw("DELETE", "/api/auth/oidc/link", undefined, undefined, opts?.signal);
}

export function listUsers(opts?: ClientOpts): Promise<UserInfo[] | null> {
  return clientRequest("GET", "/api/auth/users", undefined, (v) => decodeArray(v, decodeUserInfo, "$"), opts?.signal);
}

export function listUsersRaw(opts?: ClientOpts): Promise<ApiResult<UserInfo[]>> {
  return clientRequestRaw("GET", "/api/auth/users", undefined, (v) => decodeArray(v, decodeUserInfo, "$"), opts?.signal);
}

export function createUser(body: unknown, opts?: ClientOpts): Promise<AdminUserCreatedResponse | null> {
  return clientRequest("POST", "/api/auth/users", body, decodeAdminUserCreatedResponse, opts?.signal);
}

export function createUserRaw(body: unknown, opts?: ClientOpts): Promise<ApiResult<AdminUserCreatedResponse>> {
  return clientRequestRaw("POST", "/api/auth/users", body, decodeAdminUserCreatedResponse, opts?.signal);
}

export function deleteUser(id: string | number, opts?: ClientOpts): Promise<boolean> {
  return clientRequestOK("DELETE", `/api/auth/users/${encodeURIComponent(String(id))}`, undefined, opts?.signal);
}

export function deleteUserRaw(id: string | number, opts?: ClientOpts): Promise<ApiResult<unknown>> {
  return clientRequestRaw("DELETE", `/api/auth/users/${encodeURIComponent(String(id))}`, undefined, undefined, opts?.signal);
}

export function listAPIKeys(opts?: ClientOpts): Promise<APIKeyInfo[] | null> {
  return clientRequest("GET", "/api/auth/apikeys", undefined, (v) => decodeArray(v, decodeAPIKeyInfo, "$"), opts?.signal);
}

export function listAPIKeysRaw(opts?: ClientOpts): Promise<ApiResult<APIKeyInfo[]>> {
  return clientRequestRaw("GET", "/api/auth/apikeys", undefined, (v) => decodeArray(v, decodeAPIKeyInfo, "$"), opts?.signal);
}

export function generateAPIKey(body: unknown, opts?: ClientOpts): Promise<KeyGenerated | null> {
  return clientRequest("POST", "/api/auth/apikeys", body, decodeKeyGenerated, opts?.signal);
}

export function generateAPIKeyRaw(body: unknown, opts?: ClientOpts): Promise<ApiResult<KeyGenerated>> {
  return clientRequestRaw("POST", "/api/auth/apikeys", body, decodeKeyGenerated, opts?.signal);
}

export function revokeAPIKey(id: string | number, opts?: ClientOpts): Promise<boolean> {
  return clientRequestOK("DELETE", `/api/auth/apikeys/${encodeURIComponent(String(id))}`, undefined, opts?.signal);
}

export function revokeAPIKeyRaw(id: string | number, opts?: ClientOpts): Promise<ApiResult<unknown>> {
  return clientRequestRaw("DELETE", `/api/auth/apikeys/${encodeURIComponent(String(id))}`, undefined, undefined, opts?.signal);
}

export function configStructured(opts?: ClientOpts): Promise<StructuredConfig | null> {
  return clientRequest("GET", "/api/config/structured", undefined, decodeStructuredConfig, opts?.signal);
}

export function configStructuredRaw(opts?: ClientOpts): Promise<ApiResult<StructuredConfig>> {
  return clientRequestRaw("GET", "/api/config/structured", undefined, decodeStructuredConfig, opts?.signal);
}

export function saveConfigStructured(body: StructuredConfig, opts?: ClientOpts): Promise<StatusResponse | null> {
  return clientRequest("PUT", "/api/config/structured", body, decodeStatusResponse, opts?.signal);
}

export function saveConfigStructuredRaw(body: StructuredConfig, opts?: ClientOpts): Promise<ApiResult<StatusResponse>> {
  return clientRequestRaw("PUT", "/api/config/structured", body, decodeStatusResponse, opts?.signal);
}

export function resetConfig(opts?: ClientOpts): Promise<boolean> {
  return clientRequestOK("POST", "/api/config/reset", undefined, opts?.signal);
}

export function resetConfigRaw(opts?: ClientOpts): Promise<ApiResult<unknown>> {
  return clientRequestRaw("POST", "/api/config/reset", undefined, undefined, opts?.signal);
}

export function configParsed(opts?: ClientOpts): Promise<ParsedConfig | null> {
  return clientRequest("GET", "/api/config/parsed", undefined, decodeParsedConfig, opts?.signal);
}

export function configParsedRaw(opts?: ClientOpts): Promise<ApiResult<ParsedConfig>> {
  return clientRequestRaw("GET", "/api/config/parsed", undefined, decodeParsedConfig, opts?.signal);
}

export function manualSearch(query?: Record<string, QueryValue>, opts?: ClientOpts): Promise<ManualSearchResponse | null> {
  return clientRequest("GET", "/api/search" + qs(query), undefined, decodeManualSearchResponse, opts?.signal);
}

export function manualSearchRaw(query?: Record<string, QueryValue>, opts?: ClientOpts): Promise<ApiResult<ManualSearchResponse>> {
  return clientRequestRaw("GET", "/api/search" + qs(query), undefined, decodeManualSearchResponse, opts?.signal);
}

/** Resolve a user query (title/imdb/tmdb, optional type/season/episode) onto arr media items for the remote CLI search. */
export function searchResolve(query?: Record<string, QueryValue>, opts?: ClientOpts): Promise<ResolveResponse | null> {
  return clientRequest("GET", "/api/search/resolve" + qs(query), undefined, decodeResolveResponse, opts?.signal);
}

export function searchResolveRaw(query?: Record<string, QueryValue>, opts?: ClientOpts): Promise<ApiResult<ResolveResponse>> {
  return clientRequestRaw("GET", "/api/search/resolve" + qs(query), undefined, decodeResolveResponse, opts?.signal);
}

export function searchTargets(query?: Record<string, QueryValue>, opts?: ClientOpts): Promise<SearchTargets | null> {
  return clientRequest("GET", "/api/search/targets" + qs(query), undefined, decodeSearchTargets, opts?.signal);
}

export function searchTargetsRaw(query?: Record<string, QueryValue>, opts?: ClientOpts): Promise<ApiResult<SearchTargets>> {
  return clientRequestRaw("GET", "/api/search/targets" + qs(query), undefined, decodeSearchTargets, opts?.signal);
}

export function listState(query?: Record<string, QueryValue>, opts?: ClientOpts): Promise<StateEntry[] | null> {
  return clientRequest("GET", "/api/state" + qs(query), undefined, (v) => decodeArray(v, decodeStateEntry, "$"), opts?.signal);
}

export function listStateRaw(query?: Record<string, QueryValue>, opts?: ClientOpts): Promise<ApiResult<StateEntry[]>> {
  return clientRequestRaw("GET", "/api/state" + qs(query), undefined, (v) => decodeArray(v, decodeStateEntry, "$"), opts?.signal);
}

export function stateStats(opts?: ClientOpts): Promise<Stats | null> {
  return clientRequest("GET", "/api/state/stats", undefined, decodeStats, opts?.signal);
}

export function stateStatsRaw(opts?: ClientOpts): Promise<ApiResult<Stats>> {
  return clientRequestRaw("GET", "/api/state/stats", undefined, decodeStats, opts?.signal);
}

export function stateIDs(query?: Record<string, QueryValue>, opts?: ClientOpts): Promise<string[] | null> {
  return clientRequest("GET", "/api/state/ids" + qs(query), undefined, (v) => decodeArray(v, (s) => { if (typeof s !== "string") { throw new TypeError("expected string"); } return s; }, "$"), opts?.signal);
}

export function stateIDsRaw(query?: Record<string, QueryValue>, opts?: ClientOpts): Promise<ApiResult<string[]>> {
  return clientRequestRaw("GET", "/api/state/ids" + qs(query), undefined, (v) => decodeArray(v, (s) => { if (typeof s !== "string") { throw new TypeError("expected string"); } return s; }, "$"), opts?.signal);
}

export function listBackoff(opts?: ClientOpts): Promise<BackoffEntry[] | null> {
  return clientRequest("GET", "/api/backoff", undefined, (v) => decodeArray(v, decodeBackoffEntry, "$"), opts?.signal);
}

export function listBackoffRaw(opts?: ClientOpts): Promise<ApiResult<BackoffEntry[]>> {
  return clientRequestRaw("GET", "/api/backoff", undefined, (v) => decodeArray(v, decodeBackoffEntry, "$"), opts?.signal);
}

export function backoffPrefix(query?: Record<string, QueryValue>, opts?: ClientOpts): Promise<boolean> {
  return clientRequestOK("GET", "/api/backoff/prefix" + qs(query), undefined, opts?.signal);
}

export function backoffPrefixRaw(query?: Record<string, QueryValue>, opts?: ClientOpts): Promise<ApiResult<unknown>> {
  return clientRequestRaw("GET", "/api/backoff/prefix" + qs(query), undefined, undefined, opts?.signal);
}

export function listLocks(opts?: ClientOpts): Promise<ManualLockEntry[] | null> {
  return clientRequest("GET", "/api/locks", undefined, (v) => decodeArray(v, decodeManualLockEntry, "$"), opts?.signal);
}

export function listLocksRaw(opts?: ClientOpts): Promise<ApiResult<ManualLockEntry[]>> {
  return clientRequestRaw("GET", "/api/locks", undefined, (v) => decodeArray(v, decodeManualLockEntry, "$"), opts?.signal);
}

export function listProviders(opts?: ClientOpts): Promise<ProviderInfo[] | null> {
  return clientRequest("GET", "/api/providers", undefined, (v) => decodeArray(v, decodeProviderInfo, "$"), opts?.signal);
}

export function listProvidersRaw(opts?: ClientOpts): Promise<ApiResult<ProviderInfo[]>> {
  return clientRequestRaw("GET", "/api/providers", undefined, (v) => decodeArray(v, decodeProviderInfo, "$"), opts?.signal);
}

export function providerTimeouts(opts?: ClientOpts): Promise<ProvidersResponse | null> {
  return clientRequest("GET", "/api/providers/timeout", undefined, decodeProvidersResponse, opts?.signal);
}

export function providerTimeoutsRaw(opts?: ClientOpts): Promise<ApiResult<ProvidersResponse>> {
  return clientRequestRaw("GET", "/api/providers/timeout", undefined, decodeProvidersResponse, opts?.signal);
}

/** Sonarr series list proxy; response typing intentionally deferred (no UI consumer). */
export function mediaSeries(opts?: ClientOpts): Promise<boolean> {
  return clientRequestOK("GET", "/api/media/series", undefined, opts?.signal);
}

export function mediaSeriesRaw(opts?: ClientOpts): Promise<ApiResult<unknown>> {
  return clientRequestRaw("GET", "/api/media/series", undefined, undefined, opts?.signal);
}

export function mediaMovies(opts?: ClientOpts): Promise<boolean> {
  return clientRequestOK("GET", "/api/media/movies", undefined, opts?.signal);
}

export function mediaMoviesRaw(opts?: ClientOpts): Promise<ApiResult<unknown>> {
  return clientRequestRaw("GET", "/api/media/movies", undefined, undefined, opts?.signal);
}

/** Episodes grouped by season; honors ?recovery=1. */
export function mediaEpisodes(id: string | number, query?: Record<string, QueryValue>, opts?: ClientOpts): Promise<SeasonGroup[] | null> {
  return clientRequest("GET", `/api/media/series/${encodeURIComponent(String(id))}/episodes` + qs(query), undefined, (v) => decodeArray(v, decodeSeasonGroup, "$"), opts?.signal);
}

export function mediaEpisodesRaw(id: string | number, query?: Record<string, QueryValue>, opts?: ClientOpts): Promise<ApiResult<SeasonGroup[]>> {
  return clientRequestRaw("GET", `/api/media/series/${encodeURIComponent(String(id))}/episodes` + qs(query), undefined, (v) => decodeArray(v, decodeSeasonGroup, "$"), opts?.signal);
}

/** Whole-collection series coverage; honors ?recovery=1. */
export function coverageSeries(query?: Record<string, QueryValue>, opts?: ClientOpts): Promise<SeriesItem[] | null> {
  return clientRequest("GET", "/api/coverage/series" + qs(query), undefined, (v) => decodeArray(v, decodeSeriesItem, "$"), opts?.signal);
}

export function coverageSeriesRaw(query?: Record<string, QueryValue>, opts?: ClientOpts): Promise<ApiResult<SeriesItem[]>> {
  return clientRequestRaw("GET", "/api/coverage/series" + qs(query), undefined, (v) => decodeArray(v, decodeSeriesItem, "$"), opts?.signal);
}

/** Whole-collection movie coverage, no inlined subtitle rows (/subs owns them); honors ?recovery=1. */
export function coverageMovies(query?: Record<string, QueryValue>, opts?: ClientOpts): Promise<MovieItem[] | null> {
  return clientRequest("GET", "/api/coverage/movies" + qs(query), undefined, (v) => decodeArray(v, decodeMovieItem, "$"), opts?.signal);
}

export function coverageMoviesRaw(query?: Record<string, QueryValue>, opts?: ClientOpts): Promise<ApiResult<MovieItem[]>> {
  return clientRequestRaw("GET", "/api/coverage/movies" + qs(query), undefined, (v) => decodeArray(v, decodeMovieItem, "$"), opts?.signal);
}

export function coverageSeriesDetail(tvdbId: string | number, opts?: ClientOpts): Promise<SubtitleEntry[] | null> {
  return clientRequest("GET", `/api/coverage/series/${encodeURIComponent(String(tvdbId))}`, undefined, (v) => decodeArray(v, decodeSubtitleEntry, "$"), opts?.signal);
}

export function coverageSeriesDetailRaw(tvdbId: string | number, opts?: ClientOpts): Promise<ApiResult<SubtitleEntry[]>> {
  return clientRequestRaw("GET", `/api/coverage/series/${encodeURIComponent(String(tvdbId))}`, undefined, (v) => decodeArray(v, decodeSubtitleEntry, "$"), opts?.signal);
}

export function coverageScanState(opts?: ClientOpts): Promise<boolean> {
  return clientRequestOK("GET", "/api/coverage/scan-state", undefined, opts?.signal);
}

export function coverageScanStateRaw(opts?: ClientOpts): Promise<ApiResult<unknown>> {
  return clientRequestRaw("GET", "/api/coverage/scan-state", undefined, undefined, opts?.signal);
}

/** Per-item series coverage summary keyed by TVDB id; honors ?recovery=1. 404 exactly where the collection omits. */
export function coverageSeriesSummary(tvdbId: string | number, query?: Record<string, QueryValue>, opts?: ClientOpts): Promise<SeriesItem | null> {
  return clientRequest("GET", `/api/coverage/series/${encodeURIComponent(String(tvdbId))}/summary` + qs(query), undefined, decodeSeriesItem, opts?.signal);
}

export function coverageSeriesSummaryRaw(tvdbId: string | number, query?: Record<string, QueryValue>, opts?: ClientOpts): Promise<ApiResult<SeriesItem>> {
  return clientRequestRaw("GET", `/api/coverage/series/${encodeURIComponent(String(tvdbId))}/summary` + qs(query), undefined, decodeSeriesItem, opts?.signal);
}

/** Per-item movie coverage summary keyed by TMDB id, no subtitle rows; honors ?recovery=1. 404 exactly where the collection omits. */
export function coverageMovieSummary(tmdbId: string | number, query?: Record<string, QueryValue>, opts?: ClientOpts): Promise<MovieItem | null> {
  return clientRequest("GET", `/api/coverage/movies/${encodeURIComponent(String(tmdbId))}/summary` + qs(query), undefined, decodeMovieItem, opts?.signal);
}

export function coverageMovieSummaryRaw(tmdbId: string | number, query?: Record<string, QueryValue>, opts?: ClientOpts): Promise<ApiResult<MovieItem>> {
  return clientRequestRaw("GET", `/api/coverage/movies/${encodeURIComponent(String(tmdbId))}/summary` + qs(query), undefined, decodeMovieItem, opts?.signal);
}

/** One movie's subtitle rows. Store-only: rows or an empty list, no arr read, so it does not honor ?recovery=1. */
export function coverageMovieSubs(tmdbId: string | number, opts?: ClientOpts): Promise<SubtitleEntry[] | null> {
  return clientRequest("GET", `/api/coverage/movies/${encodeURIComponent(String(tmdbId))}/subs`, undefined, (v) => decodeArray(v, decodeSubtitleEntry, "$"), opts?.signal);
}

export function coverageMovieSubsRaw(tmdbId: string | number, opts?: ClientOpts): Promise<ApiResult<SubtitleEntry[]>> {
  return clientRequestRaw("GET", `/api/coverage/movies/${encodeURIComponent(String(tmdbId))}/subs`, undefined, (v) => decodeArray(v, decodeSubtitleEntry, "$"), opts?.signal);
}

/** Video addressed by MediaRef (media_id = arr ID + season/episode); no file path on the wire. */
export function downloadSubtitle(body: DownloadRequest, opts?: ClientOpts): Promise<DownloadAccepted | null> {
  return clientRequest("POST", "/api/search/download", body, decodeDownloadAccepted, opts?.signal);
}

export function downloadSubtitleRaw(body: DownloadRequest, opts?: ClientOpts): Promise<ApiResult<DownloadAccepted>> {
  return clientRequestRaw("POST", "/api/search/download", body, decodeDownloadAccepted, opts?.signal);
}

export function clearLock(body: unknown, opts?: ClientOpts): Promise<boolean> {
  return clientRequestOK("POST", "/api/search/clear-lock", body, opts?.signal);
}

export function clearLockRaw(body: unknown, opts?: ClientOpts): Promise<ApiResult<unknown>> {
  return clientRequestRaw("POST", "/api/search/clear-lock", body, undefined, opts?.signal);
}

export function scoreRelease(body: unknown, opts?: ClientOpts): Promise<ScorePreview | null> {
  return clientRequest("POST", "/api/score", body, decodeScorePreview, opts?.signal);
}

export function scoreReleaseRaw(body: unknown, opts?: ClientOpts): Promise<ApiResult<ScorePreview>> {
  return clientRequestRaw("POST", "/api/score", body, decodeScorePreview, opts?.signal);
}

export function listFiles(query?: Record<string, QueryValue>, opts?: ClientOpts): Promise<FileEntry[] | null> {
  return clientRequest("GET", "/api/files" + qs(query), undefined, (v) => decodeArray(v, decodeFileEntry, "$"), opts?.signal);
}

export function listFilesRaw(query?: Record<string, QueryValue>, opts?: ClientOpts): Promise<ApiResult<FileEntry[]>> {
  return clientRequestRaw("GET", "/api/files" + qs(query), undefined, (v) => decodeArray(v, decodeFileEntry, "$"), opts?.signal);
}

/** File addressed by FileRef fields or a server-minted orphan_handle; no path on the wire. */
export function deleteFile(body: DeleteFileRequest, opts?: ClientOpts): Promise<boolean> {
  return clientRequestOK("DELETE", "/api/files", body, opts?.signal);
}

export function deleteFileRaw(body: DeleteFileRequest, opts?: ClientOpts): Promise<ApiResult<unknown>> {
  return clientRequestRaw("DELETE", "/api/files", body, undefined, opts?.signal);
}

export function bulkDeleteFiles(body: BulkDeleteRequest, opts?: ClientOpts): Promise<boolean> {
  return clientRequestOK("DELETE", "/api/files/bulk", body, opts?.signal);
}

export function bulkDeleteFilesRaw(body: BulkDeleteRequest, opts?: ClientOpts): Promise<ApiResult<unknown>> {
  return clientRequestRaw("DELETE", "/api/files/bulk", body, undefined, opts?.signal);
}

/** Dispatch one async audio-sync job: 202 {activity_id, job_id} after validation; the terminal result rides the sync:done event (matched on job_id) and the jobs read. Same-file dispatch answers the existing job's ids; a full admission lease answers 429. */
export function syncAudio(body: SyncAudioRequest, opts?: ClientOpts): Promise<SyncAccepted | null> {
  return clientRequest("POST", "/api/sync/audio", body, decodeSyncAccepted, opts?.signal);
}

export function syncAudioRaw(body: SyncAudioRequest, opts?: ClientOpts): Promise<ApiResult<SyncAccepted>> {
  return clientRequestRaw("POST", "/api/sync/audio", body, decodeSyncAccepted, opts?.signal);
}

/** Dispatch one server-owned season sync batch: the season's subtitle files are enumerated server-side and answer 202 {activity_id}. Item job ids arrive via the jobs read filtered by batch_activity_id and the per-item sync:done events; a live batch for the same season answers its existing id; a full admission lease answers 429. */
export function syncSeason(body: SyncSeasonRequest, opts?: ClientOpts): Promise<SeasonSyncAccepted | null> {
  return clientRequest("POST", "/api/sync/season", body, decodeSeasonSyncAccepted, opts?.signal);
}

export function syncSeasonRaw(body: SyncSeasonRequest, opts?: ClientOpts): Promise<ApiResult<SeasonSyncAccepted>> {
  return clientRequestRaw("POST", "/api/sync/season", body, decodeSeasonSyncAccepted, opts?.signal);
}

export function syncOffset(body: SyncOffsetRequest, opts?: ClientOpts): Promise<boolean> {
  return clientRequestOK("POST", "/api/sync/offset", body, opts?.signal);
}

export function syncOffsetRaw(body: SyncOffsetRequest, opts?: ClientOpts): Promise<ApiResult<unknown>> {
  return clientRequestRaw("POST", "/api/sync/offset", body, undefined, opts?.signal);
}

/** Sync job registry in total order (accepted_at DESC, job_id DESC), filterable by batch_activity_id; the reload path re-attaches through it. */
export function syncJobs(query?: Record<string, QueryValue>, opts?: ClientOpts): Promise<Job[] | null> {
  return clientRequest("GET", "/api/sync/jobs" + qs(query), undefined, (v) => decodeArray(v, decodeJob, "$"), opts?.signal);
}

export function syncJobsRaw(query?: Record<string, QueryValue>, opts?: ClientOpts): Promise<ApiResult<Job[]>> {
  return clientRequestRaw("GET", "/api/sync/jobs" + qs(query), undefined, (v) => decodeArray(v, decodeJob, "$"), opts?.signal);
}

export function previewStart(query?: Record<string, QueryValue>, opts?: ClientOpts): Promise<PreviewStartResponse | null> {
  return clientRequest("GET", "/api/preview/start" + qs(query), undefined, decodePreviewStartResponse, opts?.signal);
}

export function previewStartRaw(query?: Record<string, QueryValue>, opts?: ClientOpts): Promise<ApiResult<PreviewStartResponse>> {
  return clientRequestRaw("GET", "/api/preview/start" + qs(query), undefined, decodePreviewStartResponse, opts?.signal);
}

/** Trigger a full library scan (202 + activity_id; 409 while one runs). */
export function startScan(opts?: ClientOpts): Promise<ScanAccepted | null> {
  return clientRequest("POST", "/api/scan", undefined, decodeScanAccepted, opts?.signal);
}

export function startScanRaw(opts?: ClientOpts): Promise<ApiResult<ScanAccepted>> {
  return clientRequestRaw("POST", "/api/scan", undefined, decodeScanAccepted, opts?.signal);
}

export function scanSeries(id: string | number, opts?: ClientOpts): Promise<ScanAccepted | null> {
  return clientRequest("POST", `/api/scan/series/${encodeURIComponent(String(id))}`, undefined, decodeScanAccepted, opts?.signal);
}

export function scanSeriesRaw(id: string | number, opts?: ClientOpts): Promise<ApiResult<ScanAccepted>> {
  return clientRequestRaw("POST", `/api/scan/series/${encodeURIComponent(String(id))}`, undefined, decodeScanAccepted, opts?.signal);
}

export function scanSeason(id: string | number, season: string | number, opts?: ClientOpts): Promise<ScanAccepted | null> {
  return clientRequest("POST", `/api/scan/season/${encodeURIComponent(String(id))}/${encodeURIComponent(String(season))}`, undefined, decodeScanAccepted, opts?.signal);
}

export function scanSeasonRaw(id: string | number, season: string | number, opts?: ClientOpts): Promise<ApiResult<ScanAccepted>> {
  return clientRequestRaw("POST", `/api/scan/season/${encodeURIComponent(String(id))}/${encodeURIComponent(String(season))}`, undefined, decodeScanAccepted, opts?.signal);
}

export function scanMovie(id: string | number, opts?: ClientOpts): Promise<ScanAccepted | null> {
  return clientRequest("POST", `/api/scan/movie/${encodeURIComponent(String(id))}`, undefined, decodeScanAccepted, opts?.signal);
}

export function scanMovieRaw(id: string | number, opts?: ClientOpts): Promise<ApiResult<ScanAccepted>> {
  return clientRequestRaw("POST", `/api/scan/movie/${encodeURIComponent(String(id))}`, undefined, decodeScanAccepted, opts?.signal);
}

export function scanItem(body: unknown, opts?: ClientOpts): Promise<ScanAccepted | null> {
  return clientRequest("POST", "/api/scan/item", body, decodeScanAccepted, opts?.signal);
}

export function scanItemRaw(body: unknown, opts?: ClientOpts): Promise<ApiResult<ScanAccepted>> {
  return clientRequestRaw("POST", "/api/scan/item", body, decodeScanAccepted, opts?.signal);
}

export function resetProviderTimeouts(opts?: ClientOpts): Promise<boolean> {
  return clientRequestOK("POST", "/api/providers/timeout/reset", undefined, opts?.signal);
}

export function resetProviderTimeoutsRaw(opts?: ClientOpts): Promise<ApiResult<unknown>> {
  return clientRequestRaw("POST", "/api/providers/timeout/reset", undefined, undefined, opts?.signal);
}
