// CODE-GENERATED by cmd/wire-codegen, DO NOT EDIT.

import { asObject, reqStr, reqNum, reqBool, optStr, optNum, optBool, reqOneOf, decodeArray, decodeRecord, type Decoder } from "../validators.js";
import type { APIKeyInfo, ActivityEntry, AdminUserCreatedResponse, Alert, AudioRule, BackoffEntry, BulkDeleteRequest, CoverageEvent, CoverageTarget, DeleteFileRequest, DownloadAccepted, DownloadRequest, EpisodeItem, EventData, FileEntry, KeyGenerated, LanguageRules, LoginSuccess, ManualLockEntry, ManualSearchResponse, MeResponse, MovieItem, NotifyEvent, ParsedConfig, PasskeyInfo, PasskeyRegistered, PathValidationResponse, PostProcessConfig, PreviewStartResponse, ProviderInfo, ProviderSchema, ProviderStatus, ProvidersResponse, ResolveCandidate, ResolveResponse, ResolveSearchIDs, ResolvedItem, ScanAccepted, ScanEvent, SchemaField, SchemaOption, SchemaSection, ScorePreview, Scores, SearchResult, SearchTarget, SearchTargets, SeasonGroup, SeriesItem, SetupStatus, SignalData, StateEntry, Stats, StatusResponse, StructuredConfig, SubtitleEntry, SubtitleTarget, SyncAudioRequest, SyncAudioResponse, SyncOffsetRequest, UserInfo, WebAuthnLoginBeginResponse, WebAuthnRegisterBeginResponse } from "./types.gen.js";

const ACTIVITY_SOURCES = ["scheduled", "manual"] as const;
const ALERT_KINDS = ["persistent", "transient"] as const;
const ALERT_LEVELS = ["error", "warn", "info"] as const;
const MEDIA_TYPES = ["movie", "episode", "series"] as const;
const NOTIFY_LEVELS = ["error", "success", "info"] as const;
const OUTCOMES = ["completed", "failed", "cancelled", "shutdown"] as const;
const ROLES = ["admin", "user"] as const;
const SCAN_KINDS = ["series", "season", "movie", "item", "full"] as const;
const SCORE_TIERS = ["excellent", "good", "acceptable", "minimal", "none"] as const;
const VARIANTS = ["standard", "hi", "forced"] as const;

export const decodeAPIKeyInfo: Decoder<APIKeyInfo> = (v) => {
  const o = asObject(v, "$.api_key_info");
  const out: APIKeyInfo = {
    created_at: reqStr(o, "created_at", "$.api_key_info"),
    key_prefix: reqStr(o, "key_prefix", "$.api_key_info"),
    key_suffix: reqStr(o, "key_suffix", "$.api_key_info"),
    label: reqStr(o, "label", "$.api_key_info"),
    id: reqNum(o, "id", "$.api_key_info"),
  };
  return out;
};

export const decodeActivityEntry: Decoder<ActivityEntry> = (v) => {
  const o = asObject(v, "$.activity_entry");
  const out: ActivityEntry = {
    started_at: reqStr(o, "started_at", "$.activity_entry"),
    id: reqStr(o, "id", "$.activity_entry"),
    action: reqStr(o, "action", "$.activity_entry"),
    detail: reqStr(o, "detail", "$.activity_entry"),
    source: reqOneOf(o, "source", ACTIVITY_SOURCES, "$.activity_entry"),
    done: reqBool(o, "done", "$.activity_entry"),
  };
  const endedAt = o["ended_at"] === null ? undefined : optStr(o, "ended_at", "$.activity_entry");
  if (endedAt !== undefined) out.ended_at = endedAt;
  if (o["kind"] !== undefined && o["kind"] !== null) out.kind = reqOneOf(o, "kind", SCAN_KINDS, "$.activity_entry");
  if (o["media_type"] !== undefined && o["media_type"] !== null) out.media_type = reqOneOf(o, "media_type", MEDIA_TYPES, "$.activity_entry");
  if (o["required_role"] !== undefined && o["required_role"] !== null) out.required_role = reqOneOf(o, "required_role", ROLES, "$.activity_entry");
  const mediaId = o["media_id"] === null ? undefined : optNum(o, "media_id", "$.activity_entry");
  if (mediaId !== undefined) out.media_id = mediaId;
  const season = o["season"] === null ? undefined : optNum(o, "season", "$.activity_entry");
  if (season !== undefined) out.season = season;
  const episode = o["episode"] === null ? undefined : optNum(o, "episode", "$.activity_entry");
  if (episode !== undefined) out.episode = episode;
  const current = o["current"] === null ? undefined : optNum(o, "current", "$.activity_entry");
  if (current !== undefined) out.current = current;
  const total = o["total"] === null ? undefined : optNum(o, "total", "$.activity_entry");
  if (total !== undefined) out.total = total;
  const queued = o["queued"] === null ? undefined : optBool(o, "queued", "$.activity_entry");
  if (queued !== undefined) out.queued = queued;
  const cancelled = o["cancelled"] === null ? undefined : optBool(o, "cancelled", "$.activity_entry");
  if (cancelled !== undefined) out.cancelled = cancelled;
  const failed = o["failed"] === null ? undefined : optBool(o, "failed", "$.activity_entry");
  if (failed !== undefined) out.failed = failed;
  const cancellable = o["cancellable"] === null ? undefined : optBool(o, "cancellable", "$.activity_entry");
  if (cancellable !== undefined) out.cancellable = cancellable;
  return out;
};

export const decodeAdminUserCreatedResponse: Decoder<AdminUserCreatedResponse> = (v) => {
  const o = asObject(v, "$.admin_user_created_response");
  const out: AdminUserCreatedResponse = {
    username: reqStr(o, "username", "$.admin_user_created_response"),
    email: reqStr(o, "email", "$.admin_user_created_response"),
    role: reqOneOf(o, "role", ROLES, "$.admin_user_created_response"),
    id: reqNum(o, "id", "$.admin_user_created_response"),
  };
  return out;
};

export const decodeAlert: Decoder<Alert> = (v) => {
  const o = asObject(v, "$.alert");
  const out: Alert = {
    time: reqStr(o, "time", "$.alert"),
    level: reqOneOf(o, "level", ALERT_LEVELS, "$.alert"),
    message: reqStr(o, "message", "$.alert"),
    source: reqStr(o, "source", "$.alert"),
    kind: reqOneOf(o, "kind", ALERT_KINDS, "$.alert"),
    id: reqNum(o, "id", "$.alert"),
    dismissed: reqBool(o, "dismissed", "$.alert"),
  };
  return out;
};

export const decodeAudioRule: Decoder<AudioRule> = (v) => {
  const o = asObject(v, "$.audio_rule");
  const out: AudioRule = {
    audio: reqStr(o, "audio", "$.audio_rule"),
    subtitles: o["subtitles"] === null ? [] : decodeArray(o["subtitles"], decodeSubtitleTarget, "$.audio_rule.subtitles"),
  };
  return out;
};

export const decodeBackoffEntry: Decoder<BackoffEntry> = (v) => {
  const o = asObject(v, "$.backoff_entry");
  const out: BackoffEntry = {
    last_tried: reqStr(o, "last_tried", "$.backoff_entry"),
    next_retry: reqStr(o, "next_retry", "$.backoff_entry"),
    media_type: reqOneOf(o, "media_type", MEDIA_TYPES, "$.backoff_entry"),
    media_id: reqStr(o, "media_id", "$.backoff_entry"),
    language: reqStr(o, "language", "$.backoff_entry"),
    provider: reqStr(o, "provider", "$.backoff_entry"),
    failures: reqNum(o, "failures", "$.backoff_entry"),
  };
  return out;
};

export const decodeBulkDeleteRequest: Decoder<BulkDeleteRequest> = (v) => {
  const o = asObject(v, "$.bulk_delete_request");
  const out: BulkDeleteRequest = {
    media_type: reqOneOf(o, "media_type", MEDIA_TYPES, "$.bulk_delete_request"),
    media_id: reqStr(o, "media_id", "$.bulk_delete_request"),
  };
  return out;
};

export const decodeCoverageEvent: Decoder<CoverageEvent> = (v) => {
  const o = asObject(v, "$.coverage_event");
  const out: CoverageEvent = {
    media_type: reqOneOf(o, "media_type", MEDIA_TYPES, "$.coverage_event"),
    media_id: reqStr(o, "media_id", "$.coverage_event"),
    language: reqStr(o, "language", "$.coverage_event"),
    variant: reqStr(o, "variant", "$.coverage_event"),
    source: reqStr(o, "source", "$.coverage_event"),
  };
  return out;
};

export const decodeCoverageTarget: Decoder<CoverageTarget> = (v) => {
  const o = asObject(v, "$.coverage_target");
  const out: CoverageTarget = {
    language: reqStr(o, "language", "$.coverage_target"),
    variant: reqStr(o, "variant", "$.coverage_target"),
    have: reqNum(o, "have", "$.coverage_target"),
    have_ignored: reqNum(o, "have_ignored", "$.coverage_target"),
    total: reqNum(o, "total", "$.coverage_target"),
  };
  return out;
};

export const decodeDeleteFileRequest: Decoder<DeleteFileRequest> = (v) => {
  const o = asObject(v, "$.delete_file_request");
  const out: DeleteFileRequest = {
  };
  if (o["media_type"] !== undefined && o["media_type"] !== null) out.media_type = reqOneOf(o, "media_type", MEDIA_TYPES, "$.delete_file_request");
  const mediaId = o["media_id"] === null ? undefined : optStr(o, "media_id", "$.delete_file_request");
  if (mediaId !== undefined) out.media_id = mediaId;
  const language = o["language"] === null ? undefined : optStr(o, "language", "$.delete_file_request");
  if (language !== undefined) out.language = language;
  const variant = o["variant"] === null ? undefined : optStr(o, "variant", "$.delete_file_request");
  if (variant !== undefined) out.variant = variant;
  const source = o["source"] === null ? undefined : optStr(o, "source", "$.delete_file_request");
  if (source !== undefined) out.source = source;
  const orphanHandle = o["orphan_handle"] === null ? undefined : optStr(o, "orphan_handle", "$.delete_file_request");
  if (orphanHandle !== undefined) out.orphan_handle = orphanHandle;
  const ordinal = o["ordinal"] === null ? undefined : optNum(o, "ordinal", "$.delete_file_request");
  if (ordinal !== undefined) out.ordinal = ordinal;
  return out;
};

export const decodeDownloadAccepted: Decoder<DownloadAccepted> = (v) => {
  const o = asObject(v, "$.download_accepted");
  const out: DownloadAccepted = {
    activity_id: reqStr(o, "activity_id", "$.download_accepted"),
    status: reqStr(o, "status", "$.download_accepted"),
  };
  return out;
};

export const decodeDownloadRequest: Decoder<DownloadRequest> = (v) => {
  const o = asObject(v, "$.download_request");
  const out: DownloadRequest = {
    provider: reqStr(o, "provider", "$.download_request"),
    subtitle_id: reqStr(o, "subtitle_id", "$.download_request"),
    language: reqStr(o, "language", "$.download_request"),
  };
  const releaseName = o["release_name"] === null ? undefined : optStr(o, "release_name", "$.download_request");
  if (releaseName !== undefined) out.release_name = releaseName;
  if (o["media_type"] !== undefined && o["media_type"] !== null) out.media_type = reqOneOf(o, "media_type", MEDIA_TYPES, "$.download_request");
  const score = o["score"] === null ? undefined : optNum(o, "score", "$.download_request");
  if (score !== undefined) out.score = score;
  const season = o["season"] === null ? undefined : optNum(o, "season", "$.download_request");
  if (season !== undefined) out.season = season;
  const episode = o["episode"] === null ? undefined : optNum(o, "episode", "$.download_request");
  if (episode !== undefined) out.episode = episode;
  const mediaId = o["media_id"] === null ? undefined : optNum(o, "media_id", "$.download_request");
  if (mediaId !== undefined) out.media_id = mediaId;
  const topPick = o["top_pick"] === null ? undefined : optBool(o, "top_pick", "$.download_request");
  if (topPick !== undefined) out.top_pick = topPick;
  const hearingImpaired = o["hearing_impaired"] === null ? undefined : optBool(o, "hearing_impaired", "$.download_request");
  if (hearingImpaired !== undefined) out.hearing_impaired = hearingImpaired;
  const forced = o["forced"] === null ? undefined : optBool(o, "forced", "$.download_request");
  if (forced !== undefined) out.forced = forced;
  return out;
};

export const decodeEpisodeItem: Decoder<EpisodeItem> = (v) => {
  const o = asObject(v, "$.episode_item");
  const out: EpisodeItem = {
    title: reqStr(o, "title", "$.episode_item"),
    id: reqNum(o, "id", "$.episode_item"),
    season: reqNum(o, "season", "$.episode_item"),
    episode: reqNum(o, "episode", "$.episode_item"),
    has_file: reqBool(o, "has_file", "$.episode_item"),
  };
  const sceneName = o["scene_name"] === null ? undefined : optStr(o, "scene_name", "$.episode_item");
  if (sceneName !== undefined) out.scene_name = sceneName;
  const sceneSeason = o["scene_season"] === null ? undefined : optNum(o, "scene_season", "$.episode_item");
  if (sceneSeason !== undefined) out.scene_season = sceneSeason;
  const sceneEpisode = o["scene_episode"] === null ? undefined : optNum(o, "scene_episode", "$.episode_item");
  if (sceneEpisode !== undefined) out.scene_episode = sceneEpisode;
  const absoluteEpisode = o["absolute_episode"] === null ? undefined : optNum(o, "absolute_episode", "$.episode_item");
  if (absoluteEpisode !== undefined) out.absolute_episode = absoluteEpisode;
  return out;
};

export const decodeFileEntry: Decoder<FileEntry> = (v) => {
  const o = asObject(v, "$.file_entry");
  const out: FileEntry = {
    media_id: reqStr(o, "media_id", "$.file_entry"),
    language: reqStr(o, "language", "$.file_entry"),
    variant: reqStr(o, "variant", "$.file_entry"),
    source: reqStr(o, "source", "$.file_entry"),
  };
  const codec = o["codec"] === null ? undefined : optStr(o, "codec", "$.file_entry");
  if (codec !== undefined) out.codec = codec;
  const name = o["name"] === null ? undefined : optStr(o, "name", "$.file_entry");
  if (name !== undefined) out.name = name;
  const orphanHandle = o["orphan_handle"] === null ? undefined : optStr(o, "orphan_handle", "$.file_entry");
  if (orphanHandle !== undefined) out.orphan_handle = orphanHandle;
  const score = o["score"] === null ? undefined : optNum(o, "score", "$.file_entry");
  if (score !== undefined) out.score = score;
  const ordinal = o["ordinal"] === null ? undefined : optNum(o, "ordinal", "$.file_entry");
  if (ordinal !== undefined) out.ordinal = ordinal;
  const offsetMs = o["offset_ms"] === null ? undefined : optNum(o, "offset_ms", "$.file_entry");
  if (offsetMs !== undefined) out.offset_ms = offsetMs;
  const size = o["size"] === null ? undefined : optNum(o, "size", "$.file_entry");
  if (size !== undefined) out.size = size;
  return out;
};

export const decodeKeyGenerated: Decoder<KeyGenerated> = (v) => {
  const o = asObject(v, "$.key_generated");
  const out: KeyGenerated = {
    created_at: reqStr(o, "created_at", "$.key_generated"),
    key: reqStr(o, "key", "$.key_generated"),
    key_prefix: reqStr(o, "key_prefix", "$.key_generated"),
    key_suffix: reqStr(o, "key_suffix", "$.key_generated"),
    label: reqStr(o, "label", "$.key_generated"),
    id: reqNum(o, "id", "$.key_generated"),
  };
  return out;
};

export const decodeLanguageRules: Decoder<LanguageRules> = (v) => {
  const o = asObject(v, "$.language_rules");
  const out: LanguageRules = {
  };
  if (o["rules"] !== undefined && o["rules"] !== null) out.rules = decodeArray(o["rules"], decodeAudioRule, "$.language_rules.rules");
  if (o["default"] !== undefined && o["default"] !== null) out.default = decodeArray(o["default"], decodeSubtitleTarget, "$.language_rules.default");
  return out;
};

export const decodeLoginSuccess: Decoder<LoginSuccess> = (v) => {
  const o = asObject(v, "$.login_success");
  const out: LoginSuccess = {
    redirect: reqStr(o, "redirect", "$.login_success"),
    user: decodeMeResponse(o["user"]),
  };
  return out;
};

export const decodeManualLockEntry: Decoder<ManualLockEntry> = (v) => {
  const o = asObject(v, "$.manual_lock_entry");
  const out: ManualLockEntry = {
    media_type: reqOneOf(o, "media_type", MEDIA_TYPES, "$.manual_lock_entry"),
    media_id: reqStr(o, "media_id", "$.manual_lock_entry"),
    language: reqStr(o, "language", "$.manual_lock_entry"),
    variant: reqOneOf(o, "variant", VARIANTS, "$.manual_lock_entry"),
    count: reqNum(o, "count", "$.manual_lock_entry"),
  };
  return out;
};

export const decodeManualSearchResponse: Decoder<ManualSearchResponse> = (v) => {
  const o = asObject(v, "$.manual_search_response");
  const out: ManualSearchResponse = {
    results: o["results"] === null ? [] : decodeArray(o["results"], decodeSearchResult, "$.manual_search_response.results"),
  };
  return out;
};

export const decodeMeResponse: Decoder<MeResponse> = (v) => {
  const o = asObject(v, "$.me_response");
  const out: MeResponse = {
    username: reqStr(o, "username", "$.me_response"),
    role: reqOneOf(o, "role", ROLES, "$.me_response"),
    id: reqNum(o, "id", "$.me_response"),
    has_passkeys: reqBool(o, "has_passkeys", "$.me_response"),
    oidc_linked: reqBool(o, "oidc_linked", "$.me_response"),
    has_password: reqBool(o, "has_password", "$.me_response"),
    can_link_oidc: reqBool(o, "can_link_oidc", "$.me_response"),
  };
  return out;
};

export const decodeMovieItem: Decoder<MovieItem> = (v) => {
  const o = asObject(v, "$.movie_item");
  const out: MovieItem = {
    title: reqStr(o, "title", "$.movie_item"),
    audio_lang: reqStr(o, "audio_lang", "$.movie_item"),
    rule: reqStr(o, "rule", "$.movie_item"),
    targets: o["targets"] === null ? [] : decodeArray(o["targets"], decodeCoverageTarget, "$.movie_item.targets"),
    subs: o["subs"] === null ? [] : decodeArray(o["subs"], decodeSubtitleEntry, "$.movie_item.subs"),
    tmdb_id: reqNum(o, "tmdb_id", "$.movie_item"),
    id: reqNum(o, "id", "$.movie_item"),
    year: reqNum(o, "year", "$.movie_item"),
    has_file: reqBool(o, "has_file", "$.movie_item"),
  };
  const imdbId = o["imdb_id"] === null ? undefined : optStr(o, "imdb_id", "$.movie_item");
  if (imdbId !== undefined) out.imdb_id = imdbId;
  const sceneName = o["scene_name"] === null ? undefined : optStr(o, "scene_name", "$.movie_item");
  if (sceneName !== undefined) out.scene_name = sceneName;
  const inCinemas = o["in_cinemas"] === null ? undefined : optStr(o, "in_cinemas", "$.movie_item");
  if (inCinemas !== undefined) out.in_cinemas = inCinemas;
  const digitalRelease = o["digital_release"] === null ? undefined : optStr(o, "digital_release", "$.movie_item");
  if (digitalRelease !== undefined) out.digital_release = digitalRelease;
  if (o["tags"] !== undefined && o["tags"] !== null) out.tags = decodeArray(o["tags"], (v) => { if (typeof v !== "number") throw new TypeError("expected number"); return v as number; }, "$.movie_item.tags");
  const excluded = o["excluded"] === null ? undefined : optBool(o, "excluded", "$.movie_item");
  if (excluded !== undefined) out.excluded = excluded;
  return out;
};

export const decodeNotifyEvent: Decoder<NotifyEvent> = (v) => {
  const o = asObject(v, "$.notify_event");
  const out: NotifyEvent = {
    level: reqOneOf(o, "level", NOTIFY_LEVELS, "$.notify_event"),
    text: reqStr(o, "text", "$.notify_event"),
  };
  return out;
};

export const decodeParsedConfig: Decoder<ParsedConfig> = (v) => {
  const o = asObject(v, "$.parsed_config");
  const out: ParsedConfig = {
    adaptive: o["adaptive"] as unknown,
    search: o["search"] as unknown,
    providers: o["providers"] === null ? {} : decodeRecord(o["providers"], (v) => { if (typeof v !== "boolean") throw new TypeError("expected boolean"); return v as boolean; }, "$.parsed_config.providers"),
    language_rules: decodeLanguageRules(o["language_rules"]),
    languages: o["languages"] === null ? [] : decodeArray(o["languages"], (v) => { if (typeof v !== "string") throw new TypeError("expected string"); return v as string; }, "$.parsed_config.languages"),
    scores: decodeScores(o["scores"]),
    post_processing: decodePostProcessConfig(o["post_processing"]),
    configured: reqBool(o, "configured", "$.parsed_config"),
    sonarr_configured: reqBool(o, "sonarr_configured", "$.parsed_config"),
    radarr_configured: reqBool(o, "radarr_configured", "$.parsed_config"),
  };
  const sonarrUrl = o["sonarr_url"] === null ? undefined : optStr(o, "sonarr_url", "$.parsed_config");
  if (sonarrUrl !== undefined) out.sonarr_url = sonarrUrl;
  const radarrUrl = o["radarr_url"] === null ? undefined : optStr(o, "radarr_url", "$.parsed_config");
  if (radarrUrl !== undefined) out.radarr_url = radarrUrl;
  if (o["ignored_codecs"] !== undefined && o["ignored_codecs"] !== null) out.ignored_codecs = decodeArray(o["ignored_codecs"], (v) => { if (typeof v !== "string") throw new TypeError("expected string"); return v as string; }, "$.parsed_config.ignored_codecs");
  return out;
};

export const decodePasskeyInfo: Decoder<PasskeyInfo> = (v) => {
  const o = asObject(v, "$.passkey_info");
  const out: PasskeyInfo = {
    created_at: reqStr(o, "created_at", "$.passkey_info"),
    name: reqStr(o, "name", "$.passkey_info"),
    id: reqNum(o, "id", "$.passkey_info"),
    backup_eligible: reqBool(o, "backup_eligible", "$.passkey_info"),
  };
  const transport = o["transport"] === null ? undefined : optStr(o, "transport", "$.passkey_info");
  if (transport !== undefined) out.transport = transport;
  return out;
};

export const decodePasskeyRegistered: Decoder<PasskeyRegistered> = (v) => {
  const o = asObject(v, "$.passkey_registered");
  const out: PasskeyRegistered = {
    created_at: reqStr(o, "created_at", "$.passkey_registered"),
    name: reqStr(o, "name", "$.passkey_registered"),
    transport: reqStr(o, "transport", "$.passkey_registered"),
    id: reqNum(o, "id", "$.passkey_registered"),
  };
  return out;
};

export const decodePathValidationResponse: Decoder<PathValidationResponse> = (v) => {
  const o = asObject(v, "$.path_validation_response");
  const out: PathValidationResponse = {
    valid: reqBool(o, "valid", "$.path_validation_response"),
  };
  const error = o["error"] === null ? undefined : optStr(o, "error", "$.path_validation_response");
  if (error !== undefined) out.error = error;
  return out;
};

export const decodePostProcessConfig: Decoder<PostProcessConfig> = (v) => {
  const o = asObject(v, "$.post_process_config");
  const out: PostProcessConfig = {
    strip_hi: reqBool(o, "strip_hi", "$.post_process_config"),
    strip_tags: reqBool(o, "strip_tags", "$.post_process_config"),
    normalize_utf8: reqBool(o, "normalize_utf8", "$.post_process_config"),
    clean_whitespace: reqBool(o, "clean_whitespace", "$.post_process_config"),
    normalize_endings: reqBool(o, "normalize_endings", "$.post_process_config"),
    remove_empty: reqBool(o, "remove_empty", "$.post_process_config"),
  };
  return out;
};

export const decodePreviewStartResponse: Decoder<PreviewStartResponse> = (v) => {
  const o = asObject(v, "$.preview_start_response");
  const out: PreviewStartResponse = {
    description: reqStr(o, "description", "$.preview_start_response"),
    start_seconds: reqNum(o, "start_seconds", "$.preview_start_response"),
  };
  return out;
};

export const decodeProviderInfo: Decoder<ProviderInfo> = (v) => {
  const o = asObject(v, "$.provider_info");
  const out: ProviderInfo = {
    name: reqStr(o, "name", "$.provider_info"),
    enabled: reqBool(o, "enabled", "$.provider_info"),
    loaded: reqBool(o, "loaded", "$.provider_info"),
  };
  return out;
};

export const decodeProviderSchema: Decoder<ProviderSchema> = (v) => {
  const o = asObject(v, "$.provider_schema");
  const out: ProviderSchema = {
    name: reqStr(o, "name", "$.provider_schema"),
    label: reqStr(o, "label", "$.provider_schema"),
  };
  if (o["settings"] !== undefined && o["settings"] !== null) out.settings = decodeArray(o["settings"], decodeSchemaField, "$.provider_schema.settings");
  return out;
};

export const decodeProviderStatus: Decoder<ProviderStatus> = (v) => {
  const o = asObject(v, "$.provider_status");
  const out: ProviderStatus = {
    recent_failures: reqNum(o, "recent_failures", "$.provider_status"),
    threshold: reqNum(o, "threshold", "$.provider_status"),
    timed_out: reqBool(o, "timed_out", "$.provider_status"),
  };
  const lastError = o["last_error"] === null ? undefined : optStr(o, "last_error", "$.provider_status");
  if (lastError !== undefined) out.last_error = lastError;
  const cooldownRemaining = o["cooldown_remaining"] === null ? undefined : optNum(o, "cooldown_remaining", "$.provider_status");
  if (cooldownRemaining !== undefined) out.cooldown_remaining = cooldownRemaining;
  return out;
};

export const decodeProvidersResponse: Decoder<ProvidersResponse> = (v) => {
  const o = asObject(v, "$.providers_response");
  const out: ProvidersResponse = {
    providers: o["providers"] === null ? {} : decodeRecord(o["providers"], decodeProviderStatus, "$.providers_response.providers"),
    enabled: reqBool(o, "enabled", "$.providers_response"),
  };
  return out;
};

export const decodeResolveCandidate: Decoder<ResolveCandidate> = (v) => {
  const o = asObject(v, "$.resolve_candidate");
  const out: ResolveCandidate = {
    media_type: reqOneOf(o, "media_type", MEDIA_TYPES, "$.resolve_candidate"),
    title: reqStr(o, "title", "$.resolve_candidate"),
    media_id: reqNum(o, "media_id", "$.resolve_candidate"),
  };
  const year = o["year"] === null ? undefined : optNum(o, "year", "$.resolve_candidate");
  if (year !== undefined) out.year = year;
  return out;
};

export const decodeResolveResponse: Decoder<ResolveResponse> = (v) => {
  const o = asObject(v, "$.resolve_response");
  const out: ResolveResponse = {
    resolved: reqBool(o, "resolved", "$.resolve_response"),
  };
  if (o["items"] !== undefined && o["items"] !== null) out.items = decodeArray(o["items"], decodeResolvedItem, "$.resolve_response.items");
  if (o["candidates"] !== undefined && o["candidates"] !== null) out.candidates = decodeArray(o["candidates"], decodeResolveCandidate, "$.resolve_response.candidates");
  return out;
};

export const decodeResolveSearchIDs: Decoder<ResolveSearchIDs> = (v) => {
  const o = asObject(v, "$.resolve_search_i_ds");
  const out: ResolveSearchIDs = {
  };
  const imdb = o["imdb"] === null ? undefined : optStr(o, "imdb", "$.resolve_search_i_ds");
  if (imdb !== undefined) out.imdb = imdb;
  const tvdb = o["tvdb"] === null ? undefined : optNum(o, "tvdb", "$.resolve_search_i_ds");
  if (tvdb !== undefined) out.tvdb = tvdb;
  const tmdb = o["tmdb"] === null ? undefined : optNum(o, "tmdb", "$.resolve_search_i_ds");
  if (tmdb !== undefined) out.tmdb = tmdb;
  return out;
};

export const decodeResolvedItem: Decoder<ResolvedItem> = (v) => {
  const o = asObject(v, "$.resolved_item");
  const out: ResolvedItem = {
    media_type: reqOneOf(o, "media_type", MEDIA_TYPES, "$.resolved_item"),
    title: reqStr(o, "title", "$.resolved_item"),
    search_ids: decodeResolveSearchIDs(o["search_ids"]),
    media_id: reqNum(o, "media_id", "$.resolved_item"),
  };
  const year = o["year"] === null ? undefined : optNum(o, "year", "$.resolved_item");
  if (year !== undefined) out.year = year;
  const season = o["season"] === null ? undefined : optNum(o, "season", "$.resolved_item");
  if (season !== undefined) out.season = season;
  const episode = o["episode"] === null ? undefined : optNum(o, "episode", "$.resolved_item");
  if (episode !== undefined) out.episode = episode;
  return out;
};

export const decodeScanAccepted: Decoder<ScanAccepted> = (v) => {
  const o = asObject(v, "$.scan_accepted");
  const out: ScanAccepted = {
    activity_id: reqStr(o, "activity_id", "$.scan_accepted"),
    status: reqStr(o, "status", "$.scan_accepted"),
  };
  return out;
};

export const decodeScanEvent: Decoder<ScanEvent> = (v) => {
  const o = asObject(v, "$.scan_event");
  const out: ScanEvent = {
    action: reqStr(o, "action", "$.scan_event"),
    detail: reqStr(o, "detail", "$.scan_event"),
    source: reqOneOf(o, "source", ACTIVITY_SOURCES, "$.scan_event"),
  };
  const activityId = o["activity_id"] === null ? undefined : optStr(o, "activity_id", "$.scan_event");
  if (activityId !== undefined) out.activity_id = activityId;
  if (o["outcome"] !== undefined && o["outcome"] !== null) out.outcome = reqOneOf(o, "outcome", OUTCOMES, "$.scan_event");
  return out;
};

export const decodeSchemaField: Decoder<SchemaField> = (v) => {
  const o = asObject(v, "$.schema_field");
  const out: SchemaField = {
    key: reqStr(o, "key", "$.schema_field"),
    label: reqStr(o, "label", "$.schema_field"),
    type: reqStr(o, "type", "$.schema_field"),
  };
  const defaultVal = o["default"] === null ? undefined : optStr(o, "default", "$.schema_field");
  if (defaultVal !== undefined) out.default = defaultVal;
  const help = o["help"] === null ? undefined : optStr(o, "help", "$.schema_field");
  if (help !== undefined) out.help = help;
  const placeholder = o["placeholder"] === null ? undefined : optStr(o, "placeholder", "$.schema_field");
  if (placeholder !== undefined) out.placeholder = placeholder;
  const min = o["min"] === null ? undefined : optStr(o, "min", "$.schema_field");
  if (min !== undefined) out.min = min;
  const max = o["max"] === null ? undefined : optStr(o, "max", "$.schema_field");
  if (max !== undefined) out.max = max;
  const showWhen = o["show_when"] === null ? undefined : optStr(o, "show_when", "$.schema_field");
  if (showWhen !== undefined) out.show_when = showWhen;
  const requires = o["requires"] === null ? undefined : optStr(o, "requires", "$.schema_field");
  if (requires !== undefined) out.requires = requires;
  const group = o["group"] === null ? undefined : optStr(o, "group", "$.schema_field");
  if (group !== undefined) out.group = group;
  if (o["fields"] !== undefined && o["fields"] !== null) out.fields = decodeArray(o["fields"], decodeSchemaField, "$.schema_field.fields");
  if (o["options"] !== undefined && o["options"] !== null) out.options = decodeArray(o["options"], decodeSchemaOption, "$.schema_field.options");
  const secret = o["secret"] === null ? undefined : optBool(o, "secret", "$.schema_field");
  if (secret !== undefined) out.secret = secret;
  const required = o["required"] === null ? undefined : optBool(o, "required", "$.schema_field");
  if (required !== undefined) out.required = required;
  return out;
};

export const decodeSchemaOption: Decoder<SchemaOption> = (v) => {
  const o = asObject(v, "$.schema_option");
  const out: SchemaOption = {
    value: reqStr(o, "value", "$.schema_option"),
    label: reqStr(o, "label", "$.schema_option"),
  };
  return out;
};

export const decodeSchemaSection: Decoder<SchemaSection> = (v) => {
  const o = asObject(v, "$.schema_section");
  const out: SchemaSection = {
    key: reqStr(o, "key", "$.schema_section"),
    title: reqStr(o, "title", "$.schema_section"),
    type: reqStr(o, "type", "$.schema_section"),
  };
  const help = o["help"] === null ? undefined : optStr(o, "help", "$.schema_section");
  if (help !== undefined) out.help = help;
  const requiredGroup = o["required_group"] === null ? undefined : optStr(o, "required_group", "$.schema_section");
  if (requiredGroup !== undefined) out.required_group = requiredGroup;
  const enableKey = o["enable_key"] === null ? undefined : optStr(o, "enable_key", "$.schema_section");
  if (enableKey !== undefined) out.enable_key = enableKey;
  if (o["fields"] !== undefined && o["fields"] !== null) out.fields = decodeArray(o["fields"], decodeSchemaField, "$.schema_section.fields");
  if (o["provider_template"] !== undefined && o["provider_template"] !== null) out.provider_template = decodeArray(o["provider_template"], decodeSchemaField, "$.schema_section.provider_template");
  if (o["providers"] !== undefined && o["providers"] !== null) out.providers = decodeArray(o["providers"], decodeProviderSchema, "$.schema_section.providers");
  return out;
};

export const decodeScorePreview: Decoder<ScorePreview> = (v) => {
  const o = asObject(v, "$.score_preview");
  const out: ScorePreview = {
    tier: reqOneOf(o, "tier", SCORE_TIERS, "$.score_preview"),
    score: reqNum(o, "score", "$.score_preview"),
    score_no_hash: reqNum(o, "score_no_hash", "$.score_preview"),
  };
  return out;
};

export const decodeScores: Decoder<Scores> = (v) => {
  const o = asObject(v, "$.scores");
  const out: Scores = {
    hash: reqNum(o, "hash", "$.scores"),
    source: reqNum(o, "source", "$.scores"),
    release_group: reqNum(o, "release_group", "$.scores"),
    streaming_service: reqNum(o, "streaming_service", "$.scores"),
    video_codec: reqNum(o, "video_codec", "$.scores"),
    hdr: reqNum(o, "hdr", "$.scores"),
    edition: reqNum(o, "edition", "$.scores"),
    season_pack: reqNum(o, "season_pack", "$.scores"),
  };
  return out;
};

export const decodeSearchResult: Decoder<SearchResult> = (v) => {
  const o = asObject(v, "$.search_result");
  const out: SearchResult = {
    provider: reqStr(o, "provider", "$.search_result"),
    language: reqStr(o, "language", "$.search_result"),
    release_name: reqStr(o, "release_name", "$.search_result"),
    matched_by: reqStr(o, "matched_by", "$.search_result"),
    subtitle_id: reqStr(o, "subtitle_id", "$.search_result"),
    tier: reqOneOf(o, "tier", SCORE_TIERS, "$.search_result"),
    score: reqNum(o, "score", "$.search_result"),
    hearing_impaired: reqBool(o, "hearing_impaired", "$.search_result"),
    forced: reqBool(o, "forced", "$.search_result"),
    on_disk: reqBool(o, "on_disk", "$.search_result"),
  };
  if (o["matches"] !== undefined && o["matches"] !== null) out.matches = decodeRecord(o["matches"], (v) => { if (typeof v !== "number") throw new TypeError("expected number"); return v as number; }, "$.search_result.matches");
  return out;
};

export const decodeSearchTarget: Decoder<SearchTarget> = (v) => {
  const o = asObject(v, "$.search_target");
  const out: SearchTarget = {
    code: reqStr(o, "code", "$.search_target"),
    variant: reqStr(o, "variant", "$.search_target"),
  };
  const minScore = o["min_score"] === null ? undefined : optNum(o, "min_score", "$.search_target");
  if (minScore !== undefined) out.min_score = minScore;
  if (o["providers"] !== undefined && o["providers"] !== null) out.providers = decodeArray(o["providers"], (v) => { if (typeof v !== "string") throw new TypeError("expected string"); return v as string; }, "$.search_target.providers");
  if (o["exclude"] !== undefined && o["exclude"] !== null) out.exclude = decodeArray(o["exclude"], (v) => { if (typeof v !== "string") throw new TypeError("expected string"); return v as string; }, "$.search_target.exclude");
  return out;
};

export const decodeSearchTargets: Decoder<SearchTargets> = (v) => {
  const o = asObject(v, "$.search_targets");
  const out: SearchTargets = {
    orig_lang: reqStr(o, "orig_lang", "$.search_targets"),
    audio_langs: o["audio_langs"] === null ? [] : decodeArray(o["audio_langs"], (v) => { if (typeof v !== "string") throw new TypeError("expected string"); return v as string; }, "$.search_targets.audio_langs"),
    targets: o["targets"] === null ? [] : decodeArray(o["targets"], decodeSearchTarget, "$.search_targets.targets"),
  };
  return out;
};

export const decodeSeasonGroup: Decoder<SeasonGroup> = (v) => {
  const o = asObject(v, "$.season_group");
  const out: SeasonGroup = {
    episodes: o["episodes"] === null ? [] : decodeArray(o["episodes"], decodeEpisodeItem, "$.season_group.episodes"),
    season: reqNum(o, "season", "$.season_group"),
  };
  return out;
};

export const decodeSeriesItem: Decoder<SeriesItem> = (v) => {
  const o = asObject(v, "$.series_item");
  const out: SeriesItem = {
    title: reqStr(o, "title", "$.series_item"),
    audio_lang: reqStr(o, "audio_lang", "$.series_item"),
    rule: reqStr(o, "rule", "$.series_item"),
    targets: o["targets"] === null ? [] : decodeArray(o["targets"], decodeCoverageTarget, "$.series_item.targets"),
    id: reqNum(o, "id", "$.series_item"),
    year: reqNum(o, "year", "$.series_item"),
    tvdb_id: reqNum(o, "tvdb_id", "$.series_item"),
    episodes: reqNum(o, "episodes", "$.series_item"),
  };
  const imdbId = o["imdb_id"] === null ? undefined : optStr(o, "imdb_id", "$.series_item");
  if (imdbId !== undefined) out.imdb_id = imdbId;
  const firstAired = o["first_aired"] === null ? undefined : optStr(o, "first_aired", "$.series_item");
  if (firstAired !== undefined) out.first_aired = firstAired;
  if (o["tags"] !== undefined && o["tags"] !== null) out.tags = decodeArray(o["tags"], (v) => { if (typeof v !== "number") throw new TypeError("expected number"); return v as number; }, "$.series_item.tags");
  const excluded = o["excluded"] === null ? undefined : optBool(o, "excluded", "$.series_item");
  if (excluded !== undefined) out.excluded = excluded;
  return out;
};

export const decodeSetupStatus: Decoder<SetupStatus> = (v) => {
  const o = asObject(v, "$.setup_status");
  const out: SetupStatus = {
    setup_required: reqBool(o, "setup_required", "$.setup_status"),
    config_valid: reqBool(o, "config_valid", "$.setup_status"),
  };
  return out;
};

export const decodeSignalData: Decoder<SignalData> = (v) => {
  const o = asObject(v, "$.signal_data");
  const out: SignalData = {
    rp_id: reqStr(o, "rp_id", "$.signal_data"),
    user_id: reqStr(o, "user_id", "$.signal_data"),
    name: reqStr(o, "name", "$.signal_data"),
    display_name: reqStr(o, "display_name", "$.signal_data"),
    credential_ids: o["credential_ids"] === null ? [] : decodeArray(o["credential_ids"], (v) => { if (typeof v !== "string") throw new TypeError("expected string"); return v as string; }, "$.signal_data.credential_ids"),
  };
  return out;
};

export const decodeStateEntry: Decoder<StateEntry> = (v) => {
  const o = asObject(v, "$.state_entry");
  const out: StateEntry = {
    media_imported: reqStr(o, "media_imported", "$.state_entry"),
    title: reqStr(o, "title", "$.state_entry"),
    media_id: reqStr(o, "media_id", "$.state_entry"),
    language: reqStr(o, "language", "$.state_entry"),
    variant: reqOneOf(o, "variant", VARIANTS, "$.state_entry"),
    provider: reqStr(o, "provider", "$.state_entry"),
    path: reqStr(o, "path", "$.state_entry"),
    release_name: reqStr(o, "release_name", "$.state_entry"),
    media_type: reqOneOf(o, "media_type", MEDIA_TYPES, "$.state_entry"),
    id: reqNum(o, "id", "$.state_entry"),
    score: reqNum(o, "score", "$.state_entry"),
    manual: reqBool(o, "manual", "$.state_entry"),
  };
  const imdbId = o["imdb_id"] === null ? undefined : optStr(o, "imdb_id", "$.state_entry");
  if (imdbId !== undefined) out.imdb_id = imdbId;
  const season = o["season"] === null ? undefined : optNum(o, "season", "$.state_entry");
  if (season !== undefined) out.season = season;
  const episode = o["episode"] === null ? undefined : optNum(o, "episode", "$.state_entry");
  if (episode !== undefined) out.episode = episode;
  return out;
};

export const decodeStats: Decoder<Stats> = (v) => {
  const o = asObject(v, "$.stats");
  const out: Stats = {
    last_scan: reqStr(o, "last_scan", "$.stats"),
    downloads: reqNum(o, "downloads", "$.stats"),
    attempts: reqNum(o, "attempts", "$.stats"),
    scan_interval_seconds: reqNum(o, "scan_interval_seconds", "$.stats"),
    total_subs: reqNum(o, "total_subs", "$.stats"),
    total_series: reqNum(o, "total_series", "$.stats"),
    total_movies: reqNum(o, "total_movies", "$.stats"),
    missing_subs: reqNum(o, "missing_subs", "$.stats"),
    partial: reqBool(o, "partial", "$.stats"),
  };
  return out;
};

export const decodeStatusResponse: Decoder<StatusResponse> = (v) => {
  const o = asObject(v, "$.status_response");
  const out: StatusResponse = {
    status: reqStr(o, "status", "$.status_response"),
  };
  return out;
};

export const decodeStructuredConfig: Decoder<StructuredConfig> = (v) => {
  const o = asObject(v, "$.structured_config");
  const out: StructuredConfig = {
    sections: o["sections"] === null ? {} : decodeRecord(o["sections"], (v) => v as unknown, "$.structured_config.sections"),
  };
  if (o["secrets_present"] !== undefined && o["secrets_present"] !== null) out.secrets_present = decodeArray(o["secrets_present"], (v) => { if (typeof v !== "string") throw new TypeError("expected string"); return v as string; }, "$.structured_config.secrets_present");
  return out;
};

export const decodeSubtitleEntry: Decoder<SubtitleEntry> = (v) => {
  const o = asObject(v, "$.subtitle_entry");
  const out: SubtitleEntry = {
    media_id: reqStr(o, "media_id", "$.subtitle_entry"),
    language: reqStr(o, "language", "$.subtitle_entry"),
    variant: reqStr(o, "variant", "$.subtitle_entry"),
    source: reqStr(o, "source", "$.subtitle_entry"),
  };
  const codec = o["codec"] === null ? undefined : optStr(o, "codec", "$.subtitle_entry");
  if (codec !== undefined) out.codec = codec;
  const score = o["score"] === null ? undefined : optNum(o, "score", "$.subtitle_entry");
  if (score !== undefined) out.score = score;
  const ordinal = o["ordinal"] === null ? undefined : optNum(o, "ordinal", "$.subtitle_entry");
  if (ordinal !== undefined) out.ordinal = ordinal;
  const offsetMs = o["offset_ms"] === null ? undefined : optNum(o, "offset_ms", "$.subtitle_entry");
  if (offsetMs !== undefined) out.offset_ms = offsetMs;
  return out;
};

export const decodeSubtitleTarget: Decoder<SubtitleTarget> = (v) => {
  const o = asObject(v, "$.subtitle_target");
  const out: SubtitleTarget = {
    code: reqStr(o, "code", "$.subtitle_target"),
  };
  const minScore = o["min_score"] === null ? undefined : optNum(o, "min_score", "$.subtitle_target");
  if (minScore !== undefined) out.min_score = minScore;
  const variant = o["variant"] === null ? undefined : optStr(o, "variant", "$.subtitle_target");
  if (variant !== undefined) out.variant = variant;
  if (o["variants"] !== undefined && o["variants"] !== null) out.variants = decodeArray(o["variants"], (v) => { if (typeof v !== "string") throw new TypeError("expected string"); return v as string; }, "$.subtitle_target.variants");
  if (o["providers"] !== undefined && o["providers"] !== null) out.providers = decodeArray(o["providers"], (v) => { if (typeof v !== "string") throw new TypeError("expected string"); return v as string; }, "$.subtitle_target.providers");
  if (o["exclude"] !== undefined && o["exclude"] !== null) out.exclude = decodeArray(o["exclude"], (v) => { if (typeof v !== "string") throw new TypeError("expected string"); return v as string; }, "$.subtitle_target.exclude");
  return out;
};

export const decodeSyncAudioRequest: Decoder<SyncAudioRequest> = (v) => {
  const o = asObject(v, "$.sync_audio_request");
  const out: SyncAudioRequest = {
    media_type: reqOneOf(o, "media_type", MEDIA_TYPES, "$.sync_audio_request"),
    media_id: reqStr(o, "media_id", "$.sync_audio_request"),
    language: reqStr(o, "language", "$.sync_audio_request"),
  };
  const variant = o["variant"] === null ? undefined : optStr(o, "variant", "$.sync_audio_request");
  if (variant !== undefined) out.variant = variant;
  const source = o["source"] === null ? undefined : optStr(o, "source", "$.sync_audio_request");
  if (source !== undefined) out.source = source;
  const ordinal = o["ordinal"] === null ? undefined : optNum(o, "ordinal", "$.sync_audio_request");
  if (ordinal !== undefined) out.ordinal = ordinal;
  const dryRun = o["dry_run"] === null ? undefined : optBool(o, "dry_run", "$.sync_audio_request");
  if (dryRun !== undefined) out.dry_run = dryRun;
  return out;
};

export const decodeSyncAudioResponse: Decoder<SyncAudioResponse> = (v) => {
  const o = asObject(v, "$.sync_audio_response");
  const out: SyncAudioResponse = {
    method: reqStr(o, "method", "$.sync_audio_response"),
    offset_ms: reqNum(o, "offset_ms", "$.sync_audio_response"),
    confidence: reqNum(o, "confidence", "$.sync_audio_response"),
    applied: reqBool(o, "applied", "$.sync_audio_response"),
  };
  return out;
};

export const decodeSyncOffsetRequest: Decoder<SyncOffsetRequest> = (v) => {
  const o = asObject(v, "$.sync_offset_request");
  const out: SyncOffsetRequest = {
    media_type: reqOneOf(o, "media_type", MEDIA_TYPES, "$.sync_offset_request"),
    media_id: reqStr(o, "media_id", "$.sync_offset_request"),
    language: reqStr(o, "language", "$.sync_offset_request"),
    offset_ms: reqNum(o, "offset_ms", "$.sync_offset_request"),
  };
  const variant = o["variant"] === null ? undefined : optStr(o, "variant", "$.sync_offset_request");
  if (variant !== undefined) out.variant = variant;
  const source = o["source"] === null ? undefined : optStr(o, "source", "$.sync_offset_request");
  if (source !== undefined) out.source = source;
  const ordinal = o["ordinal"] === null ? undefined : optNum(o, "ordinal", "$.sync_offset_request");
  if (ordinal !== undefined) out.ordinal = ordinal;
  return out;
};

export const decodeUserInfo: Decoder<UserInfo> = (v) => {
  const o = asObject(v, "$.user_info");
  const out: UserInfo = {
    created_at: reqStr(o, "created_at", "$.user_info"),
    username: reqStr(o, "username", "$.user_info"),
    email: reqStr(o, "email", "$.user_info"),
    role: reqOneOf(o, "role", ROLES, "$.user_info"),
    id: reqNum(o, "id", "$.user_info"),
    enabled: reqBool(o, "enabled", "$.user_info"),
  };
  return out;
};

export const decodeWebAuthnLoginBeginResponse: Decoder<WebAuthnLoginBeginResponse> = (v) => {
  const o = asObject(v, "$.web_authn_login_begin_response");
  const out: WebAuthnLoginBeginResponse = {
    session_token: reqStr(o, "session_token", "$.web_authn_login_begin_response"),
  };
  const publicKey = o["publicKey"] === null ? undefined : ((obj: Record<string, unknown>, key: string, path: string) => { const w = asObject(obj[key], path + "." + key); reqStr(asObject(w["publicKey"], path + "." + key + ".publicKey"), "challenge", path + "." + key + ".publicKey"); return w as unknown as { publicKey: PublicKeyCredentialRequestOptionsJSON; mediation?: string }; })(o, "publicKey", "$.web_authn_login_begin_response");
  if (publicKey !== undefined) out.publicKey = publicKey;
  return out;
};

export const decodeWebAuthnRegisterBeginResponse: Decoder<WebAuthnRegisterBeginResponse> = (v) => {
  const o = asObject(v, "$.web_authn_register_begin_response");
  const out: WebAuthnRegisterBeginResponse = {
    session_token: reqStr(o, "session_token", "$.web_authn_register_begin_response"),
  };
  const publicKey = o["publicKey"] === null ? undefined : ((obj: Record<string, unknown>, key: string, path: string) => { const w = asObject(obj[key], path + "." + key); reqStr(asObject(w["publicKey"], path + "." + key + ".publicKey"), "challenge", path + "." + key + ".publicKey"); return w as unknown as { publicKey: PublicKeyCredentialCreationOptionsJSON; mediation?: string }; })(o, "publicKey", "$.web_authn_register_begin_response");
  if (publicKey !== undefined) out.publicKey = publicKey;
  return out;
};

export const decodeEventData: (type: string, v: unknown) => EventData = (type, v) => {
  switch (type) {
    case "coverage": return decodeCoverageEvent(v);
    case "notify": return decodeNotifyEvent(v);
    case "scan:done": return decodeScanEvent(v);
    case "scan:start": return decodeScanEvent(v);
    default: throw new TypeError(`unknown EventData variant: ${type}`);
  }
};

export const decodeEventDataPayload: Decoder<EventData> = (v) => {
  const o = asObject(v, "$.event_data");
  return decodeEventData(reqStr(o, "type", "$.event_data"), o);
};

