// CODE-GENERATED by cmd/wire-codegen, DO NOT EDIT.

import { asObject, reqStr, reqNum, reqBool, optStr, optNum, optBool, reqOneOf, decodeArray, decodeRecord, type Decoder } from "../validators.js";
import type { ActivityEntry, CoverageEvent, CoverageTarget, KeyGenerated, LoginSuccess, MeResponse, MovieItem, NotifyEvent, PasskeyRegistered, ProviderSchema, ProviderStatus, ProvidersResponse, ScanEvent, SchemaField, SchemaOption, SchemaSection, ScorePreview, SearchTarget, SearchTargets, SeriesItem, SetupStatus, SignalData, StateEntry, Stats, SubtitleEntry } from "./types.gen.js";

const ACTIVITY_SOURCES = ["scheduled", "manual"] as const;
const MEDIA_TYPES = ["movie", "episode", "series"] as const;
const NOTIFY_LEVELS = ["error", "success", "info"] as const;
const ROLES = ["admin", "user"] as const;
const SCORE_TIERS = ["excellent", "good", "acceptable", "minimal", "none"] as const;
const VARIANTS = ["standard", "hi", "forced"] as const;

export const decodeActivityEntry: Decoder<ActivityEntry> = (v) => {
  const o = asObject(v, "$.activity_entry");
  const out: ActivityEntry = {
    started_at: reqStr(o, "started_at", "$.activity_entry"),
    id: reqStr(o, "id", "$.activity_entry"),
    action: reqStr(o, "action", "$.activity_entry"),
    detail: reqStr(o, "detail", "$.activity_entry"),
    source: reqOneOf(o, "source", ACTIVITY_SOURCES, "$.activity_entry"),
    done: reqBool(o, "done", "$.activity_entry"),
  };
  const endedAt = optStr(o, "ended_at", "$.activity_entry");
  if (endedAt !== undefined) out.ended_at = endedAt;
  const queued = optBool(o, "queued", "$.activity_entry");
  if (queued !== undefined) out.queued = queued;
  const cancelled = optBool(o, "cancelled", "$.activity_entry");
  if (cancelled !== undefined) out.cancelled = cancelled;
  const failed = optBool(o, "failed", "$.activity_entry");
  if (failed !== undefined) out.failed = failed;
  const current = optNum(o, "current", "$.activity_entry");
  if (current !== undefined) out.current = current;
  const total = optNum(o, "total", "$.activity_entry");
  if (total !== undefined) out.total = total;
  return out;
};

export const decodeCoverageEvent: Decoder<CoverageEvent> = (v) => {
  const o = asObject(v, "$.coverage_event");
  const out: CoverageEvent = {
    media_type: reqOneOf(o, "media_type", MEDIA_TYPES, "$.coverage_event"),
    media_id: reqStr(o, "media_id", "$.coverage_event"),
    language: reqStr(o, "language", "$.coverage_event"),
    variant: reqStr(o, "variant", "$.coverage_event"),
    source: reqStr(o, "source", "$.coverage_event"),
  };
  const path = optStr(o, "path", "$.coverage_event");
  if (path !== undefined) out.path = path;
  return out;
};

export const decodeCoverageTarget: Decoder<CoverageTarget> = (v) => {
  const o = asObject(v, "$.coverage_target");
  const out: CoverageTarget = {
    language: reqStr(o, "language", "$.coverage_target"),
    variant: reqStr(o, "variant", "$.coverage_target"),
    have: reqNum(o, "have", "$.coverage_target"),
    have_ignored: reqNum(o, "have_ignored", "$.coverage_target"),
    total: reqNum(o, "total", "$.coverage_target"),
  };
  return out;
};

export const decodeKeyGenerated: Decoder<KeyGenerated> = (v) => {
  const o = asObject(v, "$.key_generated");
  const out: KeyGenerated = {
    created_at: reqStr(o, "created_at", "$.key_generated"),
    key: reqStr(o, "key", "$.key_generated"),
    key_prefix: reqStr(o, "key_prefix", "$.key_generated"),
    key_suffix: reqStr(o, "key_suffix", "$.key_generated"),
    label: reqStr(o, "label", "$.key_generated"),
    id: reqNum(o, "id", "$.key_generated"),
  };
  return out;
};

export const decodeLoginSuccess: Decoder<LoginSuccess> = (v) => {
  const o = asObject(v, "$.login_success");
  const out: LoginSuccess = {
    redirect: reqStr(o, "redirect", "$.login_success"),
    user: decodeMeResponse(o["user"]),
  };
  return out;
};

export const decodeMeResponse: Decoder<MeResponse> = (v) => {
  const o = asObject(v, "$.me_response");
  const out: MeResponse = {
    username: reqStr(o, "username", "$.me_response"),
    role: reqOneOf(o, "role", ROLES, "$.me_response"),
    id: reqNum(o, "id", "$.me_response"),
    has_passkeys: reqBool(o, "has_passkeys", "$.me_response"),
    oidc_linked: reqBool(o, "oidc_linked", "$.me_response"),
    has_password: reqBool(o, "has_password", "$.me_response"),
    can_link_oidc: reqBool(o, "can_link_oidc", "$.me_response"),
  };
  return out;
};

export const decodeMovieItem: Decoder<MovieItem> = (v) => {
  const o = asObject(v, "$.movie_item");
  const out: MovieItem = {
    title: reqStr(o, "title", "$.movie_item"),
    audio_lang: reqStr(o, "audio_lang", "$.movie_item"),
    rule: reqStr(o, "rule", "$.movie_item"),
    targets: decodeArray(o["targets"], decodeCoverageTarget, "$.movie_item.targets"),
    subs: decodeArray(o["subs"], decodeSubtitleEntry, "$.movie_item.subs"),
    tmdb_id: reqNum(o, "tmdb_id", "$.movie_item"),
    id: reqNum(o, "id", "$.movie_item"),
    year: reqNum(o, "year", "$.movie_item"),
    has_file: reqBool(o, "has_file", "$.movie_item"),
  };
  const imdbId = optStr(o, "imdb_id", "$.movie_item");
  if (imdbId !== undefined) out.imdb_id = imdbId;
  const path = optStr(o, "path", "$.movie_item");
  if (path !== undefined) out.path = path;
  const sceneName = optStr(o, "scene_name", "$.movie_item");
  if (sceneName !== undefined) out.scene_name = sceneName;
  const inCinemas = optStr(o, "in_cinemas", "$.movie_item");
  if (inCinemas !== undefined) out.in_cinemas = inCinemas;
  const digitalRelease = optStr(o, "digital_release", "$.movie_item");
  if (digitalRelease !== undefined) out.digital_release = digitalRelease;
  if (o["tags"] !== undefined) out.tags = decodeArray(o["tags"], (v) => { if (typeof v !== "number") throw new TypeError("expected number"); return v as number; }, "$.movie_item.tags");
  const excluded = optBool(o, "excluded", "$.movie_item");
  if (excluded !== undefined) out.excluded = excluded;
  return out;
};

export const decodeNotifyEvent: Decoder<NotifyEvent> = (v) => {
  const o = asObject(v, "$.notify_event");
  const out: NotifyEvent = {
    level: reqOneOf(o, "level", NOTIFY_LEVELS, "$.notify_event"),
    text: reqStr(o, "text", "$.notify_event"),
  };
  return out;
};

export const decodePasskeyRegistered: Decoder<PasskeyRegistered> = (v) => {
  const o = asObject(v, "$.passkey_registered");
  const out: PasskeyRegistered = {
    created_at: reqStr(o, "created_at", "$.passkey_registered"),
    name: reqStr(o, "name", "$.passkey_registered"),
    transport: reqStr(o, "transport", "$.passkey_registered"),
    id: reqNum(o, "id", "$.passkey_registered"),
  };
  return out;
};

export const decodeProviderSchema: Decoder<ProviderSchema> = (v) => {
  const o = asObject(v, "$.provider_schema");
  const out: ProviderSchema = {
    name: reqStr(o, "name", "$.provider_schema"),
    label: reqStr(o, "label", "$.provider_schema"),
  };
  if (o["settings"] !== undefined) out.settings = decodeArray(o["settings"], decodeSchemaField, "$.provider_schema.settings");
  const alwaysEnabled = optBool(o, "always_enabled", "$.provider_schema");
  if (alwaysEnabled !== undefined) out.always_enabled = alwaysEnabled;
  return out;
};

export const decodeProviderStatus: Decoder<ProviderStatus> = (v) => {
  const o = asObject(v, "$.provider_status");
  const out: ProviderStatus = {
    recent_failures: reqNum(o, "recent_failures", "$.provider_status"),
    threshold: reqNum(o, "threshold", "$.provider_status"),
    timed_out: reqBool(o, "timed_out", "$.provider_status"),
  };
  const lastError = optStr(o, "last_error", "$.provider_status");
  if (lastError !== undefined) out.last_error = lastError;
  const cooldownRemaining = optNum(o, "cooldown_remaining", "$.provider_status");
  if (cooldownRemaining !== undefined) out.cooldown_remaining = cooldownRemaining;
  return out;
};

export const decodeProvidersResponse: Decoder<ProvidersResponse> = (v) => {
  const o = asObject(v, "$.providers_response");
  const out: ProvidersResponse = {
    enabled: reqBool(o, "enabled", "$.providers_response"),
  };
  if (o["providers"] !== undefined) out.providers = decodeRecord(o["providers"], decodeProviderStatus, "$.providers_response.providers");
  return out;
};

export const decodeScanEvent: Decoder<ScanEvent> = (v) => {
  const o = asObject(v, "$.scan_event");
  const out: ScanEvent = {
    action: reqStr(o, "action", "$.scan_event"),
    detail: reqStr(o, "detail", "$.scan_event"),
    source: reqOneOf(o, "source", ACTIVITY_SOURCES, "$.scan_event"),
  };
  const succeeded = optBool(o, "succeeded", "$.scan_event");
  if (succeeded !== undefined) out.succeeded = succeeded;
  return out;
};

export const decodeSchemaField: Decoder<SchemaField> = (v) => {
  const o = asObject(v, "$.schema_field");
  const out: SchemaField = {
    key: reqStr(o, "key", "$.schema_field"),
    label: reqStr(o, "label", "$.schema_field"),
    type: reqStr(o, "type", "$.schema_field"),
  };
  const defaultVal = optStr(o, "default", "$.schema_field");
  if (defaultVal !== undefined) out.default = defaultVal;
  const help = optStr(o, "help", "$.schema_field");
  if (help !== undefined) out.help = help;
  const placeholder = optStr(o, "placeholder", "$.schema_field");
  if (placeholder !== undefined) out.placeholder = placeholder;
  const min = optStr(o, "min", "$.schema_field");
  if (min !== undefined) out.min = min;
  const max = optStr(o, "max", "$.schema_field");
  if (max !== undefined) out.max = max;
  const showWhen = optStr(o, "show_when", "$.schema_field");
  if (showWhen !== undefined) out.show_when = showWhen;
  const requires = optStr(o, "requires", "$.schema_field");
  if (requires !== undefined) out.requires = requires;
  const group = optStr(o, "group", "$.schema_field");
  if (group !== undefined) out.group = group;
  if (o["fields"] !== undefined) out.fields = decodeArray(o["fields"], decodeSchemaField, "$.schema_field.fields");
  if (o["options"] !== undefined) out.options = decodeArray(o["options"], decodeSchemaOption, "$.schema_field.options");
  const secret = optBool(o, "secret", "$.schema_field");
  if (secret !== undefined) out.secret = secret;
  const required = optBool(o, "required", "$.schema_field");
  if (required !== undefined) out.required = required;
  return out;
};

export const decodeSchemaOption: Decoder<SchemaOption> = (v) => {
  const o = asObject(v, "$.schema_option");
  const out: SchemaOption = {
    value: reqStr(o, "value", "$.schema_option"),
    label: reqStr(o, "label", "$.schema_option"),
  };
  return out;
};

export const decodeSchemaSection: Decoder<SchemaSection> = (v) => {
  const o = asObject(v, "$.schema_section");
  const out: SchemaSection = {
    key: reqStr(o, "key", "$.schema_section"),
    title: reqStr(o, "title", "$.schema_section"),
    type: reqStr(o, "type", "$.schema_section"),
  };
  const help = optStr(o, "help", "$.schema_section");
  if (help !== undefined) out.help = help;
  const requiredGroup = optStr(o, "required_group", "$.schema_section");
  if (requiredGroup !== undefined) out.required_group = requiredGroup;
  const enableKey = optStr(o, "enable_key", "$.schema_section");
  if (enableKey !== undefined) out.enable_key = enableKey;
  if (o["fields"] !== undefined) out.fields = decodeArray(o["fields"], decodeSchemaField, "$.schema_section.fields");
  if (o["provider_template"] !== undefined) out.provider_template = decodeArray(o["provider_template"], decodeSchemaField, "$.schema_section.provider_template");
  if (o["providers"] !== undefined) out.providers = decodeArray(o["providers"], decodeProviderSchema, "$.schema_section.providers");
  return out;
};

export const decodeScorePreview: Decoder<ScorePreview> = (v) => {
  const o = asObject(v, "$.score_preview");
  const out: ScorePreview = {
    tier: reqOneOf(o, "tier", SCORE_TIERS, "$.score_preview"),
    score: reqNum(o, "score", "$.score_preview"),
    score_no_hash: reqNum(o, "score_no_hash", "$.score_preview"),
  };
  return out;
};

export const decodeSearchTarget: Decoder<SearchTarget> = (v) => {
  const o = asObject(v, "$.search_target");
  const out: SearchTarget = {
    code: reqStr(o, "code", "$.search_target"),
    variant: reqStr(o, "variant", "$.search_target"),
  };
  const minScore = optNum(o, "min_score", "$.search_target");
  if (minScore !== undefined) out.min_score = minScore;
  if (o["providers"] !== undefined) out.providers = decodeArray(o["providers"], (v) => { if (typeof v !== "string") throw new TypeError("expected string"); return v as string; }, "$.search_target.providers");
  if (o["exclude"] !== undefined) out.exclude = decodeArray(o["exclude"], (v) => { if (typeof v !== "string") throw new TypeError("expected string"); return v as string; }, "$.search_target.exclude");
  return out;
};

export const decodeSearchTargets: Decoder<SearchTargets> = (v) => {
  const o = asObject(v, "$.search_targets");
  const out: SearchTargets = {
    orig_lang: reqStr(o, "orig_lang", "$.search_targets"),
    audio_langs: decodeArray(o["audio_langs"], (v) => { if (typeof v !== "string") throw new TypeError("expected string"); return v as string; }, "$.search_targets.audio_langs"),
    targets: decodeArray(o["targets"], decodeSearchTarget, "$.search_targets.targets"),
  };
  return out;
};

export const decodeSeriesItem: Decoder<SeriesItem> = (v) => {
  const o = asObject(v, "$.series_item");
  const out: SeriesItem = {
    title: reqStr(o, "title", "$.series_item"),
    audio_lang: reqStr(o, "audio_lang", "$.series_item"),
    rule: reqStr(o, "rule", "$.series_item"),
    targets: decodeArray(o["targets"], decodeCoverageTarget, "$.series_item.targets"),
    id: reqNum(o, "id", "$.series_item"),
    year: reqNum(o, "year", "$.series_item"),
    tvdb_id: reqNum(o, "tvdb_id", "$.series_item"),
    episodes: reqNum(o, "episodes", "$.series_item"),
  };
  const imdbId = optStr(o, "imdb_id", "$.series_item");
  if (imdbId !== undefined) out.imdb_id = imdbId;
  const firstAired = optStr(o, "first_aired", "$.series_item");
  if (firstAired !== undefined) out.first_aired = firstAired;
  if (o["tags"] !== undefined) out.tags = decodeArray(o["tags"], (v) => { if (typeof v !== "number") throw new TypeError("expected number"); return v as number; }, "$.series_item.tags");
  const excluded = optBool(o, "excluded", "$.series_item");
  if (excluded !== undefined) out.excluded = excluded;
  return out;
};

export const decodeSetupStatus: Decoder<SetupStatus> = (v) => {
  const o = asObject(v, "$.setup_status");
  const out: SetupStatus = {
    setup_required: reqBool(o, "setup_required", "$.setup_status"),
    config_valid: reqBool(o, "config_valid", "$.setup_status"),
  };
  return out;
};

export const decodeSignalData: Decoder<SignalData> = (v) => {
  const o = asObject(v, "$.signal_data");
  const out: SignalData = {
    rp_id: reqStr(o, "rp_id", "$.signal_data"),
    user_id: reqStr(o, "user_id", "$.signal_data"),
    name: reqStr(o, "name", "$.signal_data"),
    display_name: reqStr(o, "display_name", "$.signal_data"),
    credential_ids: decodeArray(o["credential_ids"], (v) => { if (typeof v !== "string") throw new TypeError("expected string"); return v as string; }, "$.signal_data.credential_ids"),
  };
  return out;
};

export const decodeStateEntry: Decoder<StateEntry> = (v) => {
  const o = asObject(v, "$.state_entry");
  const out: StateEntry = {
    media_imported: reqStr(o, "media_imported", "$.state_entry"),
    title: reqStr(o, "title", "$.state_entry"),
    media_id: reqStr(o, "media_id", "$.state_entry"),
    language: reqStr(o, "language", "$.state_entry"),
    variant: reqOneOf(o, "variant", VARIANTS, "$.state_entry"),
    provider: reqStr(o, "provider", "$.state_entry"),
    path: reqStr(o, "path", "$.state_entry"),
    release_name: reqStr(o, "release_name", "$.state_entry"),
    media_type: reqOneOf(o, "media_type", MEDIA_TYPES, "$.state_entry"),
    id: reqNum(o, "id", "$.state_entry"),
    score: reqNum(o, "score", "$.state_entry"),
    manual: reqBool(o, "manual", "$.state_entry"),
  };
  const imdbId = optStr(o, "imdb_id", "$.state_entry");
  if (imdbId !== undefined) out.imdb_id = imdbId;
  const season = optNum(o, "season", "$.state_entry");
  if (season !== undefined) out.season = season;
  const episode = optNum(o, "episode", "$.state_entry");
  if (episode !== undefined) out.episode = episode;
  return out;
};

export const decodeStats: Decoder<Stats> = (v) => {
  const o = asObject(v, "$.stats");
  const out: Stats = {
    last_scan: reqStr(o, "last_scan", "$.stats"),
    downloads: reqNum(o, "downloads", "$.stats"),
    attempts: reqNum(o, "attempts", "$.stats"),
    scan_interval_seconds: reqNum(o, "scan_interval_seconds", "$.stats"),
    total_subs: reqNum(o, "total_subs", "$.stats"),
    total_series: reqNum(o, "total_series", "$.stats"),
    total_movies: reqNum(o, "total_movies", "$.stats"),
    missing_subs: reqNum(o, "missing_subs", "$.stats"),
    partial: reqBool(o, "partial", "$.stats"),
  };
  return out;
};

export const decodeSubtitleEntry: Decoder<SubtitleEntry> = (v) => {
  const o = asObject(v, "$.subtitle_entry");
  const out: SubtitleEntry = {
    media_id: reqStr(o, "media_id", "$.subtitle_entry"),
    language: reqStr(o, "language", "$.subtitle_entry"),
    variant: reqStr(o, "variant", "$.subtitle_entry"),
    source: reqStr(o, "source", "$.subtitle_entry"),
  };
  const codec = optStr(o, "codec", "$.subtitle_entry");
  if (codec !== undefined) out.codec = codec;
  const path = optStr(o, "path", "$.subtitle_entry");
  if (path !== undefined) out.path = path;
  const videoPath = optStr(o, "video_path", "$.subtitle_entry");
  if (videoPath !== undefined) out.video_path = videoPath;
  const score = optNum(o, "score", "$.subtitle_entry");
  if (score !== undefined) out.score = score;
  const offsetMs = optNum(o, "offset_ms", "$.subtitle_entry");
  if (offsetMs !== undefined) out.offset_ms = offsetMs;
  return out;
};

