// CODE-GENERATED by cmd/wire-codegen, DO NOT EDIT.
//
// NOTE: subflux SSE handling is inline in events.ts.
// This registry is generated for future use. Import and call
// registerAllSSEDecoders() once events.ts adopts the pattern.

import { decodeCoverageEvent, decodeNotifyEvent, decodeScanEvent } from "./decoders.gen.js";
import type { Decoder } from "../validators.js";

const registry = new Map<string, Decoder<unknown>>();

export function registerAllSSEDecoders(): void {
  registry.set("coverage", decodeCoverageEvent as Decoder<unknown>);
  registry.set("notify", decodeNotifyEvent as Decoder<unknown>);
  registry.set("scan:start", decodeScanEvent as Decoder<unknown>);
  registry.set("scan:done", decodeScanEvent as Decoder<unknown>);
}

export function getSSEDecoder(eventType: string): Decoder<unknown> | undefined {
  return registry.get(eventType);
}
