// CODE-GENERATED by cmd/wire-codegen, DO NOT EDIT.

export type ActivitySource = "scheduled" | "manual";

export type MediaType = "movie" | "episode" | "series";

export type NotifyLevel = "error" | "success" | "info";

export type Role = "admin" | "user";

export type ScoreTier = "excellent" | "good" | "acceptable" | "minimal" | "none";

export type Variant = "standard" | "hi" | "forced";

export interface ActivityEntry {
  started_at: string;
  ended_at?: string;
  id: string;
  action: string;
  detail: string;
  source: ActivitySource;
  done: boolean;
  queued?: boolean;
  cancelled?: boolean;
  failed?: boolean;
  current?: number;
  total?: number;
}

export interface CoverageEvent {
  media_type: MediaType;
  media_id: string;
  language: string;
  variant: string;
  source: string;
  path?: string;
}

export interface CoverageTarget {
  language: string;
  variant: string;
  have: number;
  have_ignored: number;
  total: number;
}

export interface KeyGenerated {
  created_at: string;
  key: string;
  key_prefix: string;
  key_suffix: string;
  label: string;
  id: number;
}

export interface LoginSuccess {
  redirect: string;
  user: MeResponse;
}

export interface MeResponse {
  username: string;
  role: Role;
  id: number;
  totp_enabled: boolean;
  has_passkeys: boolean;
}

export interface MovieItem {
  title: string;
  imdb_id?: string;
  path?: string;
  scene_name?: string;
  in_cinemas?: string;
  digital_release?: string;
  audio_lang: string;
  rule: string;
  targets: CoverageTarget[];
  subs: SubtitleEntry[];
  tags?: number[];
  tmdb_id: number;
  id: number;
  year: number;
  has_file: boolean;
  excluded?: boolean;
}

export interface NotifyEvent {
  level: NotifyLevel;
  text: string;
}

export interface PasskeyRegistered {
  created_at: string;
  name: string;
  transport: string;
  id: number;
}

export interface ProviderSchema {
  name: string;
  label: string;
  settings?: SchemaField[];
  always_enabled?: boolean;
}

export interface ProviderStatus {
  last_error?: string;
  cooldown_remaining?: number;
  recent_failures: number;
  threshold: number;
  timed_out: boolean;
}

export interface ProvidersResponse {
  providers?: Record<string, ProviderStatus>;
  enabled: boolean;
}

export interface RecoveryCodes {
  recovery_codes: string[];
}

export interface RecoveryCodesStatus {
  remaining: number;
  total: number;
}

export interface ScanEvent {
  action: string;
  detail: string;
  source: ActivitySource;
  succeeded?: boolean;
}

export interface SchemaField {
  key: string;
  label: string;
  type: string;
  default?: string;
  help?: string;
  placeholder?: string;
  min?: string;
  max?: string;
  show_when?: string;
  requires?: string;
  group?: string;
  fields?: SchemaField[];
  options?: SchemaOption[];
  secret?: boolean;
  required?: boolean;
}

export interface SchemaOption {
  value: string;
  label: string;
}

export interface SchemaSection {
  key: string;
  title: string;
  type: string;
  help?: string;
  required_group?: string;
  enable_key?: string;
  fields?: SchemaField[];
  provider_template?: SchemaField[];
  providers?: ProviderSchema[];
}

export interface ScorePreview {
  tier: ScoreTier;
  score: number;
  score_no_hash: number;
}

export interface SearchTarget {
  min_score?: number;
  code: string;
  variant: string;
  providers?: string[];
  exclude?: string[];
}

export interface SearchTargets {
  orig_lang: string;
  audio_langs: string[];
  targets: SearchTarget[];
}

export interface SeriesItem {
  title: string;
  imdb_id?: string;
  first_aired?: string;
  audio_lang: string;
  rule: string;
  targets: CoverageTarget[];
  tags?: number[];
  id: number;
  year: number;
  tvdb_id: number;
  episodes: number;
  excluded?: boolean;
}

export interface SetupStatus {
  setup_required: boolean;
  config_valid: boolean;
}

export interface SignalData {
  rp_id: string;
  user_id: string;
  name: string;
  display_name: string;
  credential_ids: string[];
}

export interface StateEntry {
  media_imported: string;
  title: string;
  media_id: string;
  language: string;
  provider: string;
  path: string;
  release_name: string;
  imdb_id?: string;
  media_type: MediaType;
  id: number;
  score: number;
  season?: number;
  episode?: number;
  manual: boolean;
}

export interface Stats {
  last_scan: string;
  downloads: number;
  attempts: number;
  scan_interval_seconds: number;
  total_subs: number;
  total_series: number;
  total_movies: number;
  missing_subs: number;
  partial: boolean;
}

export interface SubtitleEntry {
  media_id: string;
  language: string;
  variant: string;
  source: string;
  codec?: string;
  path?: string;
  video_path?: string;
  score?: number;
  offset_ms?: number;
}

