// CODE-GENERATED by cmd/wire-codegen, DO NOT EDIT.

export type ActivitySource = "scheduled" | "manual";

export type MediaType = "movie" | "episode" | "series";

export type NotifyLevel = "error" | "success" | "info";

export type Role = "admin" | "user";

export type ScoreTier = "excellent" | "good" | "acceptable" | "minimal" | "none";

export type Variant = "standard" | "hi" | "forced";

/** Entry represents an ongoing or recent action. */
export interface ActivityEntry {
  started_at: string;
  ended_at?: string;
  id: string;
  action: string;
  detail: string;
  source: ActivitySource;
  done: boolean;
  queued?: boolean;
  cancelled?: boolean;
  failed?: boolean;
  current?: number;
  total?: number;
}

/** CoverageEvent is the data payload for coverage updates. */
export interface CoverageEvent {
  media_type: MediaType;
  media_id: string;
  language: string;
  variant: string;
  source: string;
  path?: string;
}

/** TargetCoverage tracks coverage for a single expected subtitle target. */
export interface CoverageTarget {
  language: string;
  variant: string;
  have: number;
  have_ignored: number;
  total: number;
}

/** KeyGenerated is the JSON response after generating an API key. */
export interface KeyGenerated {
  created_at: string;
  key: string;
  key_prefix: string;
  key_suffix: string;
  label: string;
  id: number;
}

/** LoginSuccess is the JSON response after successful login. */
export interface LoginSuccess {
  redirect: string;
  user: MeResponse;
}

/** MeResponse is the JSON response for GET /api/auth/me. */
export interface MeResponse {
  username: string;
  role: Role;
  id: number;
  has_passkeys: boolean;
  oidc_linked: boolean;
  has_password: boolean;
  can_link_oidc: boolean;
}

/** MovieItem is the coverage summary for one movie. */
export interface MovieItem {
  title: string;
  imdb_id?: string;
  path?: string;
  scene_name?: string;
  in_cinemas?: string;
  digital_release?: string;
  audio_lang: string;
  rule: string;
  targets: CoverageTarget[];
  subs: SubtitleEntry[];
  tags?: number[];
  tmdb_id: number;
  id: number;
  year: number;
  has_file: boolean;
  excluded?: boolean;
}

/** NotifyEvent is the data payload for toast notifications pushed to the UI. */
export interface NotifyEvent {
  level: NotifyLevel;
  text: string;
}

/** PasskeyRegistered is the JSON response after successful passkey registration. */
export interface PasskeyRegistered {
  created_at: string;
  name: string;
  transport: string;
  id: number;
}

/** ProviderSchema describes a single provider's settings fields. */
export interface ProviderSchema {
  name: string;
  label: string;
  settings?: SchemaField[];
  always_enabled?: boolean;
}

/** ProviderStatus is the state of a single provider's timeout. */
export interface ProviderStatus {
  last_error?: string;
  cooldown_remaining?: number;
  recent_failures: number;
  threshold: number;
  timed_out: boolean;
}

/** ProvidersResponse is the JSON response for GET /api/providers/timeout. */
export interface ProvidersResponse {
  providers?: Record<string, ProviderStatus>;
  enabled: boolean;
}

/**
 * ScanEvent is the data payload for scan:start and scan:done. Action and
 * Detail mirror the activity log entry (e.g. "Full Scan" / "Searching
 * library for missing subtitles"). Source is "scheduled" or "manual".
 * Succeeded is meaningful only on scan:done; false indicates the scan
 * ended via activity.fail rather than activity.end.
 */
export interface ScanEvent {
  action: string;
  detail: string;
  source: ActivitySource;
  succeeded?: boolean;
}

/** SchemaField describes a single configuration field for the UI. */
export interface SchemaField {
  key: string;
  label: string;
  type: string;
  default?: string;
  help?: string;
  placeholder?: string;
  min?: string;
  max?: string;
  show_when?: string;
  requires?: string;
  group?: string;
  fields?: SchemaField[];
  options?: SchemaOption[];
  secret?: boolean;
  required?: boolean;
}

/** SchemaOption is a value+label pair for select fields. */
export interface SchemaOption {
  value: string;
  label: string;
}

/** SchemaSection describes a top-level config section. */
export interface SchemaSection {
  key: string;
  title: string;
  type: string;
  help?: string;
  required_group?: string;
  enable_key?: string;
  fields?: SchemaField[];
  provider_template?: SchemaField[];
  providers?: ProviderSchema[];
}

/** ScorePreview is the JSON response for POST /api/score/preview. */
export interface ScorePreview {
  tier: ScoreTier;
  score: number;
  score_no_hash: number;
}

/** SearchTarget describes a single subtitle search target in the API response. */
export interface SearchTarget {
  min_score?: number;
  code: string;
  variant: string;
  providers?: string[];
  exclude?: string[];
}

/** SearchTargets is the JSON response for GET /api/search/targets. */
export interface SearchTargets {
  orig_lang: string;
  audio_langs: string[];
  targets: SearchTarget[];
}

/** SeriesItem is the coverage summary for one TV series. */
export interface SeriesItem {
  title: string;
  imdb_id?: string;
  first_aired?: string;
  audio_lang: string;
  rule: string;
  targets: CoverageTarget[];
  tags?: number[];
  id: number;
  year: number;
  tvdb_id: number;
  episodes: number;
  excluded?: boolean;
}

/** SetupStatus is the JSON response for GET /api/auth/setup. */
export interface SetupStatus {
  setup_required: boolean;
  config_valid: boolean;
}

/** SignalData is the JSON response for GET /api/auth/webauthn/signal-data. */
export interface SignalData {
  rp_id: string;
  user_id: string;
  name: string;
  display_name: string;
  credential_ids: string[];
}

/** StateEntry represents a subtitle state record for API responses. */
export interface StateEntry {
  media_imported: string;
  title: string;
  media_id: string;
  language: string;
  provider: string;
  path: string;
  release_name: string;
  imdb_id?: string;
  media_type: MediaType;
  id: number;
  score: number;
  season?: number;
  episode?: number;
  manual: boolean;
}

/** Stats is the JSON response for GET /api/stats. */
export interface Stats {
  last_scan: string;
  downloads: number;
  attempts: number;
  scan_interval_seconds: number;
  total_subs: number;
  total_series: number;
  total_movies: number;
  missing_subs: number;
  partial: boolean;
}

/** SubtitleEntry is the JSON shape returned by coverage queries. */
export interface SubtitleEntry {
  media_id: string;
  language: string;
  variant: string;
  source: string;
  codec?: string;
  path?: string;
  video_path?: string;
  score?: number;
  offset_ms?: number;
}

