// Command wire-codegen generates TypeScript interfaces and validating decoders
// from Go wire types using the wiregen library (AST-based;
// github.com/cplieger/wiregen). Output lands in internal/server/static-src/wire/
// (types.gen.ts + decoders.gen.ts) and is consumed directly by ~13 client
// modules; api-types.ts re-exports the common surface for callers that want a
// single import seam.
//
// Run: go run ./cmd/wire-codegen   (from the subflux repo root)
package main

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/cplieger/subflux/internal/api"
	"github.com/cplieger/subflux/internal/server/activity"
	"github.com/cplieger/subflux/internal/server/coverage"
	"github.com/cplieger/subflux/internal/server/coveragehandlers"
	"github.com/cplieger/subflux/internal/server/events"
	"github.com/cplieger/wiregen"
)

func main() {
	r := wiregen.NewRegistry(
		wiregen.WithValidatorsImport("../validators.js"),
		wiregen.WithHeaderComment("// CODE-GENERATED by cmd/wire-codegen, DO NOT EDIT.\n\n"),
	)

	r.Types = []wiregen.WireType{
		wiregen.TypeRef[coverage.TargetCoverage](),
		wiregen.TypeRef[coveragehandlers.SeriesItem](),
		wiregen.TypeRef[coveragehandlers.MovieItem](),
		wiregen.TypeRef[api.SubtitleEntry](),
		wiregen.TypeRef[api.Stats](),
		wiregen.TypeRef[api.ProviderStatus](),
		wiregen.TypeRef[api.ProvidersResponse](),
		wiregen.TypeRef[api.MeResponse](),
		wiregen.TypeRef[api.SchemaField](),
		wiregen.TypeRef[api.SchemaOption](),
		wiregen.TypeRef[api.SchemaSection](),
		wiregen.TypeRef[api.ProviderSchema](),
		wiregen.TypeRef[api.StateEntry](),
		wiregen.TypeRef[api.ScorePreview](),
		wiregen.TypeRef[api.SearchTarget](),
		wiregen.TypeRef[api.SearchTargets](),
		wiregen.TypeRef[api.SetupStatus](),
		wiregen.TypeRef[api.LoginSuccess](),
		wiregen.TypeRef[api.SignalData](),
		wiregen.TypeRef[api.PasskeyRegistered](),
		wiregen.TypeRef[api.KeyGenerated](),
		wiregen.TypeRef[events.CoverageEvent](),
		wiregen.TypeRef[events.NotifyEvent](),
		wiregen.TypeRef[events.ScanEvent](),
		wiregen.TypeRef[activity.Entry](),
	}

	// Enum values are auto-discovered from each type's const block in source.
	// MediaType keeps explicit values: "series" is a valid value with no const.
	r.Enums = map[string]wiregen.EnumDef{
		"MediaType": {Values: []string{"movie", "episode", "series"}},
		"Variant":   {}, "Role": {}, "ScoreTier": {},
		"NotifyLevel": {}, "ActivitySource": {},
	}

	// Wire DTOs are named as their TS interface, so no overrides are needed
	// except where the Go name would stutter against its package name.
	r.TSNameOverride = map[string]string{
		"TargetCoverage": "CoverageTarget", // coverage.TargetCoverage → avoid stutter
		"Entry":          "ActivityEntry",  // activity.Entry → avoid stutter
	}

	// No SSEEvents: subflux dispatches SSE via native EventSource named events
	// (events.ts) and decodes each payload with the generated decoders, so the
	// central registry.gen.ts isn't needed.
	outDir := filepath.Join("internal", "server", "static-src", "wire")
	if err := r.Generate(outDir); err != nil {
		fmt.Fprintf(os.Stderr, "wire-codegen: %v\n", err)
		os.Exit(1)
	}
	fmt.Println("wire-codegen: generated " + outDir + "/{types,decoders}.gen.ts")
}
